export const R098_PROMOTION_CHECKLIST_VERSION = '0.1.0-research' as const;

export const R098_REQUIRED_GATES = Object.freeze([
  'CLAIM_SCOPE_FROZEN',
  'METHODOLOGY_AND_SOURCE_SCOPE_IDENTIFIED',
  'WORK_EDITION_WITNESS_PROVENANCE_BOUND',
  'PASSAGE_PROPOSITION_BINDING_COMPLETE',
  'RIGHTS_REUSE_CONSTRAINTS_RECORDED',
  'COUNTEREXAMPLES_AND_DIVERGENCE_REVIEWED',
  'CALCULATION_TIME_CONVENTIONS_EXPLICIT',
  'EXECUTABLE_PREDICATES_NO_HIDDEN_GUESSES',
  'AMBIGUITY_UNKNOWN_FAIL_CLOSED',
  'DETERMINISTIC_AND_REGRESSION_TESTS_PASS',
  'CONTENT_HASH_VERSION_SUPERSESSION_PINNED',
  'REQUIRED_DOMAIN_REVIEW_ATTESTATION_SATISFIED',
  'PRODUCT_LANGUAGE_WITHIN_SOURCE_BOUND_SEMANTICS',
  'REQUIRED_SHADOW_STAGING_EVIDENCE_COMPLETE',
  'EXPLICIT_GOVERNANCE_AUTHORITY_DECISION_RECORDED',
] as const);

export const R098_CHECKLIST_STATES = Object.freeze([
  'BLOCKED','RESEARCH_READY','REVIEW_READY','SHADOW_READY','PROMOTION_ELIGIBLE',
] as const);

export const R098_REJECTED_IMPLICIT_PROMOTION = Object.freeze([
  'MERGE_IMPLIES_PROMOTION',
  'TEST_PASS_IMPLIES_PROMOTION',
  'SOURCE_COUNT_IMPLIES_PROMOTION',
  'EXPERT_VOTE_IMPLIES_PROMOTION',
  'PRODUCT_DEMAND_IMPLIES_PROMOTION',
  'ELIGIBLE_STATE_AUTO_MUTATES_LIFECYCLE',
] as const);

export const R098_AUTHORITY = Object.freeze({
  status:'FAIL_CLOSED_PROMOTION_CHECKLIST_DEFINED' as const,
  requiredGateCount:15,
  promotionEligibleAutoPromotes:false,
  lifecycleMutationRequiresSeparateAuthorityAction:true,
  productionAuthorityPromoted:false,
});
