export const R094_COUNTEREXAMPLE_REGISTRY_VERSION = '0.2.0-research' as const;

export const R094_COUNTEREXAMPLE_CLASSES = Object.freeze([
  'SOURCE_CONTRADICTION',
  'SOURCE_EXCEPTION',
  'CALCULATION_EDGE_CASE',
  'IMPLEMENTATION_REGRESSION',
  'CROSS_SCHOOL_DIVERGENCE',
  'TEMPORAL_CONTEXT_REVERSAL',
  'DOMAIN_PROJECTION_FAILURE',
  'UNKNOWN_OR_UNRESOLVED',
] as const);

export const R094_TARGET_KINDS = Object.freeze([
  'RULE_VERSION',
  'METHODOLOGY_VERSION',
] as const);

export const R094_CHALLENGE_KINDS = Object.freeze([
  'INPUT_VECTOR',
  'SOURCE_PROPOSITION',
  'REPRODUCED_RUNTIME_RESULT',
] as const);

export const R094_EVIDENCE_STATES = Object.freeze([
  'UNVERIFIED',
  'REPRODUCED',
  'SOURCE_VERIFIED',
  'INCONCLUSIVE',
] as const);

export const R094_ADJUDICATION_OUTCOMES = Object.freeze([
  'OPEN',
  'RULE_NARROWED',
  'RULE_SUPERSEDED',
  'NOT_APPLICABLE',
  'NO_RULE_CHANGE',
  'INCONCLUSIVE',
] as const);

export const R094_SCOPE_IMPACT_STATES = Object.freeze([
  'NONE',
  'NARROWER_APPLICABILITY',
  'SUPERSEDED_TARGET',
  'IMPLEMENTATION_ONLY',
  'UNRESOLVED',
] as const);

export const R094_REQUIRED_FIELDS = Object.freeze([
  'COUNTEREXAMPLE_ID',
  'TARGET_KIND',
  'TARGET_ID',
  'TARGET_VERSION',
  'TARGET_CONTENT_HASH',
  'TARGET_SCOPE_REF',
  'CHALLENGE_KIND',
  'CHALLENGE_REF',
  'EVIDENCE_PROVENANCE_REFS',
  'EXPECTED_BEHAVIOR',
  'CONTRADICTORY_BEHAVIOR',
  'EVIDENCE_STATE',
  'ADJUDICATION_OUTCOME',
  'SCOPE_IMPACT',
  'ADJUDICATION_HISTORY',
] as const);

export const R094_HISTORY_RULES = Object.freeze([
  'ORIGINAL_TARGET_IDENTITY_IMMUTABLE',
  'ORIGINAL_CHALLENGE_IDENTITY_IMMUTABLE',
  'ADJUDICATION_APPEND_ONLY',
  'SUPERSESSION_PRESERVES_OLD_AND_SUCCESSOR_TARGET_REFS',
  'COUNTEREXAMPLE_NOT_DELETED_WHEN_RULE_REVISED',
] as const);

export const R094_CROSS_CONTRACT_RULES = Object.freeze([
  'R093_PROVENANCE_REFS_MAY_BE_REFERENCED',
  'R093_GRAPH_CONNECTIVITY_DOES_NOT_AUTO_ADJUDICATE',
  'SOURCE_PROPOSITION_IS_NOT_REPRODUCED_RUNTIME_EVIDENCE',
  'REPRODUCED_RUNTIME_EVIDENCE_IS_NOT_SOURCE_CONTRADICTION_WITHOUT_SOURCE_REF',
] as const);

export const R094_REJECTED_SHORTCUTS = Object.freeze([
  'COUNTEREXAMPLE_AUTO_INVALIDATES_RULE',
  'TARGET_VERSION_OR_HASH_OMITTED',
  'RULE_REVISION_REWRITES_COUNTEREXAMPLE_HISTORY',
  'COUNTEREXAMPLE_COUNT_EQUALS_CONFIDENCE',
  'SOURCE_PROPOSITION_EQUALS_REPRODUCED_RUNTIME_CASE',
  'REPRODUCED_RUNTIME_CASE_EQUALS_SOURCE_CONTRADICTION',
  'R093_GRAPH_CONNECTIVITY_AUTO_ADJUDICATES_COUNTEREXAMPLE',
  'PRODUCTION_CHANGES_FROM_COUNTEREXAMPLE_REGISTRY_DIRECTLY',
] as const);

export const R094_GOVERNANCE = Object.freeze({
  status: 'COUNTEREXAMPLE_REGISTRY_CONTRACT_DEFINED' as const,
  automaticRuleInvalidation: false,
  automaticRuleNarrowing: false,
  silentCounterexampleDeletion: false,
  supersessionPreservesHistory: true,
  evidenceStateSeparatedFromAdjudication: true,
  exactTargetVersionAndHashRequired: true,
  counterexampleCountAsConfidence: false,
  productionChangeRequiresGovernedPromotion: true,
  productionAuthorityPromoted: false,
});
