export const R088_TIMEZONE_SOLAR_BOUNDARY_VERSION = '0.1.0-research' as const;

export const R088_TRANSFORMATION_LAYERS = Object.freeze([
  'SOURCE_LOCAL_WALL_CLOCK',
  'HISTORICAL_CIVIL_TIME_RESOLUTION',
  'OPTIONAL_GOVERNED_SOLAR_TIME_TRANSFORMATION',
  'CALENDAR_PILLAR_CALCULATION',
] as const);

export const R088_SENSITIVITY_DIMENSIONS = Object.freeze([
  'TIMEZONE_AUTHORITY_VARIANT',
  'HISTORICAL_CIVIL_TIME_REGIME',
  'LONGITUDE_CORRECTION_POLICY',
  'APPARENT_SOLAR_COMPONENT',
  'BOUNDARY_CROSSING',
] as const);

export const R088_REQUIRED_OUTPUTS = Object.freeze([
  'ORIGINAL_LOCAL_INPUT_PROVENANCE',
  'TIMEZONE_AUTHORITY_AND_VERSION',
  'RESOLVED_UTC_INSTANT',
  'SOLAR_TIME_METHOD_AND_PARAMETERS',
  'CORRECTED_TIMESTAMP_IF_ANY',
  'FOUR_PILLAR_DELTA',
  'DOWNSTREAM_RESEARCH_STATE_DELTA',
  'BOUNDARY_AND_CAUSE',
] as const);

export const R088_REJECTED_SHORTCUTS = Object.freeze([
  'CURRENT_OFFSET_FOR_HISTORICAL_DATE',
  'COUNTRY_ONLY_TIMEZONE_INFERENCE',
  'SOLAR_CORRECTION_BY_DEFAULT',
  'DOUBLE_APPLY_SOLAR_CORRECTION',
  'COLLAPSE_TIME_UNCERTAINTY_TO_EXACT_INSTANT',
  'ROBUSTNESS_CLAIM_BEFORE_EXECUTION',
] as const);

export const R088_AUTHORITY = Object.freeze({
  status: 'TEST_MANIFEST_READY_EXECUTION_PENDING' as const,
  executionPending: true,
  defaultSolarCorrectionAuthorized: false,
  historicalTimezoneGuessAuthorized: false,
  robustnessClaimAuthorized: false,
  productionAuthorityPromoted: false,
});
