export const R129_NONNUMERIC_STRENGTH_EXPLANATION_PRIMITIVES_VERSION =
  '0.1.0-research' as const;

export type R129PrimitiveFamily =
  | 'SEASON_MONTH'
  | 'ROOT_EVIDENCE'
  | 'ROOT_QUALITY'
  | 'SOURCE_SCOPED_ROOT'
  | 'HIDDEN_STEM'
  | 'SUPPORT_RELATION'
  | 'CHALLENGE_RELATION'
  | 'RELATION_CHAIN'
  | 'UNCERTAINTY_POLICY';

export type R129ExplanationRole =
  | 'CONTEXT'
  | 'SUPPORT'
  | 'CHALLENGE'
  | 'MODIFIER'
  | 'RELATION'
  | 'QUALIFIER'
  | 'UNCERTAINTY'
  | 'POLICY_BOUNDARY';

export type R129EvidenceState =
  | 'CROSS_SURFACE_STABLE_BOUNDED'
  | 'SUPPORTED_BOUNDED'
  | 'SOURCE_SCOPED'
  | 'METHODOLOGY_SCOPED'
  | 'DIVERGENT'
  | 'UNRESOLVED';

export type R129Portability =
  | 'CROSS_SURFACE_BOUNDED'
  | 'SOURCE_SCOPED'
  | 'METHODOLOGY_SCOPED'
  | 'POLICY_SENSITIVE'
  | 'UNRESOLVED';

export type R129Admission =
  | 'ADMIT_EXPLANATION_PRIMITIVE'
  | 'ADMIT_SOURCE_SCOPED_PRIMITIVE'
  | 'ADMIT_POLICY_BOUNDARY_PRIMITIVE'
  | 'HOLD_FOR_MORE_RESEARCH';

export type R129DependencyRisk =
  | 'LOW'
  | 'MATERIAL'
  | 'HIGH'
  | 'POLICY_BLOCKING';

export interface R129StrengthExplanationPrimitive {
  primitiveId: string;
  family: R129PrimitiveFamily;
  explanationRole: R129ExplanationRole;
  evidenceState: R129EvidenceState;
  portability: R129Portability;
  admission: R129Admission;
  sourceDependencyRisk: R129DependencyRisk;
  triggerFacts: readonly string[];
  sourceDerivedMeaning: string;
  semanticClaim: string;
  researchGloss: string;
  safeExplanationPattern: string;
  sourceRefs: readonly string[];
  conditions: readonly string[];
  qualifiers: readonly string[];
  exceptions: readonly string[];
  doesNotEstablish: readonly string[];
  mustNotBeCollapsedWith: readonly string[];
  authorizesExplanation: true;
  authorizesAggregation: false;
  authorizesNumericWeight: false;
  authorizesFinalStrength: false;
  authorizesInterpretationClaim: false;
  authorizesProductionCopy: false;
  prohibitedExtensions: readonly string[];
}

function primitive(
  input: Omit<
    R129StrengthExplanationPrimitive,
    | 'authorizesExplanation'
    | 'authorizesAggregation'
    | 'authorizesNumericWeight'
    | 'authorizesFinalStrength'
    | 'authorizesInterpretationClaim'
    | 'authorizesProductionCopy'
  >,
): R129StrengthExplanationPrimitive {
  return Object.freeze({
    ...input,
    authorizesExplanation: true,
    authorizesAggregation: false,
    authorizesNumericWeight: false,
    authorizesFinalStrength: false,
    authorizesInterpretationClaim: false,
    authorizesProductionCopy: false,
  });
}

const REF = Object.freeze({
  R012: 'src/research/general-natal-month-branch-priority-counterexamples.ts',
  R013: 'src/research/general-natal-tougan-tonggen-independence.ts',
  R014: 'src/research/general-natal-muku-root-treatment.ts',
  R015: 'src/research/general-natal-yuqi-temporal-variability-source-observation-authority.ts',
  R016: 'src/research/general-natal-changsheng-root-weight-binding-authority.ts',
  R017: 'src/research/general-natal-lu-diwang-root-strength.ts',
  R121: 'src/research/general-natal-root-strength-dependency-map.ts',
  R122: 'src/research/general-natal-season-root-interaction-counterexamples.ts',
  R123: 'src/research/general-natal-hidden-stem-qualitative-depth-evidence.ts',
  R124: 'src/research/general-natal-support-accumulation-saturation-audit.ts',
  R125: 'src/research/general-natal-peer-resource-support-discriminant-corpus.ts',
  R126: 'src/research/general-natal-control-drain-output-ordering-divergence.ts',
  R127: 'src/research/general-natal-strength-label-single-feature-perturbation.ts',
  R128: 'src/research/general-natal-cross-surface-borderline-strength-adjudication.ts',
  I13: 'src/research/i13-strength-evidence-pack.ts',
} as const);

export const R129_STRENGTH_EXPLANATION_PRIMITIVES:
  readonly R129StrengthExplanationPrimitive[] = Object.freeze([
  primitive({
    primitiveId: 'SEASON_CONTEXT_FAVORABLE',
    family: 'SEASON_MONTH',
    explanationRole: 'CONTEXT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['得時 / seasonally timely state is source-observed'],
    sourceDerivedMeaning: '得時 is a bounded seasonal context descriptor.',
    semanticClaim: 'The day master is in a seasonally favorable/timely context.',
    researchGloss: 'Season can favor the day master without settling whole-chart strength.',
    safeExplanationPattern: 'Seasonal context is favorable, while other root/support/opposition evidence still matters.',
    sourceRefs: [REF.R122, REF.R128],
    conditions: ['Use only when the selected source/methodology actually establishes the seasonal state.'],
    qualifiers: ['Context primitive only.'],
    exceptions: ['得時而不旺 counterexample exists.'],
    doesNotEstablish: ['旺', '強', 'final strength'],
    mustNotBeCollapsedWith: ['SEASON_ALONE_NOT_DECISIVE'],
    prohibitedExtensions: ['DE_SHI_EQUALS_WANG', 'FAVORABLE_SEASON_EQUALS_STRONG'],
  }),
  primitive({
    primitiveId: 'SEASON_CONTEXT_UNFAVORABLE',
    family: 'SEASON_MONTH',
    explanationRole: 'CONTEXT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['失時 / 休囚 seasonal context is source-observed'],
    sourceDerivedMeaning: '失時/休囚 describes an adverse seasonal context.',
    semanticClaim: 'The day master is seasonally disadvantaged in the bounded context.',
    researchGloss: 'Seasonal disadvantage is relevant but not conclusive.',
    safeExplanationPattern: 'Seasonal context is unfavorable, while rooted/supporting evidence may materially modify the reading.',
    sourceRefs: [REF.R122, REF.R128],
    conditions: ['Use only within the governed seasonal semantics.'],
    qualifiers: ['Context primitive only.'],
    exceptions: ['失時而不弱 counterexample exists.'],
    doesNotEstablish: ['弱', '衰', 'final strength'],
    mustNotBeCollapsedWith: ['SEASON_ALONE_NOT_DECISIVE'],
    prohibitedExtensions: ['SHI_SHI_EQUALS_RUO', 'UNFAVORABLE_SEASON_EQUALS_WEAK'],
  }),
  primitive({
    primitiveId: 'SEASON_ALONE_NOT_DECISIVE',
    family: 'SEASON_MONTH',
    explanationRole: 'QUALIFIER',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['得時而不旺 or 失時而不弱 source scaffold'],
    sourceDerivedMeaning: 'Seasonal timing does not exhaust the strength adjudication.',
    semanticClaim: 'Season by itself is insufficient to settle the strength label.',
    researchGloss: 'Root, support, opposition, and methodology-sensitive evidence can modify the seasonal reading.',
    safeExplanationPattern: 'Season is one important context, not a standalone final verdict.',
    sourceRefs: [REF.R122, REF.R127, REF.R128],
    conditions: ['Keep native 旺/衰/強/弱 vocabulary distinct.'],
    qualifiers: ['Cross-surface bounded principle with textual-dependency risk.'],
    exceptions: [],
    doesNotEstablish: ['how much other evidence is needed', 'a replacement classifier'],
    mustNotBeCollapsedWith: ['FINAL_STRENGTH'],
    prohibitedExtensions: ['SEASON_IS_IRRELEVANT', 'SEASON_ALONE_EQUALS_FINAL_STRENGTH'],
  }),
  primitive({
    primitiveId: 'MONTH_CONTEXT_IMPORTANT_BOUNDED',
    family: 'SEASON_MONTH',
    explanationRole: 'CONTEXT',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['month command/month branch is relevant in the selected scope'],
    sourceDerivedMeaning: '月為提綱 and month-root priority both preserve bounded month importance.',
    semanticClaim: 'The month context is an important strength-relevant context.',
    researchGloss: 'Month context deserves explicit explanation without becoming exclusive authority.',
    safeExplanationPattern: 'The month context is important, but it is interpreted together with the rest of the chart evidence.',
    sourceRefs: [REF.R012, REF.R128],
    conditions: ['Preserve general-chart versus Tonggen-scope differences.'],
    qualifiers: ['Importance is bounded, not absolute.'],
    exceptions: ['Yuanhai anti-rigidity warning.'],
    doesNotEstablish: ['global override', 'numeric multiplier'],
    mustNotBeCollapsedWith: ['MONTH_ROOT_PRIORITY_WITHIN_TONGGEN'],
    prohibitedExtensions: ['MONTH_IMPORTANCE_EQUALS_EXCLUSIVE_AUTHORITY'],
  }),
  primitive({
    primitiveId: 'MONTH_CONTEXT_NOT_EXCLUSIVE',
    family: 'SEASON_MONTH',
    explanationRole: 'QUALIFIER',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['month-command anti-rigidity evidence'],
    sourceDerivedMeaning: 'The month command must not be rigidly treated as the only chart authority.',
    semanticClaim: 'Month importance does not make all other evidence subordinate by default.',
    researchGloss: 'A safe explanation must leave room for roots, support, opposition, and source scope.',
    safeExplanationPattern: 'Month context matters, but it does not erase other structural evidence.',
    sourceRefs: [REF.R012, REF.R128],
    conditions: [],
    qualifiers: ['Anti-overgeneralization primitive.'],
    exceptions: [],
    doesNotEstablish: ['relative weighting among all other factors'],
    mustNotBeCollapsedWith: ['MONTH_CONTEXT_IMPORTANT_BOUNDED'],
    prohibitedExtensions: ['MONTH_BRANCH_ALWAYS_OVERRIDES_EVERYTHING'],
  }),
  primitive({
    primitiveId: 'MONTH_ROOT_PRIORITY_WITHIN_TONGGEN',
    family: 'SEASON_MONTH',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['multiple governed Tonggen/root observations including month branch'],
    sourceDerivedMeaning: '通根之中，尤以月令之支為最重.',
    semanticClaim: 'Within the selected Tonggen scope, the month-branch root receives special qualitative priority.',
    researchGloss: 'This is a scope-qualified root-position primitive, not a global chart ordering.',
    safeExplanationPattern: 'Among root evidence, the month-branch root may carry special importance in this source scope.',
    sourceRefs: [REF.R012, REF.R122, REF.R128],
    conditions: ['Only within the governed Tonggen comparison scope.'],
    qualifiers: ['Position-sensitive.'],
    exceptions: ['No exhaustive root-ordering algorithm is supplied.'],
    doesNotEstablish: ['global root rank', 'numeric multiplier', 'final strength'],
    mustNotBeCollapsedWith: ['MONTH_CONTEXT_IMPORTANT_BOUNDED'],
    prohibitedExtensions: ['MONTH_ROOT_EQUALS_GLOBAL_OVERRIDE', 'MOST_WEIGHTY_EQUALS_COEFFICIENT'],
  }),
  primitive({
    primitiveId: 'ROOT_SUPPORT_PRESENT_BOUNDED',
    family: 'ROOT_EVIDENCE',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'METHODOLOGY_SCOPED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['a governed positive root/Tonggen relation is observed'],
    sourceDerivedMeaning: 'Governed root/Tonggen evidence provides bounded support.',
    semanticClaim: 'There is source-governed rooted support in the bounded scope.',
    researchGloss: 'Positive root evidence is explainable even though the global root resolver remains incomplete.',
    safeExplanationPattern: 'A rooted support relation is present in the governed scope.',
    sourceRefs: [REF.R121, REF.R013, REF.R014, REF.R016, REF.R017],
    conditions: ['Consume only governed positive root observations.'],
    qualifiers: ['Positive-evidence primitive.'],
    exceptions: ['Unmatched cases are not automatically no-root.'],
    doesNotEstablish: ['complete 四柱有根', 'final 強弱', 'numeric weight'],
    mustNotBeCollapsedWith: ['ROOT_STATUS_UNRESOLVED_OUTSIDE_GOVERNED_SCOPE'],
    prohibitedExtensions: ['POSITIVE_ROOT_EQUALS_FINAL_STRENGTH'],
  }),
  primitive({
    primitiveId: 'ROOT_STATUS_UNRESOLVED_OUTSIDE_GOVERNED_SCOPE',
    family: 'ROOT_EVIDENCE',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'UNRESOLVED',
    portability: 'UNRESOLVED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'POLICY_BLOCKING',
    triggerFacts: ['no governed positive match and no governed exact exclusion settles the queried relation'],
    sourceDerivedMeaning: 'Absence of positive evidence is not global negative evidence.',
    semanticClaim: 'Root status remains unresolved outside the governed positive/exclusion scope.',
    researchGloss: 'This prevents silent conversion of unknown root status into 無根.',
    safeExplanationPattern: 'The current research scope does not settle this root relation.',
    sourceRefs: [REF.R121],
    conditions: [],
    qualifiers: ['Fail-closed uncertainty primitive.'],
    exceptions: ['Exact governed exclusions may settle a local negative relation.'],
    doesNotEstablish: ['無根', 'final strength'],
    mustNotBeCollapsedWith: ['ROOT_SUPPORT_PRESENT_BOUNDED'],
    prohibitedExtensions: ['NO_POSITIVE_MATCH_EQUALS_NO_ROOT'],
  }),
  primitive({
    primitiveId: 'TOUGAN_TONGGEN_DISTINCT',
    family: 'ROOT_EVIDENCE',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['透干 and/or 通根 relations are under explanation'],
    sourceDerivedMeaning: '透干 and 通根 are distinct directional relations.',
    semanticClaim: 'Visibility through the stem and rootedness through the branch must be explained separately.',
    researchGloss: 'A visible stem does not substitute for a root, and a root is not merely transparency.',
    safeExplanationPattern: 'Stem visibility and branch rootedness are different kinds of evidence.',
    sourceRefs: [REF.R013, REF.R121],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['relative numeric importance', 'final strength'],
    mustNotBeCollapsedWith: ['VISIBLE_SUPPORT_NOT_EQUIVALENT_ROOT'],
    prohibitedExtensions: ['TOUGAN_EQUALS_TONGGEN'],
  }),
  primitive({
    primitiveId: 'ROOT_QUALITY_MATTERS',
    family: 'ROOT_QUALITY',
    explanationRole: 'QUALIFIER',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['multiple governed root classes are present or compared'],
    sourceDerivedMeaning: 'Classical commentary distinguishes heavier and lighter root classes.',
    semanticClaim: 'Root evidence has qualitative classes; root presence alone does not exhaust its meaning.',
    researchGloss: 'Explain root class and scope rather than flattening every root into one unit.',
    safeExplanationPattern: 'The kind of root matters, not only whether a root exists.',
    sourceRefs: [REF.R124, REF.R128, REF.R017],
    conditions: ['Preserve source-specific root class scope.'],
    qualifiers: ['Qualitative only.'],
    exceptions: ['Yin/Earth gaps remain.'],
    doesNotEstablish: ['numeric root weight', 'universal total ordering'],
    mustNotBeCollapsedWith: ['HEAVY_ROOT_CLASS_BOUNDED', 'LIGHT_ROOT_CLASS_BOUNDED'],
    prohibitedExtensions: ['ROOT_CLASS_EQUALS_COEFFICIENT'],
  }),
  primitive({
    primitiveId: 'HEAVY_ROOT_CLASS_BOUNDED',
    family: 'ROOT_QUALITY',
    explanationRole: 'SUPPORT',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed 長生/祿/旺 heavy-root observation'],
    sourceDerivedMeaning: 'Selected source treats 長生/祿旺 as 根之重者 in bounded scope.',
    semanticClaim: 'The observed root belongs to a source-governed heavy-root class.',
    researchGloss: 'Heavy-root language is preserved without converting it into magnitude.',
    safeExplanationPattern: 'This root is treated as a heavier qualitative root class in the selected source scope.',
    sourceRefs: [REF.R016, REF.R017, REF.R128],
    conditions: ['Only where the specific upstream root authority is governed.'],
    qualifiers: [],
    exceptions: ['Yin Changsheng and some Lu scopes remain unresolved.'],
    doesNotEstablish: ['numeric strength', 'final label'],
    mustNotBeCollapsedWith: ['LIGHT_ROOT_CLASS_BOUNDED'],
    prohibitedExtensions: ['HEAVY_ROOT_EQUALS_FIXED_WEIGHT'],
  }),
  primitive({
    primitiveId: 'LIGHT_ROOT_CLASS_BOUNDED',
    family: 'ROOT_QUALITY',
    explanationRole: 'SUPPORT',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed 墓庫/餘氣 root observation'],
    sourceDerivedMeaning: 'Selected source treats 墓庫/餘氣 as 根之輕者 in bounded context.',
    semanticClaim: 'The observed root belongs to a source-governed lighter root class.',
    researchGloss: 'Light-root language remains qualitative and scope-limited.',
    safeExplanationPattern: 'This root is treated as a lighter qualitative root class in the selected source scope.',
    sourceRefs: [REF.R014, REF.R015, REF.R017, REF.R128],
    conditions: ['Only governed Muku/Yuqi cases.'],
    qualifiers: [],
    exceptions: ['Yuqi temporal variability can further qualify the reading.'],
    doesNotEstablish: ['numeric weight', 'weakness'],
    mustNotBeCollapsedWith: ['HEAVY_ROOT_CLASS_BOUNDED'],
    prohibitedExtensions: ['LIGHT_ROOT_EQUALS_WEAK'],
  }),
  primitive({
    primitiveId: 'VISIBLE_SUPPORT_NOT_EQUIVALENT_ROOT',
    family: 'ROOT_QUALITY',
    explanationRole: 'QUALIFIER',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['visible peer repetition and rooted support are being compared'],
    sourceDerivedMeaning: '干多不如根重 and exact rootless repeated-stem cases reject free substitution.',
    semanticClaim: 'Repeated visible support does not freely substitute for rooted support.',
    researchGloss: 'Count and rootedness are distinct explanatory dimensions.',
    safeExplanationPattern: 'Visible same-side support is meaningful, but it is not the same thing as having a root.',
    sourceRefs: [REF.R124, REF.R127, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['a universal root-to-peer exchange rate'],
    mustNotBeCollapsedWith: ['PEER_SUPPORT_PRESENT'],
    prohibitedExtensions: ['VISIBLE_COUNT_EQUALS_ROOT_SCORE'],
  }),
  primitive({
    primitiveId: 'ROOT_QUALITY_NOT_NUMERIC_WEIGHT',
    family: 'ROOT_QUALITY',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['qualitative root classes or peer/root comparisons are present'],
    sourceDerivedMeaning: '重/輕 and comparative wording do not supply coefficients.',
    semanticClaim: 'Qualitative root ordering cannot be converted into numeric weight from the reviewed evidence.',
    researchGloss: 'This blocks hidden scoring behind explanation language.',
    safeExplanationPattern: 'The source distinguishes root quality qualitatively; it does not provide a numeric conversion.',
    sourceRefs: [REF.R124, REF.R128, REF.R121],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['root score', 'exchange rate'],
    mustNotBeCollapsedWith: ['ROOT_QUALITY_MATTERS'],
    prohibitedExtensions: ['SOURCE_COMPARATIVE_LANGUAGE_EQUALS_COEFFICIENT'],
  }),
  primitive({
    primitiveId: 'YUQI_ROOT_EVIDENCE_BOUNDED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'SUPPORT',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed non-Earth Yuqi positive root relation'],
    sourceDerivedMeaning: '餘氣 can provide bounded root/Tonggen evidence.',
    semanticClaim: 'Yuqi contributes source-bounded rooted support.',
    researchGloss: 'Preserve Yuqi as a root class without assigning a fixed amount.',
    safeExplanationPattern: 'Yuqi provides a bounded rooted-support relation in this source scope.',
    sourceRefs: [REF.R015, REF.R121],
    conditions: ['Governed non-Earth scope only.'],
    qualifiers: ['Temporal context may matter.'],
    exceptions: ['Earth Yuqi remains unresolved.'],
    doesNotEstablish: ['fixed root weight', 'final strength'],
    mustNotBeCollapsedWith: ['YUQI_TEMPORAL_VARIABILITY'],
    prohibitedExtensions: ['YUQI_EQUALS_UNIVERSAL_WEIGHT'],
  }),
  primitive({
    primitiveId: 'YUQI_TEMPORAL_VARIABILITY',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'MODIFIER',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'POLICY_SENSITIVE',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'HIGH',
    triggerFacts: ['Yuqi relation in the governed temporal commentary context'],
    sourceDerivedMeaning: '清明後十二日 and 土旺之後 receive different qualitative Yuqi descriptions.',
    semanticClaim: 'Yuqi meaning can vary with temporal subcontext.',
    researchGloss: 'Time qualification is semantic, not a hidden multiplier.',
    safeExplanationPattern: 'The same Yuqi relation may be described differently across the source-defined temporal subperiods.',
    sourceRefs: [REF.R015, REF.R123, REF.R128],
    conditions: ['Selected commentary scope only.'],
    qualifiers: ['Temporal policy remains non-executable.'],
    exceptions: [],
    doesNotEstablish: ['numeric time weight', 'global Yuqi ranking'],
    mustNotBeCollapsedWith: ['YUQI_ROOT_EVIDENCE_BOUNDED'],
    prohibitedExtensions: ['TEMPORAL_VARIABILITY_EQUALS_NUMERIC_WEIGHT'],
  }),
  primitive({
    primitiveId: 'YUQI_TEMPORAL_WEIGHT_NOT_AUTHORIZED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'UNRESOLVED',
    portability: 'UNRESOLVED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'HIGH',
    triggerFacts: ['Yuqi temporal variability is present'],
    sourceDerivedMeaning: 'The source gives qualitative temporal variation, not an executable weight function.',
    semanticClaim: 'No temporal weighting function is authorized for Yuqi.',
    researchGloss: 'This boundary must accompany any Yuqi temporal explanation.',
    safeExplanationPattern: 'Temporal variation is observed, but the research does not assign a numeric or executable weight.',
    sourceRefs: [REF.R015, REF.R121],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['classifier', 'coefficient'],
    mustNotBeCollapsedWith: ['YUQI_TEMPORAL_VARIABILITY'],
    prohibitedExtensions: ['QINGMING_TIME_EQUALS_WEIGHT'],
  }),
  primitive({
    primitiveId: 'MUKU_YANG_ROOT_BOUNDED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'METHODOLOGY_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed non-Earth Yang stem at own element Muku'],
    sourceDerivedMeaning: 'Bounded Yang own-Muku positive root evidence is governed.',
    semanticClaim: 'The Yang stem has bounded Muku root support in the selected methodology.',
    researchGloss: 'Use only the governed Yang/non-Earth matrix.',
    safeExplanationPattern: 'This Muku relation is recognized as bounded root support under the selected source policy.',
    sourceRefs: [REF.R014, REF.R128],
    conditions: ['Non-Earth Yang stem at governed own Muku.'],
    qualifiers: [],
    exceptions: ['Do not copy to Yin or Earth.'],
    doesNotEstablish: ['universal Muku rule', 'final strength'],
    mustNotBeCollapsedWith: ['MUKU_YIN_POLICY_DIVERGENT', 'EARTH_MUKU_UNRESOLVED'],
    prohibitedExtensions: ['ANY_MUKU_ROOTS_ANY_STEM'],
  }),
  primitive({
    primitiveId: 'MUKU_YIN_POLICY_DIVERGENT',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'DIVERGENT',
    portability: 'POLICY_SENSITIVE',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'POLICY_BLOCKING',
    triggerFacts: ['Yin stem at own element Muku'],
    sourceDerivedMeaning: 'Reviewed source strata do not yield one source-neutral Yin-Muku predicate.',
    semanticClaim: 'Yin Muku treatment is methodology/source-policy sensitive.',
    researchGloss: 'Expose the policy fork instead of selecting a default.',
    safeExplanationPattern: 'This Yin-Muku relation remains dependent on the selected source policy.',
    sourceRefs: [REF.R014, REF.R128],
    conditions: [],
    qualifiers: ['Blocking for universal root explanation.'],
    exceptions: [],
    doesNotEstablish: ['positive root', 'negative root'],
    mustNotBeCollapsedWith: ['MUKU_YANG_ROOT_BOUNDED'],
    prohibitedExtensions: ['AUTO_SELECT_YIN_MUKU_WINNER'],
  }),
  primitive({
    primitiveId: 'EARTH_MUKU_UNRESOLVED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'UNRESOLVED',
    portability: 'UNRESOLVED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'POLICY_BLOCKING',
    triggerFacts: ['Earth stem queried for Muku treatment'],
    sourceDerivedMeaning: 'A universal Earth Muku mapping is not resolved.',
    semanticClaim: 'Earth Muku root status remains unresolved in the governed research.',
    researchGloss: 'Do not invent a fifth Earth Muku.',
    safeExplanationPattern: 'The current research does not settle a universal Earth-Muku root rule.',
    sourceRefs: [REF.R014, REF.R121],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['Earth root mapping'],
    mustNotBeCollapsedWith: ['MUKU_YANG_ROOT_BOUNDED'],
    prohibitedExtensions: ['INVENT_EARTH_FIFTH_MUKU'],
  }),
  primitive({
    primitiveId: 'YANG_CHANGSHENG_ROOT_BOUNDED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'METHODOLOGY_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed Yang day master at Changsheng relation'],
    sourceDerivedMeaning: 'Yang Changsheng is admitted to the bounded heavy-root clause.',
    semanticClaim: 'The Yang Changsheng relation provides bounded root support.',
    researchGloss: 'Use the Yang-specific authority chain only.',
    safeExplanationPattern: 'This Yang Changsheng relation is recognized as bounded root support.',
    sourceRefs: [REF.R016, REF.R128],
    conditions: ['Canonical Yang day master and governed Changsheng mapping.'],
    qualifiers: [],
    exceptions: ['Yin Changsheng is not silently included.'],
    doesNotEstablish: ['Yin rule', 'final strength'],
    mustNotBeCollapsedWith: ['YIN_CHANGSHENG_POLICY_DIVERGENT'],
    prohibitedExtensions: ['YANG_CHANGSHENG_EQUALS_YIN_CHANGSHENG'],
  }),
  primitive({
    primitiveId: 'YIN_CHANGSHENG_POLICY_DIVERGENT',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'DIVERGENT',
    portability: 'POLICY_SENSITIVE',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'POLICY_BLOCKING',
    triggerFacts: ['Yin day master at Changsheng relation'],
    sourceDerivedMeaning: 'Yin Changsheng is explicitly excluded from the selected heavy-root clause while other reviewed wording remains broader.',
    semanticClaim: 'Yin Changsheng requires source/methodology selection.',
    researchGloss: 'Do not collapse the heavy-root exception into either root or no-root globally.',
    safeExplanationPattern: 'This Yin Changsheng relation remains source-policy sensitive.',
    sourceRefs: [REF.R016, REF.R121, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: ['明根 semantics may remain without heavy-root classification.'],
    doesNotEstablish: ['heavy root', 'light root', 'no root'],
    mustNotBeCollapsedWith: ['YANG_CHANGSHENG_ROOT_BOUNDED'],
    prohibitedExtensions: ['DEFAULT_YIN_CHANGSHENG_HEAVY_ROOT'],
  }),
  primitive({
    primitiveId: 'LU_ROOT_BOUNDED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'METHODOLOGY_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed Lu positive root relation'],
    sourceDerivedMeaning: '祿 is preserved as a bounded heavy-root class in governed scope.',
    semanticClaim: 'A governed Lu relation contributes bounded heavy-root evidence.',
    researchGloss: 'Do not bridge every 臨官 cell to Lu automatically.',
    safeExplanationPattern: 'This governed Lu relation is treated as a heavier root class.',
    sourceRefs: [REF.R017, REF.R121],
    conditions: ['Only governed Lu scope.'],
    qualifiers: [],
    exceptions: ['Yin/Earth Lu gaps remain.'],
    doesNotEstablish: ['universal Lu mapping'],
    mustNotBeCollapsedWith: ['TWELVE_GROWTH_STAGE_NOT_AUTOMATIC_ROOT_CLASS'],
    prohibitedExtensions: ['LINGUAN_EQUALS_LU_EXECUTABLE_BRIDGE'],
  }),
  primitive({
    primitiveId: 'WANG_ROOT_BOUNDED',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'METHODOLOGY_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed source-native 旺 heavy-root relation'],
    sourceDerivedMeaning: '旺 is preserved as a bounded heavy-root semantic class.',
    semanticClaim: 'A governed 旺 root relation contributes bounded heavy-root evidence.',
    researchGloss: 'Do not equate all 帝旺 stage cells with this root class.',
    safeExplanationPattern: 'This governed 旺 relation is treated as a heavier root class.',
    sourceRefs: [REF.R017, REF.R121],
    conditions: ['Only governed source-native 旺 matcher.'],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['帝旺-to-旺 executable equivalence'],
    mustNotBeCollapsedWith: ['TWELVE_GROWTH_STAGE_NOT_AUTOMATIC_ROOT_CLASS'],
    prohibitedExtensions: ['DIWANG_EQUALS_WANG_EXECUTABLE_BRIDGE'],
  }),
  primitive({
    primitiveId: 'TWELVE_GROWTH_STAGE_NOT_AUTOMATIC_ROOT_CLASS',
    family: 'SOURCE_SCOPED_ROOT',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['Twelve-Growth stage label and root-class label are being bridged'],
    sourceDerivedMeaning: '臨官/帝旺 stage authority and 祿/旺 root semantics have separate source authorities.',
    semanticClaim: 'Lexical association does not create an executable root-class bridge.',
    researchGloss: 'Keep stage vocabulary and root semantics distinct unless separately authorized.',
    safeExplanationPattern: 'The growth-stage label and the root-class label are related terms but not automatically interchangeable.',
    sourceRefs: [REF.R017],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['stage-to-root conversion'],
    mustNotBeCollapsedWith: ['LU_ROOT_BOUNDED', 'WANG_ROOT_BOUNDED'],
    prohibitedExtensions: ['LINGUAN_EQUALS_LU', 'DIWANG_EQUALS_WANG'],
  }),
  primitive({
    primitiveId: 'HIDDEN_STEM_MEMBERSHIP_NOT_DEPTH',
    family: 'HIDDEN_STEM',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['hidden-stem membership array is used in explanation'],
    sourceDerivedMeaning: 'Canonical hidden-stem array order is storage order, not semantic depth.',
    semanticClaim: 'Membership storage must not be read as 本/中/餘 depth.',
    researchGloss: 'This is a negative-control primitive against accidental semantic depth from array position.',
    safeExplanationPattern: 'Hidden-stem membership order by itself does not express qualitative depth.',
    sourceRefs: [REF.R123, REF.R127],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['hidden role rank'],
    mustNotBeCollapsedWith: ['HIDDEN_TRANSPARENCY_CAN_CHANGE_ROLE'],
    prohibitedExtensions: ['ARRAY_POSITION_EQUALS_HIDDEN_DEPTH'],
  }),
  primitive({
    primitiveId: 'HIDDEN_TRANSPARENCY_CAN_CHANGE_ROLE',
    family: 'HIDDEN_STEM',
    explanationRole: 'MODIFIER',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['exact governed hidden-stem transparency condition'],
    sourceDerivedMeaning: 'In the selected 寅 example, transparency changes which hidden stem may 作主.',
    semanticClaim: 'Transparency can alter a hidden stem qualitative role in bounded source context.',
    researchGloss: 'Role sensitivity is explainable without generalizing a universal selector.',
    safeExplanationPattern: 'Transparency can change the active qualitative role of a hidden stem in this source example.',
    sourceRefs: [REF.R123, REF.R127],
    conditions: ['Exact source-bounded role condition only.'],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['universal hidden-depth algorithm', 'strength label'],
    mustNotBeCollapsedWith: ['HIDDEN_STEM_MEMBERSHIP_NOT_DEPTH'],
    prohibitedExtensions: ['TRANSPARENCY_ROLE_EQUALS_STRENGTH_BONUS'],
  }),
  primitive({
    primitiveId: 'HIDDEN_ROLE_NOT_STRENGTH_LABEL',
    family: 'HIDDEN_STEM',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['本主/作主 or other qualitative hidden role is observed'],
    sourceDerivedMeaning: 'Qualitative hidden-stem role does not itself produce whole-chart strength.',
    semanticClaim: 'Hidden-role language is not a final strength label.',
    researchGloss: 'Prevents role semantics from becoming a hidden classifier.',
    safeExplanationPattern: 'A hidden-stem role is observed, but it does not by itself settle day-master strength.',
    sourceRefs: [REF.R123, REF.R127],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['強', '弱', '旺', '衰'],
    mustNotBeCollapsedWith: ['FINAL_STRENGTH'],
    prohibitedExtensions: ['ZUO_ZHU_EQUALS_STRONGER'],
  }),
  primitive({
    primitiveId: 'PEER_SUPPORT_PRESENT',
    family: 'SUPPORT_RELATION',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed 比肩/比劫 same-kind support relation'],
    sourceDerivedMeaning: 'Peer/same-kind support can assist the day master in bounded strength contexts.',
    semanticClaim: 'Peer support is present as one support-family relation.',
    researchGloss: 'Peer support should be explained as peer support, not a generic point.',
    safeExplanationPattern: 'Same-kind peer support is present.',
    sourceRefs: [REF.R121, REF.R124, REF.R125, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: ['Visible peers without root may still leave exact examples weak.'],
    doesNotEstablish: ['黨眾 settlement', 'strong label'],
    mustNotBeCollapsedWith: ['RESOURCE_SUPPORT_PRESENT', 'ROOT_SUPPORT_PRESENT_BOUNDED'],
    prohibitedExtensions: ['PEER_PRESENT_EQUALS_STRONG'],
  }),
  primitive({
    primitiveId: 'RESOURCE_SUPPORT_PRESENT',
    family: 'SUPPORT_RELATION',
    explanationRole: 'SUPPORT',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['governed 印綬/resource relation in bounded support context'],
    sourceDerivedMeaning: 'Resource can support/generate the day master in bounded contexts.',
    semanticClaim: 'Resource support is present as a distinct support-family relation.',
    researchGloss: 'Resource must retain its generation/dependency semantics.',
    safeExplanationPattern: 'Resource support is present and works through a different mechanism from peer support.',
    sourceRefs: [REF.R125, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: ['Resource can be disrupted or excessive in other source-local contexts.'],
    doesNotEstablish: ['same effect as peer', 'strong label'],
    mustNotBeCollapsedWith: ['PEER_SUPPORT_PRESENT'],
    prohibitedExtensions: ['ONE_RESOURCE_EQUALS_ONE_PEER'],
  }),
  primitive({
    primitiveId: 'PEER_RESOURCE_MECHANISM_DISTINCT',
    family: 'SUPPORT_RELATION',
    explanationRole: 'QUALIFIER',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['peer and resource support are both present or compared'],
    sourceDerivedMeaning: 'Peer/same-kind assistance and resource/generation are not mechanism-equivalent.',
    semanticClaim: 'Peer and resource support must remain semantically distinct.',
    researchGloss: 'Broad support overlap does not authorize substitution.',
    safeExplanationPattern: 'Both relations can support the day master, but they do so through different mechanisms.',
    sourceRefs: [REF.R125, REF.R127, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['one-to-one substitution', 'common scalar'],
    mustNotBeCollapsedWith: ['GENERIC_SUPPORT_UNIT'],
    prohibitedExtensions: ['PEER_RESOURCE_SWAP_PRESERVES_EFFECT'],
  }),
  primitive({
    primitiveId: 'SUPPORT_ACCUMULATION_QUALITATIVE',
    family: 'SUPPORT_RELATION',
    explanationRole: 'MODIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['multiple support constituents coexist in a bounded source context'],
    sourceDerivedMeaning: 'Repeated/mixed support can be qualitatively meaningful.',
    semanticClaim: 'Support accumulation can matter qualitatively.',
    researchGloss: 'Acknowledge accumulation without turning count into score.',
    safeExplanationPattern: 'Several support relations coexist and are qualitatively relevant.',
    sourceRefs: [REF.R124, REF.R125],
    conditions: ['No universal constituent completeness or threshold assumed.'],
    qualifiers: [],
    exceptions: ['Support quality and rooting remain material.'],
    doesNotEstablish: ['support score', 'threshold', 'strong label'],
    mustNotBeCollapsedWith: ['SUPPORT_THRESHOLD_NOT_ESTABLISHED'],
    prohibitedExtensions: ['SUPPORT_COUNT_EQUALS_STRENGTH'],
  }),
  primitive({
    primitiveId: 'SUPPORT_THRESHOLD_NOT_ESTABLISHED',
    family: 'SUPPORT_RELATION',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'UNRESOLVED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['support accumulation is being interpreted'],
    sourceDerivedMeaning: 'Reviewed sources do not supply one universal count/saturation threshold.',
    semanticClaim: 'No universal support-count threshold is established.',
    researchGloss: 'This primitive must accompany any accumulation explanation.',
    safeExplanationPattern: 'Support accumulation is meaningful, but no fixed count threshold is established.',
    sourceRefs: [REF.R124, REF.R121],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['N supports => strong', 'saturation point'],
    mustNotBeCollapsedWith: ['SUPPORT_ACCUMULATION_QUALITATIVE'],
    prohibitedExtensions: ['INVENT_SUPPORT_COUNT_THRESHOLD'],
  }),
  primitive({
    primitiveId: 'SUPPORT_FAMILY_PRESENCE_NOT_FINAL_STRENGTH',
    family: 'SUPPORT_RELATION',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['peer/resource/root support family is present'],
    sourceDerivedMeaning: 'Support-family presence is constituent evidence, not a final label.',
    semanticClaim: 'Presence of support does not by itself settle 強弱/旺衰.',
    researchGloss: 'Prevents constituent evidence from becoming a classifier shortcut.',
    safeExplanationPattern: 'Support is present, but the overall strength conclusion requires additional adjudication.',
    sourceRefs: [REF.R121, REF.R124, REF.R125, REF.R127],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['強', '不弱', '旺'],
    mustNotBeCollapsedWith: ['PEER_SUPPORT_PRESENT', 'RESOURCE_SUPPORT_PRESENT', 'ROOT_SUPPORT_PRESENT_BOUNDED'],
    prohibitedExtensions: ['SUPPORT_PRESENT_EQUALS_STRONG'],
  }),
  primitive({
    primitiveId: 'OUTPUT_RELATION_PRESENT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'RELATION',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['食神/傷官 output relation is present'],
    sourceDerivedMeaning: 'Output is a distinct relation family that can leak, generate, or control in bounded contexts.',
    semanticClaim: 'An output relation is present and must be interpreted relationally.',
    researchGloss: 'Do not encode output as a universal negative unit.',
    safeExplanationPattern: 'An output relation is present; its effect depends on the surrounding relation chain.',
    sourceRefs: [REF.R126, REF.R128, REF.I13],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['fixed adverse effect', 'numeric penalty'],
    mustNotBeCollapsedWith: ['WEALTH_RELATION_PRESENT', 'CONTROL_RELATION_PRESENT'],
    prohibitedExtensions: ['OUTPUT_EQUALS_MINUS_ONE'],
  }),
  primitive({
    primitiveId: 'OUTPUT_CAN_FUNCTION_AS_LEAKAGE',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'RELATION',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['食傷 described as 洩氣 in bounded source context'],
    sourceDerivedMeaning: 'Output can function as leakage/release of day-master qi.',
    semanticClaim: 'Output may act as leakage in the selected context.',
    researchGloss: 'Leakage is a mechanism, not a fixed polarity.',
    safeExplanationPattern: 'The output relation functions as leakage in this bounded context.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: ['The same actor can also generate wealth or control kill.'],
    doesNotEstablish: ['always adverse', 'fixed magnitude'],
    mustNotBeCollapsedWith: ['OUTPUT_CAN_BE_USEFUL_OVER_SUPPORTED_CONTEXT'],
    prohibitedExtensions: ['LEAKAGE_EQUALS_NEGATIVE_POINT'],
  }),
  primitive({
    primitiveId: 'OUTPUT_CAN_BE_USEFUL_OVER_SUPPORTED_CONTEXT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'MODIFIER',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['身印兩旺 and source-stated 食傷洩氣'],
    sourceDerivedMeaning: 'In an over-supported bounded context, output leakage can serve a useful regulating role.',
    semanticClaim: 'Output can be useful in an over-supported source-local context.',
    researchGloss: 'This blocks universal adverse polarity for output.',
    safeExplanationPattern: 'In this bounded context, output helps release excess support rather than acting as a simple adverse unit.',
    sourceRefs: [REF.R126, REF.R128],
    conditions: ['身印兩旺 source context.'],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['output always beneficial', 'post-leakage final label'],
    mustNotBeCollapsedWith: ['OUTPUT_RELATION_PRESENT'],
    prohibitedExtensions: ['OUTPUT_ALWAYS_GOOD'],
  }),
  primitive({
    primitiveId: 'WEALTH_RELATION_PRESENT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'RELATION',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['財 relation is present'],
    sourceDerivedMeaning: 'Wealth is a distinct relation family with capacity and generative effects.',
    semanticClaim: 'A wealth relation is present and must be interpreted with context.',
    researchGloss: 'Do not reduce wealth to one drain coefficient.',
    safeExplanationPattern: 'A wealth relation is present; its meaning depends on body capacity and downstream relations.',
    sourceRefs: [REF.R126, REF.R128, REF.I13],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['fixed drain', 'numeric penalty'],
    mustNotBeCollapsedWith: ['OUTPUT_RELATION_PRESENT', 'CONTROL_RELATION_PRESENT'],
    prohibitedExtensions: ['WEALTH_EQUALS_FIXED_DRAIN'],
  }),
  primitive({
    primitiveId: 'WEALTH_CAPACITY_DEPENDENT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['財多身弱 / 財旺身衰 or analogous governed capacity context'],
    sourceDerivedMeaning: 'Wealth effect is evaluated relative to day-master capacity in bounded sources.',
    semanticClaim: 'Wealth cannot be explained independently of the day master capacity context.',
    researchGloss: 'Capacity-sensitive explanation replaces fixed drain language.',
    safeExplanationPattern: 'The wealth relation is interpreted together with the day master capacity to carry it.',
    sourceRefs: [REF.R126, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['numeric carrying capacity', 'automatic weak label outside exact source cases'],
    mustNotBeCollapsedWith: ['WEALTH_RELATION_PRESENT'],
    prohibitedExtensions: ['WEALTH_PRESENCE_EQUALS_WEAK'],
  }),
  primitive({
    primitiveId: 'WEALTH_CAN_FEED_CONTROL',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'RELATION',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['source-local 財生官 or 財生煞 chain'],
    sourceDerivedMeaning: 'Wealth can generate an officer/kill control actor.',
    semanticClaim: 'Wealth may function as an intermediate generator of control.',
    researchGloss: 'This blocks independent penalty counting for wealth plus control in the same chain.',
    safeExplanationPattern: 'The wealth relation feeds a control relation in this bounded chain.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['global chain order', 'double penalty'],
    mustNotBeCollapsedWith: ['WEALTH_CAPACITY_DEPENDENT'],
    prohibitedExtensions: ['WEALTH_PLUS_CONTROL_EQUALS_TWO_NEGATIVE_POINTS'],
  }),
  primitive({
    primitiveId: 'CONTROL_RELATION_PRESENT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'RELATION',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['官/殺 control relation is present'],
    sourceDerivedMeaning: 'Officer/kill is a control relation, distinct from output and wealth.',
    semanticClaim: 'A control relation is present and must be interpreted with body/control context.',
    researchGloss: 'Control is not a fixed negative point.',
    safeExplanationPattern: 'A control relation is present; whether it is excessive, regulated, or useful depends on context.',
    sourceRefs: [REF.R126, REF.R128, REF.I13],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['always adverse', 'fixed strength loss'],
    mustNotBeCollapsedWith: ['OUTPUT_RELATION_PRESENT', 'WEALTH_RELATION_PRESENT'],
    prohibitedExtensions: ['CONTROL_EQUALS_MINUS_ONE'],
  }),
  primitive({
    primitiveId: 'CONTROL_EFFECT_CONTEXT_DEPENDENT',
    family: 'CHALLENGE_RELATION',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['body state/control state/mediator modifies 官殺 relation'],
    sourceDerivedMeaning: '身強七煞逢制 and weak-body mediation examples make control context-dependent.',
    semanticClaim: 'Control effect depends on body condition and whether the control actor is itself regulated or mediated.',
    researchGloss: 'Presence alone does not settle the control outcome.',
    safeExplanationPattern: 'The control relation is interpreted together with body condition and any regulating relation.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['fixed control polarity'],
    mustNotBeCollapsedWith: ['CONTROL_RELATION_PRESENT'],
    prohibitedExtensions: ['KILL_PRESENT_EQUALS_FAILURE'],
  }),
  primitive({
    primitiveId: 'RELATION_CHAIN_PRESENT',
    family: 'RELATION_CHAIN',
    explanationRole: 'RELATION',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['two or more source-local relations form a causal/control/rescue chain'],
    sourceDerivedMeaning: 'Source-local relation sequences can change actor function and settlement.',
    semanticClaim: 'The actors participate in a local relation chain rather than isolated independent units.',
    researchGloss: 'Chain structure must be explainable before any aggregate interpretation.',
    safeExplanationPattern: 'These relations form a local chain, so the actors should not be read as isolated independent effects.',
    sourceRefs: [REF.R126, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['global execution order', 'numeric chain score'],
    mustNotBeCollapsedWith: ['LOCAL_CHAIN_ORDER_MATTERS'],
    prohibitedExtensions: ['CHAIN_MEMBERS_EQUAL_INDEPENDENT_POINTS'],
  }),
  primitive({
    primitiveId: 'SAME_ACTOR_MULTIPLE_ROLES',
    family: 'RELATION_CHAIN',
    explanationRole: 'QUALIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['same actor participates in multiple source-local relations'],
    sourceDerivedMeaning: 'Food can leak and control kill; wealth can burden, generate control, or rescue a local chain.',
    semanticClaim: 'A Ten-God actor may have multiple local semantic roles.',
    researchGloss: 'Ten-God identity does not imply one fixed strength polarity.',
    safeExplanationPattern: 'The same actor can play more than one role depending on the relation chain.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['one universal actor polarity'],
    mustNotBeCollapsedWith: ['TEN_GOD_FIXED_POLARITY'],
    prohibitedExtensions: ['SAME_ACTOR_CAN_ONLY_HAVE_ONE_ROLE'],
  }),
  primitive({
    primitiveId: 'OUTPUT_GENERATES_WEALTH',
    family: 'RELATION_CHAIN',
    explanationRole: 'RELATION',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['食神生財 or 傷官生財 source-local chain'],
    sourceDerivedMeaning: 'Output can generate wealth.',
    semanticClaim: 'Output and wealth may belong to one causal path.',
    researchGloss: 'Do not double-count the chain as isolated challenging units.',
    safeExplanationPattern: 'The output relation feeds the wealth relation in this bounded chain.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['two independent penalties'],
    mustNotBeCollapsedWith: ['OUTPUT_RELATION_PRESENT', 'WEALTH_RELATION_PRESENT'],
    prohibitedExtensions: ['OUTPUT_PLUS_WEALTH_EQUALS_MINUS_TWO'],
  }),
  primitive({
    primitiveId: 'OUTPUT_CONTROLS_KILL',
    family: 'RELATION_CHAIN',
    explanationRole: 'RELATION',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['食神制煞 source-local chain'],
    sourceDerivedMeaning: 'Output can function as a controller of kill.',
    semanticClaim: 'An output actor may regulate a control actor.',
    researchGloss: 'Output is not merely leakage.',
    safeExplanationPattern: 'The output relation also controls the kill relation in this bounded chain.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['output has no leakage role', 'final strength'],
    mustNotBeCollapsedWith: ['OUTPUT_CAN_FUNCTION_AS_LEAKAGE'],
    prohibitedExtensions: ['FOOD_CONTROLS_KILL_EQUALS_NO_OUTPUT_COST'],
  }),
  primitive({
    primitiveId: 'WEALTH_GENERATES_CONTROL',
    family: 'RELATION_CHAIN',
    explanationRole: 'RELATION',
    evidenceState: 'SOURCE_SCOPED',
    portability: 'SOURCE_SCOPED',
    admission: 'ADMIT_SOURCE_SCOPED_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['財生官 / 財生煞 source-local chain'],
    sourceDerivedMeaning: 'Wealth can generate officer/kill.',
    semanticClaim: 'Wealth may feed a control actor in the local chain.',
    researchGloss: 'Causal dependency matters for explanation and double-counting risk.',
    safeExplanationPattern: 'The wealth relation feeds the control relation in this bounded chain.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['independent wealth and control penalties'],
    mustNotBeCollapsedWith: ['WEALTH_CAN_FEED_CONTROL'],
    prohibitedExtensions: ['WEALTH_CONTROL_DOUBLE_COUNT'],
  }),
  primitive({
    primitiveId: 'LOCAL_CHAIN_ORDER_MATTERS',
    family: 'RELATION_CHAIN',
    explanationRole: 'MODIFIER',
    evidenceState: 'SUPPORTED_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_EXPLANATION_PRIMITIVE',
    sourceDependencyRisk: 'MATERIAL',
    triggerFacts: ['source explicitly preserves generative/control/rescue/contamination order'],
    sourceDerivedMeaning: 'The order of local source relations can change the interpreted role/outcome.',
    semanticClaim: 'Local relation ordering is semantically material.',
    researchGloss: 'Explain the causal/rescue order without globalizing it.',
    safeExplanationPattern: 'The order of these local relations matters to how the chain is understood.',
    sourceRefs: [REF.R126, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['global precedence algorithm'],
    mustNotBeCollapsedWith: ['LOCAL_ORDER_NOT_GLOBAL_PRECEDENCE'],
    prohibitedExtensions: ['SOURCE_SENTENCE_ORDER_EQUALS_RUNTIME_PRECEDENCE'],
  }),
  primitive({
    primitiveId: 'LOCAL_ORDER_NOT_GLOBAL_PRECEDENCE',
    family: 'RELATION_CHAIN',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['one or more local relation chains are observed'],
    sourceDerivedMeaning: 'Multiple local orderings exist; no universal actor-type precedence is established.',
    semanticClaim: 'Local relation order must not be promoted into global execution precedence.',
    researchGloss: 'This keeps relation explanation non-executive.',
    safeExplanationPattern: 'This chain has a local order, but the research does not establish one universal order for all charts.',
    sourceRefs: [REF.R126],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['global ordering'],
    mustNotBeCollapsedWith: ['LOCAL_CHAIN_ORDER_MATTERS'],
    prohibitedExtensions: ['LOCAL_ORDER_EQUALS_GLOBAL_PRECEDENCE'],
  }),
  primitive({
    primitiveId: 'ONE_FEATURE_CHANGE_NOT_OPPOSITE_LABEL',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['single-feature perturbation is discussed'],
    sourceDerivedMeaning: 'R127 found semantic sensitivity but no established exact opposite-label pair.',
    semanticClaim: 'Changing one feature does not prove the opposite strength label.',
    researchGloss: 'Feature sensitivity is not a label-transition function.',
    safeExplanationPattern: 'This feature changes the evidence, but the research does not infer an opposite final label from that change alone.',
    sourceRefs: [REF.R127],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['counterfactual label'],
    mustNotBeCollapsedWith: ['FINAL_STRENGTH'],
    prohibitedExtensions: ['ONE_FEATURE_CHANGED_EQUALS_OPPOSITE_LABEL'],
  }),
  primitive({
    primitiveId: 'SOURCE_LABEL_NOT_COUNTERFACTUAL_LABEL',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['one side of a perturbation has a direct source label and the other does not'],
    sourceDerivedMeaning: 'A direct source label cannot be inherited by an unsupported synthetic counterfactual.',
    semanticClaim: 'Source labels remain attached to source-observed states.',
    researchGloss: 'Prevents synthetic completion of missing labels.',
    safeExplanationPattern: 'The source labels the observed state, while the counterfactual state remains unlabeled.',
    sourceRefs: [REF.R127],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['synthetic label'],
    mustNotBeCollapsedWith: ['SOURCE_NATIVE_LABEL'],
    prohibitedExtensions: ['SOURCE_LABEL_INHERITS_TO_COUNTERFACTUAL'],
  }),
  primitive({
    primitiveId: 'SOURCE_COUNT_NOT_VOTE_COUNT',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'HIGH',
    triggerFacts: ['multiple source surfaces repeat or resemble the same proposition'],
    sourceDerivedMeaning: 'R128 preserves textual-dependency risk and rejects source-count voting.',
    semanticClaim: 'Raw source count is not an independent vote count.',
    researchGloss: 'Dependency metadata must survive explanation synthesis.',
    safeExplanationPattern: 'Several source surfaces may share this wording, but their independence is not assumed.',
    sourceRefs: [REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['majority truth', 'confidence multiplier'],
    mustNotBeCollapsedWith: ['CROSS_SURFACE_AGREEMENT'],
    prohibitedExtensions: ['XU_PLUS_REN_EQUALS_TWO_VOTES'],
  }),
  primitive({
    primitiveId: 'SOURCE_POLICY_DIFFERENCE_NOT_DEFAULT_CHOICE',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'DIVERGENT',
    portability: 'POLICY_SENSITIVE',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'POLICY_BLOCKING',
    triggerFacts: ['R128 source-policy divergence is present'],
    sourceDerivedMeaning: 'Source-policy divergence does not select a winning source.',
    semanticClaim: 'A policy fork remains a policy fork until methodology governance selects a path.',
    researchGloss: 'Explaining disagreement is permitted; resolving it by default is not.',
    safeExplanationPattern: 'The reviewed source policies differ here, so the research keeps the treatment unresolved rather than choosing a default.',
    sourceRefs: [REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['canonical winner'],
    mustNotBeCollapsedWith: ['MUKU_YIN_POLICY_DIVERGENT', 'YIN_CHANGSHENG_POLICY_DIVERGENT'],
    prohibitedExtensions: ['SOURCE_DIVERGENCE_EQUALS_ENGINE_CHOOSE_ONE'],
  }),
  primitive({
    primitiveId: 'CHALLENGING_RELATION_NOT_NEGATIVE_POINT',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'UNCERTAINTY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['I13 challenging relation is being explained'],
    sourceDerivedMeaning: 'Output, wealth, and officer share a broad collector direction but have distinct mechanisms.',
    semanticClaim: 'A challenging relation is not an equal negative point.',
    researchGloss: 'Broad evidence direction must remain non-scalar.',
    safeExplanationPattern: 'This relation is strength-relevant, but the research does not assign it a fixed negative value.',
    sourceRefs: [REF.R126, REF.R128, REF.I13],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['-1', 'equal adverse unit'],
    mustNotBeCollapsedWith: ['OUTPUT_RELATION_PRESENT', 'WEALTH_RELATION_PRESENT', 'CONTROL_RELATION_PRESENT'],
    prohibitedExtensions: ['CHALLENGING_EQUALS_NEGATIVE_POINT'],
  }),
  primitive({
    primitiveId: 'EXPLANATION_PRIMITIVE_NOT_CLASSIFIER_RULE',
    family: 'UNCERTAINTY_POLICY',
    explanationRole: 'POLICY_BOUNDARY',
    evidenceState: 'CROSS_SURFACE_STABLE_BOUNDED',
    portability: 'CROSS_SURFACE_BOUNDED',
    admission: 'ADMIT_POLICY_BOUNDARY_PRIMITIVE',
    sourceDependencyRisk: 'LOW',
    triggerFacts: ['any R129 primitive is consumed'],
    sourceDerivedMeaning: 'R129 inventories explanation semantics only.',
    semanticClaim: 'Primitive presence must not be interpreted as a classifier rule.',
    researchGloss: 'This is the top-level R129 non-executive boundary.',
    safeExplanationPattern: 'The primitive explains one aspect of the evidence; it does not by itself produce a strength label.',
    sourceRefs: [REF.R121, REF.R127, REF.R128],
    conditions: [],
    qualifiers: [],
    exceptions: [],
    doesNotEstablish: ['if/then final classification', 'aggregate score'],
    mustNotBeCollapsedWith: ['FINAL_STRENGTH'],
    prohibitedExtensions: ['PRIMITIVE_PRESENCE_EQUALS_FINAL_LABEL'],
  }),
]);

export type R129PrimitiveRelationType =
  | 'QUALIFIES'
  | 'CONTRASTS_WITH'
  | 'CAN_COEXIST_WITH'
  | 'DOES_NOT_IMPLY'
  | 'SCOPE_LIMITS'
  | 'POLICY_FORKS';

export interface R129PrimitiveRelation {
  fromPrimitiveId: string;
  relation: R129PrimitiveRelationType;
  toPrimitiveId: string;
  researchMeaning: string;
}

export const R129_PRIMITIVE_RELATIONS: readonly R129PrimitiveRelation[] = Object.freeze([
  { fromPrimitiveId: 'SEASON_CONTEXT_FAVORABLE', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'FINAL_STRENGTH', researchMeaning: '得時 does not settle 旺/強.' },
  { fromPrimitiveId: 'SEASON_CONTEXT_UNFAVORABLE', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'FINAL_STRENGTH', researchMeaning: '失時 does not settle 弱/衰.' },
  { fromPrimitiveId: 'SEASON_ALONE_NOT_DECISIVE', relation: 'QUALIFIES', toPrimitiveId: 'SEASON_CONTEXT_FAVORABLE', researchMeaning: 'Favorable season remains non-conclusive.' },
  { fromPrimitiveId: 'SEASON_ALONE_NOT_DECISIVE', relation: 'QUALIFIES', toPrimitiveId: 'SEASON_CONTEXT_UNFAVORABLE', researchMeaning: 'Unfavorable season remains non-conclusive.' },
  { fromPrimitiveId: 'MONTH_CONTEXT_NOT_EXCLUSIVE', relation: 'QUALIFIES', toPrimitiveId: 'MONTH_CONTEXT_IMPORTANT_BOUNDED', researchMeaning: 'Month importance is bounded by anti-exclusivity.' },
  { fromPrimitiveId: 'MONTH_ROOT_PRIORITY_WITHIN_TONGGEN', relation: 'SCOPE_LIMITS', toPrimitiveId: 'MONTH_CONTEXT_IMPORTANT_BOUNDED', researchMeaning: 'Month-root priority is narrower than general month importance.' },
  { fromPrimitiveId: 'ROOT_STATUS_UNRESOLVED_OUTSIDE_GOVERNED_SCOPE', relation: 'QUALIFIES', toPrimitiveId: 'ROOT_SUPPORT_PRESENT_BOUNDED', researchMeaning: 'Positive bounded root evidence does not complete the global root resolver.' },
  { fromPrimitiveId: 'TOUGAN_TONGGEN_DISTINCT', relation: 'CONTRASTS_WITH', toPrimitiveId: 'ROOT_SUPPORT_PRESENT_BOUNDED', researchMeaning: 'Transparency and rootedness remain distinct relations.' },
  { fromPrimitiveId: 'ROOT_QUALITY_MATTERS', relation: 'QUALIFIES', toPrimitiveId: 'ROOT_SUPPORT_PRESENT_BOUNDED', researchMeaning: 'Root support has qualitative classes.' },
  { fromPrimitiveId: 'HEAVY_ROOT_CLASS_BOUNDED', relation: 'CONTRASTS_WITH', toPrimitiveId: 'LIGHT_ROOT_CLASS_BOUNDED', researchMeaning: 'Heavy/light are qualitative source classes.' },
  { fromPrimitiveId: 'VISIBLE_SUPPORT_NOT_EQUIVALENT_ROOT', relation: 'CONTRASTS_WITH', toPrimitiveId: 'PEER_SUPPORT_PRESENT', researchMeaning: 'Visible peer support is not root support.' },
  { fromPrimitiveId: 'ROOT_QUALITY_NOT_NUMERIC_WEIGHT', relation: 'QUALIFIES', toPrimitiveId: 'ROOT_QUALITY_MATTERS', researchMeaning: 'Qualitative root distinctions remain non-numeric.' },
  { fromPrimitiveId: 'YUQI_TEMPORAL_VARIABILITY', relation: 'QUALIFIES', toPrimitiveId: 'YUQI_ROOT_EVIDENCE_BOUNDED', researchMeaning: 'Yuqi evidence may require temporal qualification.' },
  { fromPrimitiveId: 'YUQI_TEMPORAL_WEIGHT_NOT_AUTHORIZED', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'YUQI_TEMPORAL_VARIABILITY', researchMeaning: 'Temporal variability does not imply a weight function.' },
  { fromPrimitiveId: 'MUKU_YIN_POLICY_DIVERGENT', relation: 'POLICY_FORKS', toPrimitiveId: 'MUKU_YANG_ROOT_BOUNDED', researchMeaning: 'Yang Muku authority does not automatically extend to Yin.' },
  { fromPrimitiveId: 'EARTH_MUKU_UNRESOLVED', relation: 'SCOPE_LIMITS', toPrimitiveId: 'MUKU_YANG_ROOT_BOUNDED', researchMeaning: 'Non-Earth Yang Muku does not resolve Earth.' },
  { fromPrimitiveId: 'YIN_CHANGSHENG_POLICY_DIVERGENT', relation: 'POLICY_FORKS', toPrimitiveId: 'YANG_CHANGSHENG_ROOT_BOUNDED', researchMeaning: 'Yang Changsheng authority does not automatically extend to Yin.' },
  { fromPrimitiveId: 'TWELVE_GROWTH_STAGE_NOT_AUTOMATIC_ROOT_CLASS', relation: 'QUALIFIES', toPrimitiveId: 'LU_ROOT_BOUNDED', researchMeaning: '臨官 stage is not automatically executable Lu.' },
  { fromPrimitiveId: 'TWELVE_GROWTH_STAGE_NOT_AUTOMATIC_ROOT_CLASS', relation: 'QUALIFIES', toPrimitiveId: 'WANG_ROOT_BOUNDED', researchMeaning: '帝旺 stage is not automatically executable Wang root.' },
  { fromPrimitiveId: 'HIDDEN_STEM_MEMBERSHIP_NOT_DEPTH', relation: 'CONTRASTS_WITH', toPrimitiveId: 'HIDDEN_TRANSPARENCY_CAN_CHANGE_ROLE', researchMeaning: 'Storage order is non-semantic while bounded transparency can affect role.' },
  { fromPrimitiveId: 'HIDDEN_ROLE_NOT_STRENGTH_LABEL', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'HIDDEN_TRANSPARENCY_CAN_CHANGE_ROLE', researchMeaning: 'Role change does not settle strength.' },
  { fromPrimitiveId: 'PEER_RESOURCE_MECHANISM_DISTINCT', relation: 'CONTRASTS_WITH', toPrimitiveId: 'PEER_SUPPORT_PRESENT', researchMeaning: 'Peer support mechanism remains distinct.' },
  { fromPrimitiveId: 'PEER_RESOURCE_MECHANISM_DISTINCT', relation: 'CONTRASTS_WITH', toPrimitiveId: 'RESOURCE_SUPPORT_PRESENT', researchMeaning: 'Resource support mechanism remains distinct.' },
  { fromPrimitiveId: 'SUPPORT_THRESHOLD_NOT_ESTABLISHED', relation: 'QUALIFIES', toPrimitiveId: 'SUPPORT_ACCUMULATION_QUALITATIVE', researchMeaning: 'Accumulation does not supply a threshold.' },
  { fromPrimitiveId: 'SUPPORT_FAMILY_PRESENCE_NOT_FINAL_STRENGTH', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'PEER_SUPPORT_PRESENT', researchMeaning: 'Peer presence does not settle strength.' },
  { fromPrimitiveId: 'SUPPORT_FAMILY_PRESENCE_NOT_FINAL_STRENGTH', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'RESOURCE_SUPPORT_PRESENT', researchMeaning: 'Resource presence does not settle strength.' },
  { fromPrimitiveId: 'OUTPUT_CAN_BE_USEFUL_OVER_SUPPORTED_CONTEXT', relation: 'QUALIFIES', toPrimitiveId: 'OUTPUT_RELATION_PRESENT', researchMeaning: 'Output can be useful in bounded over-supported context.' },
  { fromPrimitiveId: 'OUTPUT_CAN_FUNCTION_AS_LEAKAGE', relation: 'CAN_COEXIST_WITH', toPrimitiveId: 'OUTPUT_CONTROLS_KILL', researchMeaning: 'Output can leak and also control kill in local contexts.' },
  { fromPrimitiveId: 'WEALTH_CAPACITY_DEPENDENT', relation: 'QUALIFIES', toPrimitiveId: 'WEALTH_RELATION_PRESENT', researchMeaning: 'Wealth meaning depends on carrying capacity context.' },
  { fromPrimitiveId: 'WEALTH_CAN_FEED_CONTROL', relation: 'CAN_COEXIST_WITH', toPrimitiveId: 'WEALTH_CAPACITY_DEPENDENT', researchMeaning: 'Wealth can both burden capacity and feed a control chain.' },
  { fromPrimitiveId: 'CONTROL_EFFECT_CONTEXT_DEPENDENT', relation: 'QUALIFIES', toPrimitiveId: 'CONTROL_RELATION_PRESENT', researchMeaning: 'Control presence is not conclusive.' },
  { fromPrimitiveId: 'OUTPUT_GENERATES_WEALTH', relation: 'QUALIFIES', toPrimitiveId: 'RELATION_CHAIN_PRESENT', researchMeaning: 'Output→wealth is one local causal chain.' },
  { fromPrimitiveId: 'OUTPUT_CONTROLS_KILL', relation: 'QUALIFIES', toPrimitiveId: 'RELATION_CHAIN_PRESENT', researchMeaning: 'Output→control is one local control chain.' },
  { fromPrimitiveId: 'WEALTH_GENERATES_CONTROL', relation: 'QUALIFIES', toPrimitiveId: 'RELATION_CHAIN_PRESENT', researchMeaning: 'Wealth→control is one local generative chain.' },
  { fromPrimitiveId: 'LOCAL_CHAIN_ORDER_MATTERS', relation: 'QUALIFIES', toPrimitiveId: 'RELATION_CHAIN_PRESENT', researchMeaning: 'Local order can be semantically material.' },
  { fromPrimitiveId: 'LOCAL_ORDER_NOT_GLOBAL_PRECEDENCE', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'LOCAL_CHAIN_ORDER_MATTERS', researchMeaning: 'Local order does not create global precedence.' },
  { fromPrimitiveId: 'ONE_FEATURE_CHANGE_NOT_OPPOSITE_LABEL', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'FINAL_STRENGTH', researchMeaning: 'Single-feature sensitivity is not a label flip rule.' },
  { fromPrimitiveId: 'SOURCE_LABEL_NOT_COUNTERFACTUAL_LABEL', relation: 'SCOPE_LIMITS', toPrimitiveId: 'SOURCE_NATIVE_LABEL', researchMeaning: 'Source labels remain attached to observed source states.' },
  { fromPrimitiveId: 'SOURCE_COUNT_NOT_VOTE_COUNT', relation: 'QUALIFIES', toPrimitiveId: 'CROSS_SURFACE_AGREEMENT', researchMeaning: 'Cross-surface repetition does not imply independent votes.' },
  { fromPrimitiveId: 'SOURCE_POLICY_DIFFERENCE_NOT_DEFAULT_CHOICE', relation: 'POLICY_FORKS', toPrimitiveId: 'MUKU_YIN_POLICY_DIVERGENT', researchMeaning: 'Policy divergence remains unresolved without methodology selection.' },
  { fromPrimitiveId: 'SOURCE_POLICY_DIFFERENCE_NOT_DEFAULT_CHOICE', relation: 'POLICY_FORKS', toPrimitiveId: 'YIN_CHANGSHENG_POLICY_DIVERGENT', researchMeaning: 'Policy divergence remains unresolved without methodology selection.' },
  { fromPrimitiveId: 'CHALLENGING_RELATION_NOT_NEGATIVE_POINT', relation: 'QUALIFIES', toPrimitiveId: 'OUTPUT_RELATION_PRESENT', researchMeaning: 'Output challenging direction is non-scalar.' },
  { fromPrimitiveId: 'CHALLENGING_RELATION_NOT_NEGATIVE_POINT', relation: 'QUALIFIES', toPrimitiveId: 'WEALTH_RELATION_PRESENT', researchMeaning: 'Wealth challenging direction is non-scalar.' },
  { fromPrimitiveId: 'CHALLENGING_RELATION_NOT_NEGATIVE_POINT', relation: 'QUALIFIES', toPrimitiveId: 'CONTROL_RELATION_PRESENT', researchMeaning: 'Control challenging direction is non-scalar.' },
  { fromPrimitiveId: 'EXPLANATION_PRIMITIVE_NOT_CLASSIFIER_RULE', relation: 'DOES_NOT_IMPLY', toPrimitiveId: 'FINAL_STRENGTH', researchMeaning: 'R129 primitives are explanatory, not executable labels.' },
]);

export const R129_VIRTUAL_RELATION_TARGETS = Object.freeze([
  'FINAL_STRENGTH',
  'SOURCE_NATIVE_LABEL',
  'CROSS_SURFACE_AGREEMENT',
  'GENERIC_SUPPORT_UNIT',
  'TEN_GOD_FIXED_POLARITY',
] as const);

export const R129_REJECTED_EXPLANATION_SHORTCUTS = Object.freeze([
  'DE_SHI_THEREFORE_STRONG',
  'SHI_SHI_THEREFORE_WEAK',
  'ONE_ROOT_THEREFORE_STRONG',
  'NO_POSITIVE_ROOT_MATCH_THEREFORE_ROOTLESS',
  'MANY_PEERS_THEREFORE_STRONG',
  'MANY_RESOURCES_THEREFORE_STRONG',
  'OUTPUT_THEREFORE_WEAKER',
  'WEALTH_THEREFORE_DRAINED',
  'CONTROL_THEREFORE_WEAKER',
  'MONTH_BRANCH_THEREFORE_OVERRIDES_ALL',
  'MULTIPLE_CLASSICS_THEREFORE_CERTAIN',
  'ROOT_QUALITY_THEREFORE_NUMERIC_WEIGHT',
  'SUPPORT_ACCUMULATION_THEREFORE_SUPPORT_SCORE',
  'CHALLENGING_RELATION_THEREFORE_NEGATIVE_POINT',
  'LOCAL_CHAIN_ORDER_THEREFORE_GLOBAL_PRECEDENCE',
  'POLICY_DIVERGENCE_THEREFORE_PICK_MAJORITY',
  'EXPLANATION_PRIMITIVE_THEREFORE_FINAL_LABEL',
] as const);

const policyOrUncertaintyRoles = new Set<R129ExplanationRole>([
  'UNCERTAINTY',
  'POLICY_BOUNDARY',
]);

export const R129_SUMMARY = Object.freeze({
  primitiveCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.length,
  familyCount: new Set(R129_STRENGTH_EXPLANATION_PRIMITIVES.map((row) => row.family)).size,
  relationCount: R129_PRIMITIVE_RELATIONS.length,
  crossSurfaceBoundedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.portability === 'CROSS_SURFACE_BOUNDED',
  ).length,
  sourceOrMethodologyScopedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.portability === 'SOURCE_SCOPED' || row.portability === 'METHODOLOGY_SCOPED',
  ).length,
  policySensitiveOrUnresolvedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.portability === 'POLICY_SENSITIVE' || row.portability === 'UNRESOLVED',
  ).length,
  antiDeterminismOrUncertaintyCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => policyOrUncertaintyRoles.has(row.explanationRole),
  ).length,
  numericWeightAuthorizedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.authorizesNumericWeight,
  ).length,
  aggregationAuthorizedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.authorizesAggregation,
  ).length,
  finalStrengthAuthorizedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.authorizesFinalStrength,
  ).length,
  interpretationClaimAuthorizedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.authorizesInterpretationClaim,
  ).length,
  productionCopyAuthorizedCount: R129_STRENGTH_EXPLANATION_PRIMITIVES.filter(
    (row) => row.authorizesProductionCopy,
  ).length,
} as const);

export const R129_AUTHORITY = Object.freeze({
  status: 'RESEARCH_NONNUMERIC_STRENGTH_EXPLANATION_PRIMITIVE_INVENTORY_COMPLETE' as const,
  researchOnly: true,
  explanationVocabularyEstablishedBounded: true,
  seasonExplanationPrimitivesAvailable: true,
  rootPresenceQualityPrimitivesAvailable: true,
  peerResourceDistinctSupportPrimitivesAvailable: true,
  outputWealthControlDistinctPrimitivesAvailable: true,
  localRelationChainPrimitivesAvailable: true,
  sourcePolicyBoundaryPrimitivesAvailable: true,
  uncertaintyAntiDeterminismPrimitivesAvailable: true,
  numericStrengthModelAuthorized: false,
  primitiveAggregationRuleAuthorized: false,
  finalQiangRuoClassifierAuthorized: false,
  finalWangShuaiClassifierAuthorized: false,
  userFacingReadingCopyAuthorized: false,
  interpretationClaimEmissionAuthorized: false,
  automaticAuthorityAdmissionAuthorized: false,
  automaticEngineAdmissionAuthorized: false,
  previewPromotionAuthorized: false,
  productionAuthorityPromoted: false,
});
