export const R099_PRODUCTION_ISOLATION_REGRESSION_VERSION = '0.1.0-research' as const;

export const R099_INVARIANT_FAMILIES = Object.freeze([
  'RESEARCH_IMPORT_ISOLATION',
  'REGISTRY_STATUS_ISOLATION',
  'CONTENT_HASH_STABILITY',
  'CALCULATION_OUTPUT_STABILITY',
  'INTERPRETATION_OUTPUT_STABILITY',
  'UNKNOWN_FAIL_CLOSED',
  'PREVIEW_SHADOW_SEPARATION',
  'COMMERCE_ENTITLEMENT_SEPARATION',
  'AUTHORITY_DIFF_REQUIRED',
  'SUPERSESSION_TRACEABILITY',
] as const);

export const R099_INTENDED_PRODUCTION_CHANGE_REQUIREMENTS = Object.freeze([
  'EXPLICIT_AUTHORITY_LIFECYCLE_DIFF',
  'OLD_NEW_CONTENT_ADDRESSED_VERSION_LINEAGE',
  'GOVERNED_PROMOTION_EVIDENCE',
  'AFFECTED_FIXTURE_OUTPUT_DELTA_DECLARED',
] as const);

export const R099_REJECTED_SHORTCUTS = Object.freeze([
  'UPDATED_SNAPSHOT_EQUALS_AUTHORIZED_CHANGE',
  'RESEARCH_STATUS_RULE_IN_PRODUCTION_PACK',
  'SHADOW_WRITE_PROMOTES_AUTHORITY',
  'UNKNOWN_RESEARCH_VALUE_DEFAULTED_IN_PRODUCTION',
  'COMMERCE_CHANGE_HIDDEN_IN_RESEARCH_DIFF',
] as const);

export const R099_AUTHORITY = Object.freeze({
  status:'PRODUCTION_ISOLATION_REGRESSION_INVARIANTS_DEFINED' as const,
  invariantFamilyCount:10,
  silentAuthorityDriftAllowed:false,
  snapshotUpdateAloneAuthorizesChange:false,
  existingCiWorkflowsMutated:false,
  productionAuthorityPromoted:false,
});
