export const R099_PRODUCTION_ISOLATION_REGRESSION_VERSION = '0.2.0-research' as const;

export const R099_INVARIANT_FAMILIES = Object.freeze([
  'RESEARCH_IMPORT_ISOLATION',
  'REGISTRY_STATUS_ISOLATION',
  'CONTENT_HASH_STABILITY',
  'CALCULATION_OUTPUT_STABILITY',
  'INTERPRETATION_OUTPUT_STABILITY',
  'UNKNOWN_FAIL_CLOSED',
  'PREVIEW_SHADOW_SEPARATION',
  'COMMERCE_ENTITLEMENT_SEPARATION',
  'AUTHORITY_DIFF_REQUIRED',
  'SUPERSESSION_TRACEABILITY',
] as const);

export const R099_REQUIRED_ORACLE_FIELDS = Object.freeze([
  'INVARIANT_FAMILY',
  'PROTECTED_SURFACE_REF',
  'BASELINE_REF',
  'OBSERVATION_REF',
  'COMPARISON_MODE',
  'ALLOWED_DELTA_POLICY_REF',
  'AUTHORITY_DIFF_RECEIPT_REF_IF_INTENDED_DELTA',
  'RESULT',
  'FAILURE_REASON_REF_IF_FAILED',
] as const);

export const R099_ORACLE_RESULTS = Object.freeze([
  'PASS_STABLE',
  'PASS_AUTHORIZED_DELTA',
  'FAIL_SILENT_DRIFT',
  'FAIL_MISSING_BASELINE',
  'FAIL_MISSING_AUTHORITY_DIFF',
  'FAIL_UNTRACEABLE_SUPERSESSION',
] as const);

export const R099_INTENDED_PRODUCTION_CHANGE_REQUIREMENTS = Object.freeze([
  'OLD_CONTENT_HASH_AND_VERSION',
  'NEW_CONTENT_HASH_AND_VERSION',
  'GOVERNED_PROMOTION_EVIDENCE',
  'AUTHORITY_ACTOR_OR_DECISION_REF',
  'AFFECTED_PROTECTED_SURFACES',
  'DECLARED_EXPECTED_FIXTURE_OUTPUT_DELTAS',
  'SEPARATE_LIFECYCLE_MUTATION_RECEIPT',
] as const);

export const R099_MUTATION_PROBE_REQUIREMENTS = Object.freeze([
  'RESEARCH_IMPORT_INTO_PROTECTED_PRODUCTION_BOUNDARY_IS_DETECTED',
  'PROTECTED_FINGERPRINT_CHANGE_WITHOUT_AUTHORITY_RECEIPT_IS_DETECTED',
  'CALCULATION_OR_INTERPRETATION_DRIFT_UNDER_RESEARCH_ONLY_CHANGE_IS_DETECTED',
  'UNRESOLVED_RESEARCH_VALUE_DEFAULTED_IN_PRODUCTION_IS_DETECTED',
  'SHADOW_AUTHORITY_WRITE_IS_DETECTED',
] as const);

export const R099_CROSS_CONTRACT_RULES = Object.freeze([
  'R096_STATE_LABEL_IS_NOT_PRODUCTION_FALLBACK_VALUE',
  'R098_PROMOTION_ELIGIBLE_IS_NOT_PROMOTED',
  'R098_CHECKLIST_ALONE_IS_NOT_LIFECYCLE_MUTATION_RECEIPT',
  'CANDIDATE_HASH_OR_VERSION_CHANGE_REQUIRES_REEVALUATION',
] as const);

export const R099_EXECUTION_SURFACES = Object.freeze([
  'CI',
  'PRODUCTION_CALCULATION_CONTAINER',
  'PIE_SHADOW',
] as const);

export const R099_REQUIRED_FAILURE_CLASSES = Object.freeze([
  'SILENT_IMPORT_BOUNDARY_DRIFT',
  'SILENT_REGISTRY_LIFECYCLE_DRIFT',
  'PROTECTED_HASH_DRIFT',
  'CALCULATION_OUTPUT_DRIFT',
  'INTERPRETATION_OUTPUT_DRIFT',
  'UNKNOWN_DEFAULT_COERCION',
  'SHADOW_AUTHORITY_WRITE',
  'COMMERCE_ENTITLEMENT_DRIFT',
  'MISSING_AUTHORITY_RECEIPT',
  'BROKEN_SUPERSESSION_LINEAGE',
] as const);

export const R099_REJECTED_SHORTCUTS = Object.freeze([
  'UPDATED_SNAPSHOT_EQUALS_AUTHORIZED_CHANGE',
  'RESEARCH_STATUS_RULE_IN_PRODUCTION_PACK',
  'SHADOW_WRITE_PROMOTES_AUTHORITY',
  'UNKNOWN_RESEARCH_VALUE_DEFAULTED_IN_PRODUCTION',
  'COMMERCE_CHANGE_HIDDEN_IN_RESEARCH_DIFF',
  'GREEN_TESTS_IMPLY_AUTHORIZATION',
  'PR_MERGE_IMPLIES_AUTHORIZATION',
  'R098_ELIGIBLE_IMPLIES_LIFECYCLE_MUTATED',
  'MISSING_BASELINE_SKIPPED_AS_PASS',
  'MISSING_AUTHORITY_RECEIPT_SKIPPED_AS_PASS',
  'OLD_VERSION_DELETED_WITHOUT_SUPERSESSION_LINEAGE',
  'TEST_FILE_EXISTENCE_COUNTS_AS_DRIFT_PROTECTION',
] as const);

export const R099_AUTHORITY = Object.freeze({
  status: 'FAIL_CLOSED_PRODUCTION_ISOLATION_REGRESSION_CONTRACT_DEFINED' as const,
  invariantFamilyCount: 10,
  executableOracleRequired: true,
  mutationProbeRequiredForDetectorLiveness: true,
  missingBaselineFailsClosed: true,
  missingAuthorityReceiptFailsClosed: true,
  silentAuthorityDriftAllowed: false,
  snapshotUpdateAloneAuthorizesChange: false,
  greenTestsAloneAuthorizeChange: false,
  promotionEligibleEqualsPromoted: false,
  researchChangeMayAlterCommerceEntitlement: false,
  existingCiWorkflowsMutated: false,
  parallelWorkflowCreated: false,
  productionAuthorityPromoted: false,
});
