export const R098_PROMOTION_CHECKLIST_VERSION = '0.2.0-research' as const;

export const R098_REQUIRED_GATES = Object.freeze([
  'CLAIM_SCOPE_FROZEN',
  'METHODOLOGY_AND_SOURCE_SCOPE_IDENTIFIED',
  'WORK_EDITION_WITNESS_PROVENANCE_BOUND',
  'PASSAGE_PROPOSITION_BINDING_COMPLETE',
  'RIGHTS_REUSE_CONSTRAINTS_RECORDED',
  'COUNTEREXAMPLES_AND_DIVERGENCE_REVIEWED',
  'CALCULATION_TIME_CONVENTIONS_EXPLICIT',
  'EXECUTABLE_PREDICATES_NO_HIDDEN_GUESSES',
  'AMBIGUITY_UNKNOWN_FAIL_CLOSED',
  'DETERMINISTIC_AND_REGRESSION_TESTS_PASS',
  'CONTENT_HASH_VERSION_SUPERSESSION_PINNED',
  'REQUIRED_DOMAIN_REVIEW_ATTESTATION_SATISFIED',
  'PRODUCT_LANGUAGE_WITHIN_SOURCE_BOUND_SEMANTICS',
  'REQUIRED_SHADOW_STAGING_EVIDENCE_COMPLETE',
  'EXPLICIT_GOVERNANCE_AUTHORITY_DECISION_RECORDED',
] as const);

export const R098_GATE_STATUSES = Object.freeze([
  'SATISFIED',
  'PENDING',
  'BLOCKED',
  'NOT_APPLICABLE_WITH_JUSTIFICATION',
] as const);

export const R098_GATE_APPLICABILITY = Object.freeze([
  'REQUIRED',
  'CONDITIONAL',
] as const);

export const R098_REQUIRED_GATE_RECORD_FIELDS = Object.freeze([
  'GATE_ID',
  'STATUS',
  'APPLICABILITY',
  'EVIDENCE_REFS',
  'REVIEWED_AT',
  'REVIEWER_OR_AUTHORITY_REF',
  'BLOCKING_REASON_REF_IF_BLOCKED_OR_PENDING',
  'NOT_APPLICABLE_POLICY_REF_AND_JUSTIFICATION_IF_NOT_APPLICABLE',
] as const);

export const R098_CHECKLIST_STATES = Object.freeze([
  'BLOCKED',
  'RESEARCH_READY',
  'REVIEW_READY',
  'SHADOW_READY',
  'PROMOTION_ELIGIBLE',
] as const);

export const R098_CANDIDATE_IDENTITY_FIELDS = Object.freeze([
  'CLAIM_ID',
  'CONTENT_HASH',
  'VERSION',
  'METHODOLOGY_SOURCE_SCOPE_REF',
  'INTENDED_LIFECYCLE_TARGET',
] as const);

export const R098_CROSS_CONTRACT_EVIDENCE_RULES = Object.freeze([
  'R091_IDENTITY_MAY_EVIDENCE_GATE_3',
  'R093_PROVENANCE_MAY_EVIDENCE_GATE_4',
  'R094_COUNTEREXAMPLES_MAY_EVIDENCE_GATE_6',
  'R095_LINEAGE_SCOPE_MAY_EVIDENCE_GATE_2',
  'R096_STATE_LABEL_DOES_NOT_REPLACE_GATE_EVIDENCE',
  'R097_INSPECTION_MAY_EVIDENCE_SCAN_BOUND_GATE_4',
  'R090_EXPERT_REVIEW_MAY_EVIDENCE_GATE_12_WHEN_REQUIRED',
] as const);

export const R098_PROMOTION_ELIGIBILITY_RULES = Object.freeze([
  'ALL_REQUIRED_GATES_MUST_BE_SATISFIED_OR_GOVERNED_NOT_APPLICABLE',
  'NOT_APPLICABLE_REQUIRES_POLICY_REF_AND_JUSTIFICATION',
  'GATE_15_REQUIRES_EXPLICIT_GOVERNANCE_DECISION_FOR_EXACT_CANDIDATE',
  'PROMOTION_ELIGIBLE_DOES_NOT_MUTATE_LIFECYCLE',
  'CANDIDATE_HASH_OR_VERSION_CHANGE_REQUIRES_GATE_REEVALUATION',
] as const);

export const R098_REJECTED_IMPLICIT_PROMOTION = Object.freeze([
  'MERGE_IMPLIES_PROMOTION',
  'TEST_PASS_IMPLIES_PROMOTION',
  'SOURCE_COUNT_IMPLIES_PROMOTION',
  'EXPERT_VOTE_IMPLIES_PROMOTION',
  'PRODUCT_DEMAND_IMPLIES_PROMOTION',
  'SHADOW_PASS_IMPLIES_PROMOTION',
  'EVIDENCE_STATE_IMPLIES_PROMOTION',
  'CONDITIONAL_GATE_SILENTLY_SKIPPED',
  'NOT_APPLICABLE_WITHOUT_POLICY_AND_JUSTIFICATION',
  'OLD_CHECKLIST_REUSED_AFTER_CANDIDATE_HASH_CHANGE',
  'ELIGIBLE_STATE_AUTO_MUTATES_LIFECYCLE',
] as const);

export const R098_AUTHORITY = Object.freeze({
  status: 'FAIL_CLOSED_PROMOTION_CHECKLIST_DEFINED' as const,
  requiredGateCount: 15,
  conditionalGateSilentSkipAuthorized: false,
  notApplicableRequiresPolicyAndJustification: true,
  promotionEligibleRequiresExactCandidateDecision: true,
  promotionEligibleAutoPromotes: false,
  checklistStateIsConfidenceScore: false,
  candidateHashChangeRequiresReevaluation: true,
  lifecycleMutationRequiresSeparateAuthorityAction: true,
  productionAuthorityPromoted: false,
});
