export const R096_EVIDENCE_STATE_MODEL_VERSION = '0.2.0-research' as const;

export const R096_PRIMARY_STATES = Object.freeze([
  'VERIFIED_BOUNDED',
  'VERIFIED_VARIANT',
  'DIVERGENT_BY_SOURCE_OR_SCHOOL',
  'PARTIALLY_SUPPORTED',
  'INCONCLUSIVE',
  'UNVERIFIED',
  'CONTRADICTED_WITHIN_SCOPE',
  'EXECUTION_PENDING',
] as const);

export const R096_ORTHOGONAL_DIMENSIONS = Object.freeze([
  'PROVENANCE_QUALITY',
  'PASSAGE_BINDING_COMPLETENESS',
  'PROPOSITION_SCOPE_MATCH',
  'SOURCE_INDEPENDENCE_OR_DERIVATION',
  'CROSS_SOURCE_AGREEMENT_OR_DIVERGENCE',
  'IMPLEMENTATION_EXECUTION_VERIFICATION',
  'EXPERT_REVIEW_STATUS',
  'TEMPORAL_CALCULATION_CONVENTION_STABILITY',
] as const);

export const R096_REQUIRED_STATE_ASSIGNMENT_FIELDS = Object.freeze([
  'STATE_ASSIGNMENT_ID',
  'SUBJECT_CLAIM_REF',
  'STATE',
  'SCOPE_REF',
  'EVIDENCE_EVENT_REFS',
  'PROVENANCE_REFS',
  'DIMENSION_SNAPSHOT_REF',
  'RECORDED_AT',
  'PREVIOUS_STATE_ASSIGNMENT_REF_IF_TRANSITION',
  'TRANSITION_REASON_REF_IF_TRANSITION',
] as const);

export const R096_TRANSITION_RULES = Object.freeze([
  'TRANSITION_REQUIRES_EXPLICIT_EVIDENCE_EVENT',
  'TRANSITION_REFERENCES_PREVIOUS_ASSIGNMENT',
  'STATE_HISTORY_APPEND_ONLY',
  'NO_MONOTONIC_PROGRESSION_ASSUMED',
  'VERIFIED_BOUNDED_MAY_REOPEN_ON_SCOPED_CONTRADICTORY_EVIDENCE',
  'INCONCLUSIVE_DOES_NOT_COERCE_TO_FALSE_OR_CONTRADICTED',
] as const);

export const R096_CROSS_CONTRACT_RULES = Object.freeze([
  'R093_GRAPH_CONNECTIVITY_DOES_NOT_AUTO_ASSIGN_STATE',
  'R094_COUNTEREXAMPLE_COUNT_DOES_NOT_AUTO_ASSIGN_STATE',
  'R095_LINEAGE_POPULARITY_OR_SENIORITY_DOES_NOT_ASSIGN_STATE',
] as const);

export const R096_FUTURE_NUMERIC_CALIBRATION_REQUIREMENTS = Object.freeze([
  'SEPARATELY_GOVERNED_CALIBRATION_STUDY',
  'TARGET_OUTCOME',
  'LABELED_POPULATION',
  'MEASUREMENT_VALIDITY',
  'CALIBRATION_METHOD',
  'ERROR_AND_UNCERTAINTY_ANALYSIS',
  'SCOPE',
  'VERSIONING',
  'ADMISSION_AND_RETIREMENT_RULES',
] as const);

export const R096_REJECTED_SHORTCUTS = Object.freeze([
  'NUMERIC_CONFIDENCE_PERCENTAGE',
  'STAR_RATING',
  'SOURCE_COUNT_SCORE',
  'REVIEWER_COUNT_SCORE',
  'HIDDEN_WEIGHTED_SUM',
  'HIDDEN_LEXICOGRAPHIC_RANKING',
  'PRIMARY_STATES_HAVE_IMPLICIT_ORDINAL_ORDER',
  'DIMENSION_SNAPSHOT_AUTO_DERIVES_PRIMARY_STATE',
  'DIVERGENT_EQUALS_LOW_CONFIDENCE',
  'INCONCLUSIVE_EQUALS_FALSE',
  'UNVERIFIED_EQUALS_CONTRADICTED',
  'VERIFIED_BOUNDED_EQUALS_UNIVERSAL',
  'STATE_CHANGE_WITHOUT_EVIDENCE_EVENT',
  'STATE_HISTORY_OVERWRITTEN',
] as const);

export const R096_AUTHORITY = Object.freeze({
  status: 'QUALITATIVE_EVIDENCE_STATE_MODEL_ONLY' as const,
  arithmeticAggregationAuthorized: false,
  implicitOrdinalRankingAuthorized: false,
  dimensionSnapshotAutoDerivesState: false,
  stateTransitionRequiresEvidenceEvent: true,
  stateHistoryAppendOnly: true,
  monotonicProgressionAssumed: false,
  verifiedBoundedMeansUniversal: false,
  divergentPreservesPlurality: true,
  inconclusiveCoercesToFalse: false,
  unverifiedEqualsContradicted: false,
  numericCalibrationAuthorized: false,
  productionAuthorityPromoted: false,
});
