export const R097_SCAN_INSPECTION_MANIFEST_VERSION = '0.1.0-research' as const;

export const R097_REQUIRED_FIELDS = Object.freeze([
  'WORK_EDITION_WITNESS_IDS',
  'IMMUTABLE_FILE_LOCATOR_IF_AVAILABLE',
  'FILE_CHECKSUM',
  'PAGE_INDEX',
  'PRINTED_PAGE_LABEL_IF_PRESENT',
  'COORDINATE_SYSTEM',
  'CROP_BOUNDING_BOX_IF_CLAIM_LOCAL',
  'ROTATION_ORIENTATION',
  'RENDER_DPI_OR_SCALE',
  'VISIBLE_TEXT_TRANSCRIPTION',
  'TRANSCRIPTION_METHOD',
  'UNCERTAINTY_OR_ILLEGIBLE_SPANS',
  'INSPECTOR_TIMESTAMP_TOOL_VERSION_IF_APPLICABLE',
  'SUPPORTED_CLAIM_IDS',
] as const);

export const R097_TRANSCRIPTION_METHODS = Object.freeze([
  'HUMAN_VISUAL',
  'BUILT_IN_VISION',
  'OCR_LAST_RESORT',
] as const);

export const R097_REJECTED_SHORTCUTS = Object.freeze([
  'PDF_INDEX_EQUALS_PRINTED_PAGE',
  'OCR_OUTPUT_EQUALS_WITNESS_TEXT',
  'SILENTLY_GUESS_ILLEGIBLE_CHARACTERS',
  'SCREENSHOT_WITHOUT_WITNESS_IDENTITY',
  'REUSE_REGION_AFTER_FILE_CHECKSUM_CHANGE',
] as const);

export const R097_AUTHORITY = Object.freeze({
  status:'REPRODUCIBLE_SCAN_INSPECTION_MANIFEST_DEFINED' as const,
  pageIndexEqualsPrintedPage:false,
  ocrAsWitnessAuthorized:false,
  checksumChangeRequiresReinspection:true,
  sourceIdentityRequired:true,
  productionAuthorityPromoted:false,
});
