export const R095_SCHOOL_LINEAGE_TAG_VERSION = '0.2.0-research' as const;

export const R095_TAG_DIMENSIONS = Object.freeze([
  'TRADITION_FAMILY',
  'WORK_OR_COMMENTARY_LINEAGE',
  'AUTHOR_COMMENTATOR_PRACTITIONER',
  'HISTORICAL_OR_PUBLICATION_CONTEXT',
  'METHODOLOGY_FAMILY',
  'TERMINOLOGY_PROFILE',
  'CALCULATION_CONVENTION_DEPENDENCY',
] as const);

export const R095_TAG_ASSERTION_REVIEW_STATES = Object.freeze([
  'VERIFIED',
  'REVIEWED',
  'INCONCLUSIVE',
] as const);

export const R095_REQUIRED_TAG_ASSERTION_FIELDS = Object.freeze([
  'ASSERTION_ID',
  'SUBJECT_REF',
  'DIMENSION',
  'TAG_VALUE',
  'EVIDENCE_REFS',
  'REVIEW_STATE',
  'SCOPE_REF',
] as const);

export const R095_LINEAGE_RELATIONS = Object.freeze([
  'SAME_TRADITION',
  'DERIVED',
  'COMMENTARY_ON',
  'UNKNOWN',
] as const);

export const R095_PROPOSITION_RELATIONS = Object.freeze([
  'EQUIVALENT_WITHIN_SCOPE',
  'PARTIAL_OVERLAP',
  'DIVERGENT',
  'INCOMPARABLE',
  'UNKNOWN',
] as const);

export const R095_RELATION_ASSERTION_RULES = Object.freeze([
  'NON_UNKNOWN_LINEAGE_RELATION_REQUIRES_EVIDENCE_REFS',
  'PROPOSITION_RELATION_REQUIRES_EXPLICIT_PROPOSITION_REFS',
  'DIFFERENT_LABELS_DO_NOT_IMPLY_DIVERGENCE',
  'SAME_LABEL_DOES_NOT_IMPLY_SEMANTIC_EQUIVALENCE',
  'LINEAGE_RELATION_DOES_NOT_REWRITE_PROPOSITION_RELATION',
  'PROPOSITION_RELATION_DOES_NOT_REWRITE_LINEAGE_RELATION',
] as const);

export const R095_COMPOSITION_POLICY_REQUIREMENTS = Object.freeze([
  'EXPLICIT_VERSIONED_POLICY_REQUIRED',
  'ELIGIBLE_METHODOLOGY_OR_SOURCE_FAMILIES',
  'COMPATIBILITY_CONDITIONS',
  'PRESERVED_CONFLICTS_AND_AMBIGUITIES',
  'PROHIBITED_COMBINATIONS',
  'OUTPUT_SCOPE',
] as const);

export const R095_REJECTED_SHORTCUTS = Object.freeze([
  'POPULARITY_EQUALS_AUTHORITY',
  'SENIORITY_EQUALS_CONFIDENCE',
  'AUTO_SELECT_CANONICAL_SCHOOL',
  'SAME_LABEL_EQUALS_SAME_SEMANTICS',
  'DIFFERENT_LABEL_EQUALS_DIVERGENCE',
  'LINEAGE_RELATION_EQUALS_PROPOSITION_EQUIVALENCE',
  'PRACTITIONER_TAG_PROPAGATES_TO_ALL_CITED_SOURCES',
  'LINEAGE_RELATION_TRANSITIVELY_PROPAGATES_AUTHORITY',
  'CROSS_SCHOOL_BLEND_WITHOUT_COMPOSITION_POLICY',
] as const);

export const R095_AUTHORITY = Object.freeze({
  status: 'DESCRIPTIVE_LINEAGE_TAG_TAXONOMY_ONLY' as const,
  tagAssertionsRequireEvidence: true,
  tagsAsAuthorityWeights: false,
  lineageAndPropositionRelationsSeparated: true,
  propositionComparisonRequiredForDivergence: true,
  forcedReconciliationAuthorized: false,
  transitiveAuthorityPropagationAuthorized: false,
  practitionerTagInheritanceAuthorized: false,
  crossSchoolBlendWithoutCompositionPolicyAuthorized: false,
  unknownLineagePreserved: true,
  productionAuthorityPromoted: false,
});
