export const R084_FALSE_POSITIVE_PATTERNS_VERSION = '0.1.0-research' as const;

export const R084_FALSE_POSITIVE_PATTERNS = Object.freeze([
  ['FP01','CANDIDATE_STRUCTURE','PATTERN_ESTABLISHED',['ESTABLISHMENT_PREDICATES','RESCUE','CONFLICT_SETTLEMENT'],['R021','R030']],
  ['FP02','RELATION_PRESENT','FIXED_GOOD_BAD',['POSITION_CONTEXT','COMPETING_INTERACTIONS','RESCUE'],['R052-R059']],
  ['FP03','TEN_GOD_PRESENT','CONCRETE_DOMAIN_OUTCOME',['DOMAIN_BRIDGE','CONFIGURATION','TEMPORAL_EVIDENCE'],['R065-R070']],
  ['FP04','FAMILY_STAR_PRESENT_OR_ABSENT','RELATIVE_EXISTENCE_OR_FIXED_OUTCOME',['METHOD_SEX_SCOPE','CONFIGURATION','MODERN_TRANSLATION'],['R070']],
  ['FP05','LUCK_NOMINALLY_SUPPORTS_XI_YONG','FAVORABLE_EVENT',['NATAL_RESCUE_BLOCKING','STRUCTURAL_STATE','EVENT_BRIDGE'],['R077']],
  ['FP06','LATENT_COMPONENT_ACTIVATED','CONCRETE_EVENT',['DURATION','STRUCTURAL_THRESHOLD','EVENT_BRIDGE'],['R073']],
  ['FP07','ANNUAL_MONTHLY_RELATION_MATCH','CONCRETE_EVENT',['NATAL_DAYUN_ANNUAL_MONTH_COMPOSITION'],['R074','R075','R079']],
  ['FP08','SOURCE_WORKED_EXAMPLE','ENGINE_GROUND_TRUTH',['INDEPENDENT_VALIDATION','GOVERNED_RULE_MAPPING'],['R081','R083:#1235']],
  ['FP09','RETROSPECTIVE_ALIGNMENT','PREDICTIVE_ACCURACY',['PROSPECTIVE_CASES','NEGATIVE_CASES','CALIBRATION'],['R080']],
  ['FP10','SOURCE_PROVIDED_CHART','INDEPENDENT_CALCULATION_VERIFIED',['EXACT_BIRTH_INPUTS','BOUNDARY_POLICIES','CALCULATOR_PROVENANCE'],['R082','R083:#1235']],
  ['FP11','MULTIPLE_GEJU_CANDIDATES','NUMERIC_WINNER_OR_SINGLE_FINAL_PATTERN',['SOURCE_GOVERNED_CONFLICT_SETTLEMENT'],['R030']],
  ['FP12','ORDINARY_PATTERN_BROKEN','AUTO_ENTER_FOLLOW_PATTERN',['ONE_SIDEDNESS','NO_FUYI','ORDINARY_RESCUE_CHECK','EXTERNAL_PATTERN_GATES'],['R029']],
].map(([id, trigger, unsupportedLeap, missingEvidence, evidenceRefs]) => Object.freeze({
  id,
  trigger,
  unsupportedLeap,
  missingEvidence,
  evidenceRefs,
  productionAssertion: 'HOLD' as const,
  executableRepair: false,
})));

export const R084_AUTHORITY = Object.freeze({
  status: 'VERIFIED_FALSE_POSITIVE_DIAGNOSTIC_CORPUS' as const,
  patternCount: 12,
  numericFalsePositiveProbabilityAuthorized: false,
  automaticRepairAuthorized: false,
  productionBehaviorChanged: false,
});
