export const R085_FALSE_NEGATIVE_PATTERNS_VERSION = '0.1.0-research' as const;

export const R085_FALSE_NEGATIVE_PATTERNS = Object.freeze([
  ['FN01','KEEP_ONLY_FIRST_OR_MONTH_COMMAND_CANDIDATE','COEXISTING_CANDIDATES',['PRESERVE_PLURAL_CANDIDATE_STATE']],
  ['FN02','EVERY_CLASH_IS_DESTRUCTIVE','CLASH_RESCUE_OR_RESOLUTION',['POSITION_CONTEXT','COMPETING_INTERACTION_CORPUS']],
  ['FN03','HIDDEN_STEMS_ALWAYS_INERT','TRANSPARENCY_OR_LUCK_ACTIVATION',['GOVERNED_ACTIVATION_TRIGGER']],
  ['FN04','OFFICER_PLUS_HURTING_ALWAYS_FAILS','METAL_WATER_CLIMATE_EXCEPTION_OR_RESCUE',['CLIMATE_CONTEXT','RESCUE_CONTEXT']],
  ['FN05','OUTPUT_PLUS_SEAL_ALWAYS_FAILS','BOUNDED_SEAL_SUCCESS_PATH',['STRENGTH','SEAL_ROOTEDNESS','CONFIGURATION']],
  ['FN06','WEALTH_PLUS_SEAL_ALWAYS_MUTUALLY_DESTROYS','CONTEXTUAL_ROLE_OR_RESCUE',['RELATION_DIRECTION','CONFIGURATION']],
  ['FN07','ORDINARY_STRUCTURE_BLOCKS_ALL_TRANSITIONS','JIANLU_YUEJIE_OR_STRUCTURAL_CHANGE',['TRANSITION_PREDICATES']],
  ['FN08','ALL_EXTERNAL_FOLLOW_PATTERNS_DISABLED','ONE_SIDED_NO_FUYI_CASES',['GLOBAL_ENTRY_GATES']],
  ['FN09','ANNUAL_STEM_EMPHASIS_MEANS_STEM_ONLY','ANNUAL_BRANCH_ROOT_SUPPORT',['RETAIN_BRANCH_PARTICIPATION']],
  ['FN10','MONTHLY_LUCK_IGNORED','LOWER_TEMPORAL_LAYER',['NATAL_DAYUN_ANNUAL_COMPOSITION']],
  ['FN11','FORCE_ALL_SOURCE_VARIANTS_TO_ONE_REGISTRY','SOURCE_STRATUM_VARIANTS',['LINEAGE_SOURCE_TAGS']],
  ['FN12','UNRESOLVED_COERCED_TO_FALSE','INDETERMINATE_CANDIDATE',['PRESERVE_UNRESOLVED_STATE']],
].map(([id, filter, suppressedEvidence, recoveryEvidence]) => Object.freeze({
  id,
  filter,
  suppressedEvidence,
  recoveryEvidence,
  suppressedEvidenceAutomaticallyTrue: false,
  executableRepair: false,
})));

export const R085_AUTHORITY = Object.freeze({
  status: 'VERIFIED_FALSE_NEGATIVE_DIAGNOSTIC_CORPUS' as const,
  patternCount: 12,
  suppressedEvidenceAutomaticallyTrue: false,
  automaticRepairAuthorized: false,
  productionBehaviorChanged: false,
});
