export const RELATIONSHIP_SPOUSE_T8_DAY_BRANCH_PALACE_CLAIM_NARRATIVE_PROFILE_VERSION_CONTRACT =
  '1.0.0-research' as const;

export const RELATIONSHIP_SPOUSE_T8_DAY_BRANCH_PALACE_PROJECT_REVIEWER_STATUS =
  'internal_reviewed' as const;
