import type {
  FaceAuthorityRegistry,
  FaceClaimTypeDefinition,
  FaceComparisonPolicy,
  FaceMethodologyPackDefinition,
  SourceLineageRelation,
  SourcePassage,
  SourceWitness,
  SourceWork,
} from './contracts.js';

export const FACE_RESEARCH_WORKS_V0 = [
  {
    workId: 'work.shenxiang_quanbian',
    canonicalTitle: '神相全編',
    alternateTitles: ['Shenxiang Quanbian'],
    attributedAuthors: ['陳摶（傳）', '袁忠徹（訂正）'],
    sourceClass: 'primary_manual',
  },
  {
    workId: 'work.renlun_datongfu',
    canonicalTitle: '人倫大統賦',
    alternateTitles: ['Renlun Datongfu'],
    attributedAuthors: ['張行簡'],
    estimatedPeriod: '金代',
    sourceClass: 'primary_manual',
  },
  {
    workId: 'work.mayi_xiangfa',
    canonicalTitle: '麻衣相法',
    alternateTitles: ['Mayi Xiangfa'],
    attributedAuthors: ['傳統題署 불확정', '秦慎安（校勘，1925 witness）'],
    sourceClass: 'primary_manual',
  },
  {
    workId: 'work.liuzhuang_xiangfa',
    canonicalTitle: '柳莊相法',
    alternateTitles: ['Liuzhuang Xiangfa'],
    attributedAuthors: ['袁柳莊（傳）'],
    sourceClass: 'primary_manual',
  },
  {
    workId: 'work.kohn_1986',
    canonicalTitle: 'A Textbook of Physiognomy: The Tradition of the Shenxiang quanbian',
    alternateTitles: [],
    attributedAuthors: ['Livia Kohn'],
    estimatedPeriod: '1986',
    sourceClass: 'scholarly_lineage',
  },
] as const satisfies readonly SourceWork[];

export const FACE_RESEARCH_WITNESSES_V0 = [
  {
    witnessId: 'witness.shenxiang_quanbian.nlc_1925',
    workId: 'work.shenxiang_quanbian',
    editionLabel: '文明書局 民國十四年本 — NLC scan',
    publicationYear: 1925,
    holdingInstitution: 'National Library of China',
    digitalSourceUrl: 'https://commons.wikimedia.org/wiki/File:NLC416-13jh001662-59167_神相全編.pdf',
    witnessStatus: 'verified',
  },
  {
    witnessId: 'witness.shenxiang_quanbian.ctext',
    workId: 'work.shenxiang_quanbian',
    editionLabel: 'Chinese Text Project electronic transcription',
    digitalSourceUrl: 'https://ctext.org/wiki.pl?chapter=905153&if=gb',
    witnessStatus: 'candidate',
  },
  {
    witnessId: 'witness.mayi_xiangfa.nlc_1925_v1',
    workId: 'work.mayi_xiangfa',
    editionLabel: '文明書局 民國十四年 第1卷 — NLC scan',
    publicationYear: 1925,
    holdingInstitution: 'National Library of China',
    digitalSourceUrl: 'https://commons.wikimedia.org/wiki/File:NLC416-12jh002690-44091_麻衣相法_第1卷.pdf',
    witnessStatus: 'verified',
  },
  {
    witnessId: 'witness.mayi_xiangfa.nlc_1925_v2',
    workId: 'work.mayi_xiangfa',
    editionLabel: '文明書局 民國十四年 第2卷 — NLC scan',
    publicationYear: 1925,
    holdingInstitution: 'National Library of China',
    digitalSourceUrl: 'https://commons.wikimedia.org/wiki/File:NLC416-12jh002690-44092_麻衣相法_第2卷.pdf',
    witnessStatus: 'verified',
  },
  {
    witnessId: 'witness.liuzhuang_xiangfa.nlc_1925',
    workId: 'work.liuzhuang_xiangfa',
    editionLabel: '民國十四年本 — NLC scan',
    publicationYear: 1925,
    holdingInstitution: 'National Library of China',
    digitalSourceUrl: 'https://commons.wikimedia.org/wiki/File:NLC416-13jh001257-42702_柳莊相法.pdf',
    witnessStatus: 'verified',
  },
  {
    witnessId: 'witness.liuzhuang_xiangfa.ctext',
    workId: 'work.liuzhuang_xiangfa',
    editionLabel: 'Chinese Text Project electronic transcription',
    digitalSourceUrl: 'https://ctext.org/wiki.pl?chapter=90958&if=gb',
    witnessStatus: 'candidate',
  },
  {
    witnessId: 'witness.renlun_datongfu.wikisource',
    workId: 'work.renlun_datongfu',
    editionLabel: 'Wikisource transcription, 卷上',
    digitalSourceUrl: 'https://zh.wikisource.org/zh/人倫大統賦/卷上',
    witnessStatus: 'candidate',
  },
  {
    witnessId: 'witness.kohn_1986.jstor',
    workId: 'work.kohn_1986',
    editionLabel: 'Asian Folklore Studies 45(2), pp. 227–258',
    publicationYear: 1986,
    holdingInstitution: 'Nanzan University / JSTOR',
    digitalSourceUrl: 'https://www.jstor.org/stable/1178619',
    witnessStatus: 'verified',
  },
] as const satisfies readonly SourceWitness[];

export const FACE_RESEARCH_PASSAGES_V0 = [
  {
    passageId: 'passage.shenxiang.intro.scope',
    witnessId: 'witness.shenxiang_quanbian.ctext',
    chapter: '卷首 / 十觀前總論',
    originalText: '大凡觀人之相貌，先觀骨格，次看五行；量三停之長短，察面部之盈虧，觀眉目之清秀……取五官之有成，看六府之有就，取五岳之歸朝……俱依部位流年而推；骨格形局而斷。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.shenxiang.three_divisions.ten_observations',
    witnessId: 'witness.shenxiang_quanbian.ctext',
    chapter: '十觀 / 五看五岳及三停',
    originalText: '三停者，額門，准頭，地角，此面部三停也……俱要平等。上停長少年忙，中停長福祿昌，下停長老吉祥，三停平等，一生衣祿無虧。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.shenxiang.face_three_divisions',
    witnessId: 'witness.shenxiang_quanbian.ctext',
    chapter: '面三停',
    originalText: '面之三停者，自發際下至眉間為上停，自眉間下至鼻為中停，自准下人中至頦為下停。夫三停者，以象三才也。',
    normalizedText: '上停=髮際至眉；中停=眉至準頭；下停=準頭至頦/地閣。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.shenxiang.sancai_three_divisions',
    witnessId: 'witness.shenxiang_quanbian.ctext',
    chapter: '三才三停論',
    originalText: '三停者，髮際至印堂為上輔，是初主。自山根至准頭為中府，是中主。自人中至地閣為下輔，末至。自發際至眉為上停，眉至准頭為中停，准頭至地閣為下停。訣曰：上停長老吉昌，中停長近君王，下停長少吉祥。三停平等，富貴榮顯。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.mayi.sancai_three_divisions.boundaries',
    witnessId: 'witness.mayi_xiangfa.nlc_1925_v1',
    volume: '卷一',
    chapter: '三才三停',
    printedPage: '31',
    scanPage: 35,
    originalText: '三停者髮際至印堂為上停……自山根至準頭為中停……自人中至地閣為下停……自髮際至眉為上停。',
    normalizedText: '1925 NLC scan confirms a transmitted 三停 boundary formulation; ellipses mark omitted intervening print, not OCR uncertainty.',
    verificationStatus: 'scan_checked',
  },
  {
    passageId: 'passage.mayi.sancai_three_divisions.period',
    witnessId: 'witness.mayi_xiangfa.nlc_1925_v1',
    volume: '卷一',
    chapter: '三才三停',
    printedPage: '33',
    scanPage: 36,
    originalText: '上停長老吉昌，中停長近君王，下停長少吉祥，三停平等富貴榮顯，三停不均孤夭貧賤。',
    verificationStatus: 'scan_checked',
  },
  {
    passageId: 'passage.liuzhuang.three_divisions',
    witnessId: 'witness.liuzhuang_xiangfa.ctext',
    chapter: '永樂百問 / 三停有面有身何說',
    originalText: '面上三停，髮際到山根為上停，為初限。山根到准頭，為中停，為中限。人中到地閣，為下停，主末限。如上停短削，少年不利。中停低陷，一世不榮。下停若長，一生憂滯。大概上停中停俱長，下停宜短。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.renlun.five_officers_six_fus',
    witnessId: 'witness.renlun_datongfu.wikisource',
    volume: '卷上',
    originalText: '四瀆須宜深且闊，五嶽必要穹與隆。五官欲其明而正，六府欲其實而充。一官成十年貴顯，一府就十載富豐。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.liuzhuang.twelve_palaces.wealth',
    witnessId: 'witness.liuzhuang_xiangfa.ctext',
    chapter: '十二宮 / 二財帛宮',
    originalText: '鼻乃財星，位居土宿。截筒懸膽，千倉萬箱。聳直興隆，一生富貴。中正不偏，須知福祿滔滔。',
    verificationStatus: 'unverified_ocr',
  },
  {
    passageId: 'passage.liuzhuang.configuration_caution',
    witnessId: 'witness.liuzhuang_xiangfa.ctext',
    chapter: '相法總論',
    originalText: '不可以美而言好，莫以惡而言害，其中還有異處，不可定一理而推，更宜細審聲音，再察五官六府。',
    verificationStatus: 'unverified_ocr',
  },
] as const satisfies readonly SourcePassage[];

export const FACE_RESEARCH_LINEAGE_V0 = [
  {
    fromWorkId: 'work.shenxiang_quanbian',
    toWorkId: 'work.renlun_datongfu',
    relation: 'quotes',
    evidenceRefs: ['evidence.shenxiang_contents.renlun_datongfu'],
    confidence: 'high',
  },
  {
    fromWorkId: 'work.kohn_1986',
    toWorkId: 'work.shenxiang_quanbian',
    relation: 'same_tradition',
    evidenceRefs: ['doi:10.2307/1178619'],
    confidence: 'high',
  },
  {
    fromWorkId: 'work.mayi_xiangfa',
    toWorkId: 'work.shenxiang_quanbian',
    relation: 'same_tradition',
    evidenceRefs: ['passage.mayi.sancai_three_divisions.boundaries', 'passage.shenxiang.sancai_three_divisions'],
    confidence: 'medium',
  },
  {
    fromWorkId: 'work.liuzhuang_xiangfa',
    toWorkId: 'work.shenxiang_quanbian',
    relation: 'same_tradition',
    evidenceRefs: ['evidence.shared_systems.three_divisions_five_officers_twelve_palaces'],
    confidence: 'medium',
  },
] as const satisfies readonly SourceLineageRelation[];

export const FACE_METHOD_REFS_V0 = Object.freeze({
  shenxiangThreeDivisions: 'method.shenxiang.face_three_divisions@0.1.0',
  mayiThreeDivisions: 'method.mayi.face_three_divisions@0.1.0',
  liuzhuangThreeDivisions: 'method.liuzhuang.face_three_divisions@0.1.0',
  fiveOfficers: 'method.five_officers.research_v0@0.1.0',
  twelvePalaces: 'method.twelve_palaces.research_v0@0.1.0',
});

export const FACE_RESEARCH_METHODOLOGIES_V0 = [
  {
    methodologyId: 'method.shenxiang.face_three_divisions',
    version: '0.1.0',
    traditionalTerm: '面三停',
    scope: 'static_face',
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    description: '神相全編 계열의 상·중·하 삼정 경계를 별도 방법론으로 보존한다.',
    limitations: ['전자본문 대조 단계이며 scan_checked 이전이다.', '平等의 수치 허용오차는 원전이 제공하지 않는다.'],
    reviewStatus: 'research',
  },
  {
    methodologyId: 'method.mayi.face_three_divisions',
    version: '0.1.0',
    traditionalTerm: '三才三停',
    scope: 'static_face',
    sourceRefs: ['passage.mayi.sancai_three_divisions.boundaries', 'passage.mayi.sancai_three_divisions.period'],
    description: '1925 NLC scan에서 직접 확인한 麻衣相法 삼정 전승을 독립 witness methodology로 보존한다.',
    limitations: ['scan은 확인했지만 현대 landmark operationalization과 平等 tolerance는 별도 calibration이 필요하다.'],
    reviewStatus: 'reviewed',
  },
  {
    methodologyId: 'method.liuzhuang.face_three_divisions',
    version: '0.1.0',
    traditionalTerm: '面上三停',
    scope: 'static_face',
    sourceRefs: ['passage.liuzhuang.three_divisions'],
    description: '柳莊相法의 삼정 좌표계를 神相全編 좌표계와 합치지 않고 별도 방법론으로 보존한다.',
    limitations: ['전자본문은 상정=髮際→山根, 중정=山根→準頭, 하정=人中→地閣을 제시하지만 NLC scan은 아직 직접 대조하지 않았다.'],
    reviewStatus: 'research',
  },
  {
    methodologyId: 'method.five_officers.research_v0',
    version: '0.1.0',
    traditionalTerm: '五官六府',
    scope: 'static_face',
    sourceRefs: ['passage.renlun.five_officers_six_fus'],
    description: '오관·육부 연구 단위의 placeholder authority.',
    limitations: ['세부 부위 map은 아직 미구축이다.'],
    reviewStatus: 'research',
  },
  {
    methodologyId: 'method.twelve_palaces.research_v0',
    version: '0.1.0',
    traditionalTerm: '十二宮',
    scope: 'static_face',
    sourceRefs: ['passage.liuzhuang.twelve_palaces.wealth'],
    description: '십이궁 연구 단위의 placeholder authority.',
    limitations: ['최종 十二宮 region map은 아직 미구축이다.'],
    reviewStatus: 'research',
  },
] as const;

export const FACE_RESEARCH_CONFLICTS_V0 = [
  {
    conflictId: 'conflict.three_divisions.period_direction_v0',
    methodologyRefs: [
      FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
      FACE_METHOD_REFS_V0.mayiThreeDivisions,
      FACE_METHOD_REFS_V0.liuzhuangThreeDivisions,
    ],
    sourceRefs: [
      'passage.shenxiang.three_divisions.ten_observations',
      'passage.shenxiang.sancai_three_divisions',
      'passage.mayi.sancai_three_divisions.period',
      'passage.liuzhuang.three_divisions',
    ],
    affectedTiers: ['F6'],
    status: 'open',
    reason: '삼정의 長과 초·중·말년을 연결하는 문구가 전승/문맥별로 일관되지 않는다. 1925 麻衣相法 scan은 上停長老吉昌 계열을 실제로 확인하므로 단순 OCR 오류로 치부할 수 없다.',
  },
] as const;

export const FACE_THREE_DIVISION_REGION_MAPS_V0 = [
  {
    regionMapId: 'regionmap.shenxiang.face_three_divisions',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    coordinateFrame: 'normalized_face_landmark_frame',
    regions: [
      {
        regionKey: 'upper',
        label: '上停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'hairline_midpoint', toAnchor: 'brow_midline' },
        sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
      },
      {
        regionKey: 'middle',
        label: '中停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'brow_midline', toAnchor: 'nose_tip' },
        sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
      },
      {
        regionKey: 'lower',
        label: '下停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'nose_tip', toAnchor: 'chin_bottom' },
        sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
      },
    ],
    mappingStatus: 'research',
  },
  {
    regionMapId: 'regionmap.liuzhuang.face_three_divisions',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.liuzhuangThreeDivisions,
    sourceRefs: ['passage.liuzhuang.three_divisions'],
    coordinateFrame: 'normalized_face_landmark_frame',
    regions: [
      {
        regionKey: 'upper',
        label: '上停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'hairline_midpoint', toAnchor: 'shangen' },
        sourceRefs: ['passage.liuzhuang.three_divisions'],
      },
      {
        regionKey: 'middle',
        label: '中停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'shangen', toAnchor: 'nose_tip' },
        sourceRefs: ['passage.liuzhuang.three_divisions'],
      },
      {
        regionKey: 'lower',
        label: '下停',
        geometryDefinition: { kind: 'vertical_span', fromAnchor: 'renzhong', toAnchor: 'dige' },
        sourceRefs: ['passage.liuzhuang.three_divisions'],
      },
    ],
    mappingStatus: 'research',
  },
] as const;

export const FACE_THREE_DIVISION_METRICS_V0 = [
  {
    metricKey: 'metric.shenxiang.three_divisions.upper_length',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    regionMapRef: 'regionmap.shenxiang.face_three_divisions@0.1.0',
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    formula: 'abs(y(brow_midline)-y(hairline_midpoint))/normalized_face_height',
    requiredAnchorRefs: ['hairline_midpoint', 'brow_midline'],
    unit: 'normalized_distance',
    stabilityRequirements: ['frontal_static_view', 'hairline_visible', 'brow_midline_visible'],
    reviewStatus: 'research',
  },
  {
    metricKey: 'metric.shenxiang.three_divisions.middle_length',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    regionMapRef: 'regionmap.shenxiang.face_three_divisions@0.1.0',
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    formula: 'abs(y(nose_tip)-y(brow_midline))/normalized_face_height',
    requiredAnchorRefs: ['brow_midline', 'nose_tip'],
    unit: 'normalized_distance',
    stabilityRequirements: ['frontal_static_view', 'brow_midline_visible', 'nose_tip_visible'],
    reviewStatus: 'research',
  },
  {
    metricKey: 'metric.shenxiang.three_divisions.lower_length',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    regionMapRef: 'regionmap.shenxiang.face_three_divisions@0.1.0',
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    formula: 'abs(y(chin_bottom)-y(nose_tip))/normalized_face_height',
    requiredAnchorRefs: ['nose_tip', 'chin_bottom'],
    unit: 'normalized_distance',
    stabilityRequirements: ['frontal_static_view', 'nose_tip_visible', 'chin_visible'],
    reviewStatus: 'research',
  },
] as const;

export const FACE_THREE_DIVISION_OPERATIONALIZATIONS_V0 = [
  {
    operationalizationId: 'op.shenxiang.three_divisions.relative_order_v0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    traditionalTerm: '三停長短 / 三停平等',
    inputMetricRefs: [
      'metric.shenxiang.three_divisions.upper_length@0.1.0',
      'metric.shenxiang.three_divisions.middle_length@0.1.0',
      'metric.shenxiang.three_divisions.lower_length@0.1.0',
    ],
    classificationBands: {
      kind: 'strict_relative_order',
      classes: [
        'upper_longest',
        'middle_longest',
        'lower_longest',
        'upper_middle_tie_longest',
        'upper_lower_tie_longest',
        'middle_lower_tie_longest',
        'all_equal_exact',
      ],
      numericTolerance: null,
      nearEqualClassification: 'blocked_until_calibrated',
    },
    reviewStatus: 'research',
  },
] as const;

export const FACE_CLAIM_TYPES_V0 = [
  {
    claimType: 'FACE_MORPHOLOGY_CLASSIFICATION',
    valueSchemaRef: 'face-claim/morphology/v1',
    allowedTiers: ['F1'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
    comparisonGroups: ['morphology.salience'],
  },
  {
    claimType: 'FACE_LOCAL_INTERPRETATION',
    valueSchemaRef: 'face-claim/local/v1',
    allowedTiers: ['F2'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
    comparisonGroups: ['local.salience'],
  },
  {
    claimType: 'FACE_CONFIGURATION_INTERPRETATION',
    valueSchemaRef: 'face-claim/configuration/v1',
    allowedTiers: ['F3'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
  },
  {
    claimType: 'FACE_TENSION_INTERPRETATION',
    valueSchemaRef: 'face-claim/tension/v1',
    allowedTiers: ['F3', 'F7'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
  },
  {
    claimType: 'FACE_POSITION_PERIOD_INTERPRETATION',
    valueSchemaRef: 'face-claim/position-period/v1',
    allowedTiers: ['F6'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
    comparisonGroups: ['three_divisions.salience'],
  },
  {
    claimType: 'FACE_PALACE_STATUS',
    valueSchemaRef: 'face-claim/palace/v1',
    allowedTiers: ['F2', 'F3', 'F7'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
    comparisonGroups: ['twelve_palaces.salience'],
  },
  {
    claimType: 'FACE_DOMAIN_PATTERN',
    valueSchemaRef: 'face-claim/domain/v1',
    allowedTiers: ['F7'],
    materialForNarrative: true,
    dynamicAppearance: false,
    requiresMethodAttribution: true,
  },
] as const satisfies readonly FaceClaimTypeDefinition[];

export const FACE_THREE_DIVISION_RULES_V0 = [
  {
    ruleId: 'rule.shenxiang.three_divisions.upper_longest',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions'],
    tier: 'F1',
    inputs: [{ inputKey: 'threeDivisionRelation', sourceType: 'operationalization', ref: 'op.shenxiang.three_divisions.relative_order_v0', required: true }],
    condition: { op: 'eq', input: 'threeDivisionRelation', value: 'upper_longest' },
    output: { claimType: 'FACE_MORPHOLOGY_CLASSIFICATION', semanticKey: 'face.three_divisions.upper_longest', pattern: 'upper_longest' },
    rationale: '원전이 삼정의 長短을 구분하므로, 수치 임계값 없이 유일 최장 구간만 형태 분류로 보존한다.',
    limitations: ['운세·성격·수명 해석을 포함하지 않는다.', 'near-equal은 calibration 전까지 별도 판정하지 않는다.'],
    promotionStatus: 'research',
  },
  {
    ruleId: 'rule.shenxiang.three_divisions.middle_longest',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions'],
    tier: 'F1',
    inputs: [{ inputKey: 'threeDivisionRelation', sourceType: 'operationalization', ref: 'op.shenxiang.three_divisions.relative_order_v0', required: true }],
    condition: { op: 'eq', input: 'threeDivisionRelation', value: 'middle_longest' },
    output: { claimType: 'FACE_MORPHOLOGY_CLASSIFICATION', semanticKey: 'face.three_divisions.middle_longest', pattern: 'middle_longest' },
    rationale: '원전이 삼정의 長短을 구분하므로, 수치 임계값 없이 유일 최장 구간만 형태 분류로 보존한다.',
    limitations: ['운세·성격·수명 해석을 포함하지 않는다.', 'near-equal은 calibration 전까지 별도 판정하지 않는다.'],
    promotionStatus: 'research',
  },
  {
    ruleId: 'rule.shenxiang.three_divisions.lower_longest',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions'],
    tier: 'F1',
    inputs: [{ inputKey: 'threeDivisionRelation', sourceType: 'operationalization', ref: 'op.shenxiang.three_divisions.relative_order_v0', required: true }],
    condition: { op: 'eq', input: 'threeDivisionRelation', value: 'lower_longest' },
    output: { claimType: 'FACE_MORPHOLOGY_CLASSIFICATION', semanticKey: 'face.three_divisions.lower_longest', pattern: 'lower_longest' },
    rationale: '원전이 삼정의 長短을 구분하므로, 수치 임계값 없이 유일 최장 구간만 형태 분류로 보존한다.',
    limitations: ['운세·성격·수명 해석을 포함하지 않는다.', 'near-equal은 calibration 전까지 별도 판정하지 않는다.'],
    promotionStatus: 'research',
  },
  {
    ruleId: 'rule.shenxiang.three_divisions.exact_equal',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions', 'passage.shenxiang.sancai_three_divisions'],
    tier: 'F1',
    inputs: [{ inputKey: 'threeDivisionRelation', sourceType: 'operationalization', ref: 'op.shenxiang.three_divisions.relative_order_v0', required: true }],
    condition: { op: 'eq', input: 'threeDivisionRelation', value: 'all_equal_exact' },
    output: { claimType: 'FACE_MORPHOLOGY_CLASSIFICATION', semanticKey: 'face.three_divisions.exact_equal_measurement', pattern: 'exact_equal_measurement' },
    rationale: '平等이라는 원전 표현을 임의의 허용오차로 바꾸지 않고 정확한 측정 동률만 별도 표식한다.',
    limitations: ['전통적 平等의 실무 허용오차와 동일하다는 뜻이 아니다.', 'production balance classification은 calibration authority가 필요하다.'],
    promotionStatus: 'research',
  },
  {
    ruleId: 'rule.shenxiang.three_divisions.no_unique_longest',
    version: '0.1.0',
    methodologyRef: FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    sourceRefs: ['passage.shenxiang.face_three_divisions'],
    tier: 'F1',
    inputs: [{ inputKey: 'threeDivisionRelation', sourceType: 'operationalization', ref: 'op.shenxiang.three_divisions.relative_order_v0', required: true }],
    condition: { op: 'in', input: 'threeDivisionRelation', values: ['upper_middle_tie_longest', 'upper_lower_tie_longest', 'middle_lower_tie_longest'] },
    output: { claimType: 'FACE_MORPHOLOGY_CLASSIFICATION', semanticKey: 'face.three_divisions.no_unique_longest', pattern: 'no_unique_longest' },
    rationale: '동률일 때 임의로 하나의 중심 구간을 선택하지 않는다.',
    limitations: ['near-equal을 동률로 간주하지 않는다.'],
    promotionStatus: 'research',
  },
] as const;

export const FACE_COMPARISON_POLICY_V0: FaceComparisonPolicy = {
  policyId: 'comparison.face.research_v0',
  version: '0.1.0',
  groups: [
    {
      groupKey: 'morphology.salience',
      eligibleClaimTypes: ['FACE_MORPHOLOGY_CLASSIFICATION'],
      comparisonMode: 'diagnostic_salience',
    },
    {
      groupKey: 'local.salience',
      eligibleClaimTypes: ['FACE_LOCAL_INTERPRETATION'],
      comparisonMode: 'diagnostic_salience',
    },
    {
      groupKey: 'three_divisions.salience',
      eligibleClaimTypes: ['FACE_POSITION_PERIOD_INTERPRETATION'],
      comparisonMode: 'diagnostic_salience',
      sourceRefs: ['passage.shenxiang.three_divisions.ten_observations'],
    },
    {
      groupKey: 'twelve_palaces.salience',
      eligibleClaimTypes: ['FACE_PALACE_STATUS'],
      comparisonMode: 'diagnostic_salience',
    },
  ],
};

export const FACE_RESEARCH_PACK_V0: FaceMethodologyPackDefinition = {
  packId: 'pack.face.research_v0',
  version: '0.2.0',
  sourceWitnessSetRef: 'witness-set.face.research_v0',
  methodologyDefinitionRefs: [
    FACE_METHOD_REFS_V0.shenxiangThreeDivisions,
    FACE_METHOD_REFS_V0.mayiThreeDivisions,
    FACE_METHOD_REFS_V0.liuzhuangThreeDivisions,
    FACE_METHOD_REFS_V0.fiveOfficers,
    FACE_METHOD_REFS_V0.twelvePalaces,
  ],
  regionMapRefs: [
    'regionmap.shenxiang.face_three_divisions@0.1.0',
    'regionmap.liuzhuang.face_three_divisions@0.1.0',
  ],
  metricRegistryRef: 'metrics.face.research_v0',
  operationalizationRegistryRef: 'operationalizations.face.research_v0',
  claimTypeRegistryRef: 'claim-types.face.research_v0',
  ruleRegistryRef: 'rules.face.research_v0',
  comparisonPolicyRef: `${FACE_COMPARISON_POLICY_V0.policyId}@${FACE_COMPARISON_POLICY_V0.version}`,
  enabledTiers: ['F0', 'F1', 'F2', 'F3', 'F6', 'F7'],
  forbiddenObservationInputs: ['observations.colorAppearance'],
};

export const FACE_AUTHORITY_RESEARCH_REGISTRY_V0: FaceAuthorityRegistry = {
  works: FACE_RESEARCH_WORKS_V0,
  witnesses: FACE_RESEARCH_WITNESSES_V0,
  passages: FACE_RESEARCH_PASSAGES_V0,
  lineage: FACE_RESEARCH_LINEAGE_V0,
  methodologies: FACE_RESEARCH_METHODOLOGIES_V0,
  conflicts: FACE_RESEARCH_CONFLICTS_V0,
  regionMaps: FACE_THREE_DIVISION_REGION_MAPS_V0,
  metrics: FACE_THREE_DIVISION_METRICS_V0,
  operationalizations: FACE_THREE_DIVISION_OPERATIONALIZATIONS_V0,
  claimTypes: FACE_CLAIM_TYPES_V0,
  rules: FACE_THREE_DIVISION_RULES_V0,
  comparisonPolicies: [FACE_COMPARISON_POLICY_V0],
  methodologyPacks: [FACE_RESEARCH_PACK_V0],
};
