import {
  FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS,
  type TraditionalFiveOfficerMethodologyRefT4,
} from './traditional-five-officers-methodology-t4.js';

export type TraditionalFiveOfficerOperationalizationModalityT5 =
  | 'static_geometry'
  | 'spatial_relation'
  | 'controlled_appearance'
  | 'controlled_multi_state'
  | 'figurative_form_research'
  | 'historical_measure_research'
  | 'semantic_region_definition';

export type TraditionalFiveOfficerOperationalizationStatusT5 =
  | 'blocked_pending_observation_contract_and_binding'
  | 'blocked_pending_capture_protocol_and_binding'
  | 'blocked_pending_multi_state_protocol_and_binding'
  | 'blocked_pending_source_grounded_construct_definition'
  | 'blocked_pending_historical_measure_interpretation'
  | 'blocked_pending_semantic_region_definition';

export interface TraditionalFiveOfficerOperationalizationSpecificationT5 {
  readonly specificationId: string;
  readonly t4CriterionRef: string;
  readonly methodologyRef: TraditionalFiveOfficerMethodologyRefT4;
  readonly traditionalOfficerName:
    | '採聽官'
    | '保壽官'
    | '監察官'
    | '審辨官'
    | '出納官';
  readonly sourceExpression: string;
  readonly modality: TraditionalFiveOfficerOperationalizationModalityT5;
  readonly observationContractIntent: string;
  readonly requiredNeutralCapabilities: readonly string[];
  readonly capturePrerequisites: readonly string[];
  readonly prohibitedProxyClasses: readonly string[];
  readonly constructValidityStatus: 'not_established';
  readonly operationalizationStatus: TraditionalFiveOfficerOperationalizationStatusT5;
  readonly concreteCoordinateOrFormulaAuthorized: false;
  readonly traditionalMetricBindingAuthorized: false;
  readonly calibrationAuthorized: false;
  readonly thresholdAuthorized: false;
  readonly automaticCriterionStateAuthorized: false;
}

export interface TraditionalFiveOfficerFormationOperationalizationT5 {
  readonly specificationId: string;
  readonly methodologyRef: TraditionalFiveOfficerMethodologyRefT4;
  readonly traditionalOfficerName:
    | '採聽官'
    | '保壽官'
    | '監察官'
    | '審辨官'
    | '出納官';
  readonly inputOperationalizationRefs: readonly string[];
  readonly sourceAggregateSemantics:
    'listed_descriptors_leading_to_formation_label';
  readonly executableBooleanAndAuthorized: false;
  readonly executableBooleanOrAuthorized: false;
  readonly criterionWeightingAuthorized: false;
  readonly partialSatisfactionPolicyAuthorized: false;
  readonly negativeCountercriterionPolicyAuthorized: false;
  readonly executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration';
}

export interface TraditionalFiveOfficerBindingPrerequisiteT5 {
  readonly prerequisiteId: string;
  readonly traditionalExpressions: readonly string[];
  readonly requiredCapability: string;
  readonly observationOwner: 'face-observation-engine' | 'face-reading-binding';
  readonly bindingOwner: 'face-reading-binding';
  readonly status: 'blocked';
  readonly prohibitedInference: readonly string[];
}

export const FACE_TRADITIONAL_T5_FIVE_OFFICER_OPERATIONALIZATION_SPECS = [
  {
    specificationId: 't5.op.listening.color_fresh',
    t4CriterionRef: 't4.listening.color_fresh',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    sourceExpression: '色鮮',
    modality: 'controlled_appearance',
    observationContractIntent:
      '귀의 visible appearance를 capture conditions와 함께 중립적으로 기술할 수 있어야 한다.',
    requiredNeutralCapabilities: ['visible_ear_region', 'appearance_observation_without_traditional_label'],
    capturePrerequisites: ['controlled_illumination', 'white_balance_or_equivalent_color_control'],
    prohibitedProxyClasses: ['raw_rgb_mean', 'skin_tone_class', 'health_or_ethnicity_inference'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.listening.high_relative_to_brow',
    t4CriterionRef: 't4.listening.high_relative_to_brow',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    sourceExpression: '高聳於眉',
    modality: 'spatial_relation',
    observationContractIntent:
      '귀와 眉 사이의 vertical relation을 전통 의미 부여 전 중립 reference들로 표현할 수 있어야 한다.',
    requiredNeutralCapabilities: ['governed_visible_ear_vertical_reference', 'governed_brow_vertical_reference'],
    capturePrerequisites: ['pose_control_sufficient_for_vertical_relation'],
    prohibitedProxyClasses: ['ear_center_vs_brow_center_without_authority', 'generic_face_height_ratio'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.listening.contour_complete',
    t4CriterionRef: 't4.listening.contour_complete',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    sourceExpression: '輪廓完成',
    modality: 'semantic_region_definition',
    observationContractIntent:
      '輪/廓/完成의 source-grounded semantic structure를 먼저 정의한 뒤 neutral ear contour evidence와 결합해야 한다.',
    requiredNeutralCapabilities: ['visible_ear_contour_structure'],
    capturePrerequisites: ['ear_visibility_without_occlusion'],
    prohibitedProxyClasses: ['single_contour_completeness_score', 'modern_ear_subregion_alias_without_source_authority'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_semantic_region_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.listening.close_fleshy_substantial',
    t4CriterionRef: 't4.listening.close_fleshy_substantial',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    sourceExpression: '貼肉敦厚',
    modality: 'static_geometry',
    observationContractIntent:
      '귀의 visible attachment/projection 및 fullness 후보를 서로 분리된 중립 관찰로 표현해야 한다.',
    requiredNeutralCapabilities: ['ear_attachment_or_projection_candidate', 'visible_ear_fullness_candidate'],
    capturePrerequisites: ['pose_control', 'ear_visibility_without_occlusion'],
    prohibitedProxyClasses: ['single_selfie_depth_claim', 'pixel_thickness_as_tissue_thickness'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.listening.fengmen_broad',
    t4CriterionRef: 't4.listening.fengmen_broad',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    sourceExpression: '風門寬大',
    modality: 'semantic_region_definition',
    observationContractIntent:
      '風門의 source-grounded region identity를 확정하기 전에는 寬大 측정을 정의하지 않는다.',
    requiredNeutralCapabilities: ['candidate_ear_internal_opening_geometry_only_after_region_binding'],
    capturePrerequisites: ['ear_visibility_without_occlusion'],
    prohibitedProxyClasses: ['ear_canal_proxy', 'concha_width_proxy', 'generic_internal_ear_width'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_semantic_region_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },

  {
    specificationId: 't5.op.longevity.broad_clear_long',
    t4CriterionRef: 't4.longevity.broad_clear_long',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    sourceExpression: '寬廣清長',
    modality: 'static_geometry',
    observationContractIntent:
      '眉의 visible extent와 clarity 후보를 분리해서 관찰하되 복합 source construct를 유지한다.',
    requiredNeutralCapabilities: ['bilateral_brow_extent', 'brow_density_or_boundary_clarity_candidate'],
    capturePrerequisites: ['neutral_expression', 'brow_visibility'],
    prohibitedProxyClasses: ['brow_length_only', 'brow_area_only', 'cosmetic_density_as_traditional_qing'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.longevity.both_extend_into_temples',
    t4CriterionRef: 't4.longevity.both_extend_into_temples',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    sourceExpression: '雙分入鬢',
    modality: 'spatial_relation',
    observationContractIntent:
      '양쪽 眉 외측과 鬢의 관계를 평가하기 위한 neutral temporal-hair region과 brow-tail reference가 필요하다.',
    requiredNeutralCapabilities: ['bilateral_brow_tail_reference', 'governed_temporal_hair_region_candidate'],
    capturePrerequisites: ['frontal_or_governed_pose', 'temporal_hair_visibility'],
    prohibitedProxyClasses: ['brow_tail_x_coordinate_only', 'generic_face_width_boundary_as_bin'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.longevity.suspended_rhino_new_moon_analogy',
    t4CriterionRef: 't4.longevity.suspended_rhino_new_moon_analogy',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    sourceExpression: '或如懸犀新月之樣',
    modality: 'figurative_form_research',
    observationContractIntent:
      '懸犀/新月 비유의 source-grounded visual construct를 별도 연구한 뒤 neutral brow form과 비교해야 한다.',
    requiredNeutralCapabilities: ['brow_centerline_or_contour_shape_without_traditional_label'],
    capturePrerequisites: ['neutral_expression', 'brow_visibility'],
    prohibitedProxyClasses: ['single_curvature_value', 'arch_height_only', 'template_similarity_without_source_construct'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_source_grounded_construct_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.longevity.ends_full',
    t4CriterionRef: 't4.longevity.ends_full',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    sourceExpression: '首尾豐盈',
    modality: 'static_geometry',
    observationContractIntent:
      '眉의 medial/lateral end roles와 visible fullness 후보를 중립적으로 정의해야 한다.',
    requiredNeutralCapabilities: ['governed_brow_medial_end', 'governed_brow_lateral_end', 'local_brow_fullness_candidate'],
    capturePrerequisites: ['brow_visibility'],
    prohibitedProxyClasses: ['global_brow_density_only', 'tail_thickness_only'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.longevity.high_in_forehead_center',
    t4CriterionRef: 't4.longevity.high_in_forehead_center',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    sourceExpression: '高居額中',
    modality: 'spatial_relation',
    observationContractIntent:
      '眉의 위치와 額中 source region 사이의 relation을 위한 governed region binding이 필요하다.',
    requiredNeutralCapabilities: ['governed_brow_vertical_reference', 'neutral_forehead_region_candidate'],
    capturePrerequisites: ['forehead_visibility', 'pose_control'],
    prohibitedProxyClasses: ['forehead_height_ratio', 'brow_y_coordinate_without_ezhong_binding'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },

  {
    specificationId: 't5.op.inspection.concealed_not_exposed',
    t4CriterionRef: 't4.inspection.concealed_not_exposed',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    sourceExpression: '含藏不露',
    modality: 'controlled_appearance',
    observationContractIntent:
      'controlled gaze/expression에서 visible eye exposure를 중립적으로 기술하고 source construct와 별도 binding해야 한다.',
    requiredNeutralCapabilities: ['visible_eye_exposure_candidate', 'gaze_state_observation'],
    capturePrerequisites: ['neutral_expression', 'controlled_gaze', 'no_blink'],
    prohibitedProxyClasses: ['eye_opening_ratio_as_direct_hancang', 'single_frame_blink_state'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.inspection.black_white_distinct',
    t4CriterionRef: 't4.inspection.black_white_distinct',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    sourceExpression: '黑白分明',
    modality: 'controlled_appearance',
    observationContractIntent:
      '눈 영역의 visible dark/light separation 후보를 capture-controlled appearance로만 관찰한다.',
    requiredNeutralCapabilities: ['eye_region_appearance_contrast_candidate'],
    capturePrerequisites: ['controlled_illumination', 'exposure_control', 'white_balance_control'],
    prohibitedProxyClasses: ['raw_pixel_contrast', 'medical_eye_state', 'race_or_ethnicity_inference'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.inspection.pupil_settled',
    t4CriterionRef: 't4.inspection.pupil_settled',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    sourceExpression: '瞳子端定',
    modality: 'controlled_appearance',
    observationContractIntent:
      'controlled gaze에서 visible pupil/iris alignment 후보를 기록하되 端定 의미와 동일시하지 않는다.',
    requiredNeutralCapabilities: ['visible_iris_or_pupil_alignment_candidate', 'gaze_state_observation'],
    capturePrerequisites: ['controlled_gaze', 'frontal_pose', 'sufficient_eye_resolution'],
    prohibitedProxyClasses: ['gaze_center_offset_as_direct_duanding', 'medical_strabismus_inference'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.inspection.radiant_lustre',
    t4CriterionRef: 't4.inspection.radiant_lustre',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    sourceExpression: '光彩射人',
    modality: 'controlled_appearance',
    observationContractIntent:
      '눈의 visible lustre 후보와 capture specular artefact를 분리할 수 있는 연구 계약이 필요하다.',
    requiredNeutralCapabilities: ['eye_region_lustre_candidate', 'specular_highlight_observation'],
    capturePrerequisites: ['controlled_illumination', 'camera_exposure_metadata_or_equivalent_control'],
    prohibitedProxyClasses: ['specular_highlight_count_as_guangcai', 'brightness_mean'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.inspection.slender_long_historical_measure',
    t4CriterionRef: 't4.inspection.slender_long_historical_measure',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    sourceExpression: '或細長極寸',
    modality: 'historical_measure_research',
    observationContractIntent:
      '細長의 form semantics와 極寸의 historical measure semantics를 먼저 source-grounded하게 해석해야 한다.',
    requiredNeutralCapabilities: ['visible_eye_shape_candidate_only_after_measure_semantics'],
    capturePrerequisites: ['controlled_pose'],
    prohibitedProxyClasses: ['millimetre_conversion', 'pixel_length', 'face_width_percentage', 'fixed_aspect_ratio'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_historical_measure_interpretation',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },

  {
    specificationId: 't5.op.discernment.bridge_column_straight',
    t4CriterionRef: 't4.discernment.bridge_column_straight',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '梁柱端直',
    modality: 'static_geometry',
    observationContractIntent:
      'neutral nasal bridge/column geometry 후보를 관찰하되 梁柱/端直 traditional binding은 별도 authority로 둔다.',
    requiredNeutralCapabilities: ['neutral_nasal_bridge_axis_or_shape_candidate'],
    capturePrerequisites: ['pose_control'],
    prohibitedProxyClasses: ['FR287_or_FR297_direct_traditional_alias', 'centerline_deviation_as_direct_duanzhi'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.yintang_level_broad',
    t4CriterionRef: 't4.discernment.yintang_level_broad',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '印堂平闊',
    modality: 'semantic_region_definition',
    observationContractIntent:
      '印堂의 governed traditional region identity를 먼저 확정한 뒤 平/闊 후보를 operationalize해야 한다.',
    requiredNeutralCapabilities: ['neutral_interbrow_region_candidate'],
    capturePrerequisites: ['frontal_pose', 'interbrow_visibility'],
    prohibitedProxyClasses: ['generic_interbrow_midpoint', 'interbrow_distance_as_direct_yintang_width'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_semantic_region_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.shangen_connects_yintang',
    t4CriterionRef: 't4.discernment.shangen_connects_yintang',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '山根連印',
    modality: 'spatial_relation',
    observationContractIntent:
      '山根/印堂 각각의 governed binding 이후 두 source-local regions 사이의 connection relation을 정의해야 한다.',
    requiredNeutralCapabilities: ['neutral_nasal_bridge_root_reference_candidate', 'neutral_interbrow_region_candidate'],
    capturePrerequisites: ['frontal_pose'],
    prohibitedProxyClasses: ['FR297_equals_shangen', 'nearest_distance_only', 'visual_continuity_without_region_authority'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.nianshou_high_prominent',
    t4CriterionRef: 't4.discernment.nianshou_high_prominent',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '年壽高隆',
    modality: 'semantic_region_definition',
    observationContractIntent:
      '年壽 region identity를 source-grounded하게 정의한 뒤 neutral prominence 후보와 binding해야 한다.',
    requiredNeutralCapabilities: ['neutral_nasal_bridge_subregion_geometry_candidate'],
    capturePrerequisites: ['pose_control', 'sufficient_nose_visibility'],
    prohibitedProxyClasses: ['generic_bridge_midpoint', '2d_height_as_3d_prominence'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_semantic_region_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.zhuntou_round_ku_raised',
    t4CriterionRef: 't4.discernment.zhuntou_round_ku_raised',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '準圓庫起',
    modality: 'semantic_region_definition',
    observationContractIntent:
      '準/庫의 source-local region identities를 먼저 확정하고 圓/起를 서로 다른 neutral morphology 후보로 다뤄야 한다.',
    requiredNeutralCapabilities: ['neutral_nose_tip_shape_candidate', 'neutral_adjacent_nasal_region_prominence_candidate'],
    capturePrerequisites: ['pose_control', 'sufficient_nose_visibility'],
    prohibitedProxyClasses: ['tip_circularity_equals_zhun_round', 'FR298_projection_equals_ku_rise'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_semantic_region_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.suspended_gallbladder_form',
    t4CriterionRef: 't4.discernment.suspended_gallbladder_form',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '形如懸膽',
    modality: 'figurative_form_research',
    observationContractIntent:
      '懸膽 비유의 source-grounded form construct를 별도 연구한 뒤 neutral nose morphology와 비교해야 한다.',
    requiredNeutralCapabilities: ['neutral_nose_outline_and_projection_candidates'],
    capturePrerequisites: ['pose_control'],
    prohibitedProxyClasses: ['tip_circularity_only', 'template_similarity_without_source_construct'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_source_grounded_construct_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.cut_tube_form',
    t4CriterionRef: 't4.discernment.cut_tube_form',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '齊如截筒',
    modality: 'figurative_form_research',
    observationContractIntent:
      '截筒 비유의 source-grounded form construct를 별도 연구한 뒤 neutral nose morphology와 비교해야 한다.',
    requiredNeutralCapabilities: ['neutral_nose_outline_and_axis_candidates'],
    capturePrerequisites: ['pose_control'],
    prohibitedProxyClasses: ['rectilinearity_only', 'bridge_width_uniformity_only', 'template_similarity_without_source_construct'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_source_grounded_construct_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.discernment.fresh_yellow_bright',
    t4CriterionRef: 't4.discernment.fresh_yellow_bright',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    sourceExpression: '色鮮黃明',
    modality: 'controlled_appearance',
    observationContractIntent:
      '鼻 region의 visible color/brightness 후보를 controlled capture에서만 연구하고 traditional meaning과 분리한다.',
    requiredNeutralCapabilities: ['nose_region_appearance_candidate'],
    capturePrerequisites: ['controlled_illumination', 'white_balance_control', 'exposure_control'],
    prohibitedProxyClasses: ['raw_hue_threshold', 'skin_tone_class', 'health_or_ethnicity_inference'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },

  {
    specificationId: 't5.op.intake.square_broad',
    t4CriterionRef: 'criterion.intake.square_broad',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    sourceExpression: '方大',
    modality: 'static_geometry',
    observationContractIntent:
      'FR132 경계에 따라 方의 form과 大의 relative-size 후보를 분리하되 compound construct를 유지한다.',
    requiredNeutralCapabilities: ['neutral_mouth_outline_form_candidate', 'anatomically_governed_relative_mouth_size_candidate'],
    capturePrerequisites: ['neutral_expression', 'closed_or_governed_mouth_state'],
    prohibitedProxyClasses: [
      'neutral.mouth.contour_set.bounding_box_aspect_ratio@0.1.0_as_direct_fang',
      'neutral.mouth.contour_set.horizontal_span_to_full_mesh_horizontal_span_ratio@0.1.0_as_direct_da',
    ],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.intake.lips_substantial',
    t4CriterionRef: 'criterion.intake.lips_substantial',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    sourceExpression: '端厚',
    modality: 'static_geometry',
    observationContractIntent:
      'FR132 경계에 따라 厚의 fullness/thickness 후보와 unresolved 端 semantics를 분리한다.',
    requiredNeutralCapabilities: ['governed_visible_lip_fullness_candidate', 'source_grounded_duan_semantics'],
    capturePrerequisites: ['neutral_expression', 'governed_lip_parting_state'],
    prohibitedProxyClasses: ['symmetric_arclength_mean_nearest_set_distance_as_direct_lip_thickness', 'thickness_only_as_duanhou'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_observation_contract_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.intake.corners_arched',
    t4CriterionRef: 'criterion.intake.corners_arched',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    sourceExpression: '角弓',
    modality: 'figurative_form_research',
    observationContractIntent:
      'FR132 경계에 따라 corner orientation/bow-like contour/teeth visibility 후보를 연구하되 generic curvature로 축약하지 않는다.',
    requiredNeutralCapabilities: ['mouth_corner_orientation_candidate', 'mouth_contour_form_candidate', 'teeth_visibility_candidate'],
    capturePrerequisites: ['neutral_expression', 'controlled_lip_parting'],
    prohibitedProxyClasses: ['corner_curvature_only', 'smile_score', 'single_template_match'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_source_grounded_construct_definition',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.intake.open_close_relation',
    t4CriterionRef: 'criterion.intake.open_close_relation',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    sourceExpression: '開大合小',
    modality: 'controlled_multi_state',
    observationContractIntent:
      '동일 subject의 controlled open/closed states를 별도 관찰한 뒤 source relation과 binding해야 한다.',
    requiredNeutralCapabilities: ['controlled_open_mouth_state', 'controlled_closed_mouth_state', 'same_subject_state_comparison'],
    capturePrerequisites: ['multi_state_capture_protocol', 'pose_consistency', 'expression_control'],
    prohibitedProxyClasses: ['single_frame_mouth_opening', 'speech_frame', 'cross_subject_comparison'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_multi_state_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
  {
    specificationId: 't5.op.intake.red_lip_color',
    t4CriterionRef: 'criterion.intake.red_lip_color',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    sourceExpression: '唇紅',
    modality: 'controlled_appearance',
    observationContractIntent:
      'FR132 경계에 따라 color-calibrated lip appearance가 없으면 fail closed한다.',
    requiredNeutralCapabilities: ['visible_lip_region', 'controlled_lip_color_candidate'],
    capturePrerequisites: ['controlled_illumination', 'white_balance_control', 'exposure_control'],
    prohibitedProxyClasses: ['raw_red_channel', 'skin_tone_relative_guess', 'health_or_ethnicity_inference'],
    constructValidityStatus: 'not_established',
    operationalizationStatus: 'blocked_pending_capture_protocol_and_binding',
    concreteCoordinateOrFormulaAuthorized: false,
    traditionalMetricBindingAuthorized: false,
    calibrationAuthorized: false,
    thresholdAuthorized: false,
    automaticCriterionStateAuthorized: false,
  },
] as const satisfies readonly TraditionalFiveOfficerOperationalizationSpecificationT5[];

export const FACE_TRADITIONAL_T5_FIVE_OFFICER_FORMATION_SPECS = [
  {
    specificationId: 't5.formation.listening',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    traditionalOfficerName: '採聽官',
    inputOperationalizationRefs: [
      't5.op.listening.color_fresh',
      't5.op.listening.high_relative_to_brow',
      't5.op.listening.contour_complete',
      't5.op.listening.close_fleshy_substantial',
      't5.op.listening.fengmen_broad',
    ],
    sourceAggregateSemantics: 'listed_descriptors_leading_to_formation_label',
    executableBooleanAndAuthorized: false,
    executableBooleanOrAuthorized: false,
    criterionWeightingAuthorized: false,
    partialSatisfactionPolicyAuthorized: false,
    negativeCountercriterionPolicyAuthorized: false,
    executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration',
  },
  {
    specificationId: 't5.formation.longevity',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    traditionalOfficerName: '保壽官',
    inputOperationalizationRefs: [
      't5.op.longevity.broad_clear_long',
      't5.op.longevity.both_extend_into_temples',
      't5.op.longevity.suspended_rhino_new_moon_analogy',
      't5.op.longevity.ends_full',
      't5.op.longevity.high_in_forehead_center',
    ],
    sourceAggregateSemantics: 'listed_descriptors_leading_to_formation_label',
    executableBooleanAndAuthorized: false,
    executableBooleanOrAuthorized: false,
    criterionWeightingAuthorized: false,
    partialSatisfactionPolicyAuthorized: false,
    negativeCountercriterionPolicyAuthorized: false,
    executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration',
  },
  {
    specificationId: 't5.formation.inspection',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    traditionalOfficerName: '監察官',
    inputOperationalizationRefs: [
      't5.op.inspection.concealed_not_exposed',
      't5.op.inspection.black_white_distinct',
      't5.op.inspection.pupil_settled',
      't5.op.inspection.radiant_lustre',
      't5.op.inspection.slender_long_historical_measure',
    ],
    sourceAggregateSemantics: 'listed_descriptors_leading_to_formation_label',
    executableBooleanAndAuthorized: false,
    executableBooleanOrAuthorized: false,
    criterionWeightingAuthorized: false,
    partialSatisfactionPolicyAuthorized: false,
    negativeCountercriterionPolicyAuthorized: false,
    executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration',
  },
  {
    specificationId: 't5.formation.discernment',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    traditionalOfficerName: '審辨官',
    inputOperationalizationRefs: [
      't5.op.discernment.bridge_column_straight',
      't5.op.discernment.yintang_level_broad',
      't5.op.discernment.shangen_connects_yintang',
      't5.op.discernment.nianshou_high_prominent',
      't5.op.discernment.zhuntou_round_ku_raised',
      't5.op.discernment.suspended_gallbladder_form',
      't5.op.discernment.cut_tube_form',
      't5.op.discernment.fresh_yellow_bright',
    ],
    sourceAggregateSemantics: 'listed_descriptors_leading_to_formation_label',
    executableBooleanAndAuthorized: false,
    executableBooleanOrAuthorized: false,
    criterionWeightingAuthorized: false,
    partialSatisfactionPolicyAuthorized: false,
    negativeCountercriterionPolicyAuthorized: false,
    executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration',
  },
  {
    specificationId: 't5.formation.intake',
    methodologyRef: FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
    traditionalOfficerName: '出納官',
    inputOperationalizationRefs: [
      't5.op.intake.square_broad',
      't5.op.intake.red_lip_color',
      't5.op.intake.lips_substantial',
      't5.op.intake.corners_arched',
      't5.op.intake.open_close_relation',
    ],
    sourceAggregateSemantics: 'listed_descriptors_leading_to_formation_label',
    executableBooleanAndAuthorized: false,
    executableBooleanOrAuthorized: false,
    criterionWeightingAuthorized: false,
    partialSatisfactionPolicyAuthorized: false,
    negativeCountercriterionPolicyAuthorized: false,
    executableFormationStatus: 'blocked_pending_semantics_binding_and_calibration',
  },
] as const satisfies readonly TraditionalFiveOfficerFormationOperationalizationT5[];

export const FACE_TRADITIONAL_T5_FIVE_OFFICER_BINDING_PREREQUISITES = [
  {
    prerequisiteId: 't5.binding.ear_semantics',
    traditionalExpressions: ['輪廓', '貼肉敦厚', '風門'],
    requiredCapability: 'source-grounded ear semantic regions/relations plus neutral observable counterparts',
    observationOwner: 'face-reading-binding',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['modern ear anatomy label => traditional term', 'single 2D metric => depth/fullness construct'],
  },
  {
    prerequisiteId: 't5.binding.brow_relations',
    traditionalExpressions: ['入鬢', '額中', '首尾', '懸犀', '新月'],
    requiredCapability: 'governed brow roles, adjacent neutral regions, and source-grounded figurative constructs',
    observationOwner: 'face-reading-binding',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['generic temple => 鬢', 'forehead center => 額中 without methodology binding', 'curvature => 新月'],
  },
  {
    prerequisiteId: 't5.binding.eye_capture',
    traditionalExpressions: ['含藏不露', '黑白分明', '瞳子端定', '光彩射人'],
    requiredCapability: 'controlled eye-state and appearance capture contract',
    observationOwner: 'face-observation-engine',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['single uncontrolled selfie => traditional eye criterion', 'medical state inference'],
  },
  {
    prerequisiteId: 't5.binding.eye_historical_measure',
    traditionalExpressions: ['細長極寸'],
    requiredCapability: 'source-grounded interpretation of historical 寸 expression before any metric design',
    observationOwner: 'face-reading-binding',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['寸 => mm', '寸 => pixel', '寸 => normalized face ratio'],
  },
  {
    prerequisiteId: 't5.binding.nose_named_regions',
    traditionalExpressions: ['梁柱', '印堂', '山根', '年壽', '準', '庫'],
    requiredCapability: 'methodology-specific traditional region identities mapped to governed neutral observations',
    observationOwner: 'face-reading-binding',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['FR297 => 山根', 'FR298 => 準/庫', 'generic bridge/tip labels => traditional region authority'],
  },
  {
    prerequisiteId: 't5.binding.nose_figurative_forms',
    traditionalExpressions: ['懸膽', '截筒'],
    requiredCapability: 'source-grounded figurative form definitions before neutral shape comparison',
    observationOwner: 'face-reading-binding',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['single shape metric => figurative form', 'template match => source construct'],
  },
  {
    prerequisiteId: 't5.binding.appearance_color',
    traditionalExpressions: ['色鮮', '色鮮黃明', '唇紅'],
    requiredCapability: 'capture-controlled appearance evidence separated from sensitive-attribute inference',
    observationOwner: 'face-observation-engine',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['raw RGB => traditional color criterion', 'appearance => health/race/ethnicity'],
  },
  {
    prerequisiteId: 't5.binding.intake_dynamic',
    traditionalExpressions: ['開大合小'],
    requiredCapability: 'same-subject controlled open/closed mouth state protocol',
    observationOwner: 'face-observation-engine',
    bindingOwner: 'face-reading-binding',
    status: 'blocked',
    prohibitedInference: ['single frame => multi-state relation', 'speech frame => controlled open state'],
  },
] as const satisfies readonly TraditionalFiveOfficerBindingPrerequisiteT5[];

export const FACE_TRADITIONAL_T5_FIVE_OFFICER_AUTHORIZATION = Object.freeze({
  phase: 'T5_OPERATIONALIZATION_SPECIFICATION' as const,
  criterionOperationalizationSpecificationCount:
    FACE_TRADITIONAL_T5_FIVE_OFFICER_OPERATIONALIZATION_SPECS.length,
  expectedCriterionOperationalizationSpecificationCount: 28 as const,
  allFiveFormationSpecificationsPresent: true as const,
  concreteCoordinateFrameAuthorized: false as const,
  executableMetricFormulaAuthorized: false as const,
  traditionalMetricBindingAuthorized: false as const,
  captureCalibrationProtocolAuthorized: false as const,
  numericThresholdAuthorized: false as const,
  booleanFormationEvaluatorAuthorized: false as const,
  criterionWeightingAuthorized: false as const,
  partialSatisfactionScoringAuthorized: false as const,
  automaticOfficerFormationStateAuthorized: false as const,
  traditionalOutcomeClaimAuthorized: false as const,
  productionAuthorization: false as const,
});

export const FACE_TRADITIONAL_T5_FIVE_OFFICER_T6_HANDOFF = Object.freeze({
  nextPhase: 'T6_FIVE_OFFICERS_METHODOLOGY_PACK_CANDIDATE' as const,
  candidateMethodologyRefs: [
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.mapping,
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.listening,
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.longevity,
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.inspection,
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.discernment,
    FACE_TRADITIONAL_T4_FIVE_OFFICER_METHOD_REFS.intake,
  ] as const,
  packCandidateMayInclude: [
    'T3 scan-checked 神相 NLC-1925 witness/passages',
    'T4 source-qualified 五官 mapping and formation methodology identities',
    'T5 abstract criterion operationalization specifications',
    'T5 formation-level fail-closed specifications',
    'T5 binding/capture prerequisites',
    'explicit authority gates',
  ] as const,
  packCandidateMustNotClaim: [
    'executable RGB/CV binding',
    'numeric criterion thresholds',
    'Boolean 官成 evaluator',
    'criterion weighting or partial score',
    'automatic 官成 state',
    'traditional outcome claim',
    'Production readiness',
  ] as const,
  remainingExternalDependencies: [
    'face-observation-engine neutral observation contracts',
    'face-reading-binding methodology-specific semantic bindings',
    'capture calibration protocols for appearance constructs',
    'source-grounded definitions for unresolved named regions and figurative forms',
    'historical-measure interpretation for 細長極寸',
  ] as const,
});
