import { deterministicContentHash } from './rule-registry.js';
import {
  buildCurrentSajuEngineCapabilityFrontier,
  type SajuEngineCapabilityKey,
} from './saju-engine-capability-frontier.js';

export const SAJU_R1_CANONICAL_CAPABILITY_RUNTIME_AUDIT_VERSION =
  'myeonghwa-saju-r1-canonical-capability-runtime-audit-v1' as const;

export type SajuR1RuntimeState = 'IMPLEMENTED' | 'PARTIAL' | 'RESEARCH_ONLY' | 'RUNTIME_UNREACHABLE' | 'BLOCKED' | 'MISSING' | 'UNKNOWN';
export type SajuR1ProductReadiness = 'ALREADY_USABLE' | 'NEEDS_INTEGRATION' | 'NEEDS_RULE_SYNTHESIS' | 'NEEDS_BOUNDED_RESEARCH' | 'NOT_REQUIRED_FOR_CURRENT_PRODUCT';

export interface SajuR1AuditEntry {
  readonly id: string;
  readonly layer: 'calculation' | 'structural' | 'domain' | 'extended' | 'consumer' | 'verification';
  readonly capability: string;
  readonly methodology: { readonly id: string; readonly status: string } | null;
  readonly rule: { readonly id: string; readonly status: string } | null;
  readonly interpretationPack: { readonly id: string; readonly status: string } | null;
  readonly claim: { readonly type: string; readonly state: string } | null;
  readonly sourceEvidenceState: string;
  readonly requiredInputs: readonly string[];
  readonly readingProfile: string | null;
  readonly profileAuthorizationState: string;
  readonly runtimeState: SajuR1RuntimeState;
  readonly runtimeReachable: boolean;
  readonly existingTests: readonly string[];
  readonly benchmarkEvidence: readonly string[];
  readonly knownGap: string;
  readonly productReadiness: SajuR1ProductReadiness;
  readonly consumer: string;
  readonly evidencePaths: readonly string[];
  readonly nextAction: string;
  readonly frontierCapabilityKey: SajuEngineCapabilityKey | null;
}

const OBSERVATIONS: readonly SajuR1AuditEntry[] = Object.freeze([
  {"id":"birth-input","layer":"calculation","capability":"Birth Input","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["calendarType","date","time","sexForTraditionalCalculation"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/product-host-birth-date-input.test.ts"],"benchmarkEvidence":[],"knownGap":"No R1 blocker found for bounded birth input handling.","productReadiness":"ALREADY_USABLE","consumer":"calculation","evidencePaths":["src/calculation/calculation-engine.ts"],"nextAction":"Keep as shared T0 substrate.","frontierCapabilityKey":null},
  {"id":"calculation-policy","layer":"calculation","capability":"Calculation Policy","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["calculation policy profile"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-boundary.test.ts"],"benchmarkEvidence":[],"knownGap":"No R1 blocker found in policy selection.","productReadiness":"ALREADY_USABLE","consumer":"calculation","evidencePaths":["src/calculation/calculation-policy-profiles.ts"],"nextAction":"Keep policy versioning explicit.","frontierCapabilityKey":null},
  {"id":"canonical-snapshot","layer":"calculation","capability":"Canonical Saju Snapshot","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["birth input","calculation policy"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-core.test.ts"],"benchmarkEvidence":[],"knownGap":"Snapshot is implemented but is not semantic authority.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/calculation-engine.ts","src/contracts/calculation.ts"],"nextAction":"Preserve snapshot/authority separation.","frontierCapabilityKey":null},
  {"id":"pillars","layer":"calculation","capability":"Four Pillars","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["normalized birth instant"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-authoritative-fixtures.test.ts"],"benchmarkEvidence":[],"knownGap":"No R1 blocker found for pillar facts.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/manseryeok-adapter.ts"],"nextAction":"Reuse canonical pillar facts.","frontierCapabilityKey":null},
  {"id":"day-master","layer":"calculation","capability":"Day Master","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["day pillar"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-core.test.ts"],"benchmarkEvidence":[],"knownGap":"No R1 blocker found for day-master fact.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/manseryeok-adapter.ts","src/contracts/calculation.ts"],"nextAction":"Reuse canonical day-master fact.","frontierCapabilityKey":null},
  {"id":"ten-god-mapping","layer":"calculation","capability":"Ten-God Mapping Facts","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["day master","stems","branches"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-core.test.ts"],"benchmarkEvidence":[],"knownGap":"Mapping fact exists; contextual meaning remains a separate structural concern.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/manseryeok-adapter.ts","src/contracts/calculation.ts"],"nextAction":"Do not collapse mapping into contextual interpretation.","frontierCapabilityKey":null},
  {"id":"hidden-stems","layer":"calculation","capability":"Hidden Stems","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["branches"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-core.test.ts"],"benchmarkEvidence":[],"knownGap":"No R1 blocker found for hidden-stem facts.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/hidden-stems.ts","src/calculation/calculation-engine.ts"],"nextAction":"Reuse facts without inventing weighting semantics.","frontierCapabilityKey":null},
  {"id":"solar-term-context","layer":"calculation","capability":"Solar-Term Context","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["birth instant","timezone policy"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-authoritative-fixtures.test.ts"],"benchmarkEvidence":[],"knownGap":"Fact generation is implemented; structural seasonal semantics are separate.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/calculation-engine.ts","src/contracts/calculation.ts"],"nextAction":"Reuse context as input only.","frontierCapabilityKey":null},
  {"id":"five-element-facts","layer":"calculation","capability":"Five-Element Facts","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["pillars"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-core.test.ts"],"benchmarkEvidence":[],"knownGap":"Facts exist; no numeric score is authorized by this audit.","productReadiness":"ALREADY_USABLE","consumer":"interpretation","evidencePaths":["src/calculation/manseryeok-adapter.ts","src/contracts/calculation.ts"],"nextAction":"Keep facts distinct from strength conclusions.","frontierCapabilityKey":null},
  {"id":"luck-cycle-calculation","layer":"calculation","capability":"Luck-Cycle Calculation Facts","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["birth input","pillars","policy"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/calculation-authoritative-fixtures.test.ts"],"benchmarkEvidence":[],"knownGap":"Calculation facts exist; Daewoon interpretation synthesis remains incomplete.","productReadiness":"ALREADY_USABLE","consumer":"temporal research","evidencePaths":["src/calculation/manseryeok-adapter.ts","src/contracts/calculation.ts"],"nextAction":"Feed only admitted temporal rules.","frontierCapabilityKey":null},
  {"id":"ambiguity-scenarios","layer":"calculation","capability":"Ambiguity / Scenario Facts","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["ambiguous or unknown birth time"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/scenario-evaluation-audit.test.ts","test/unknown-time-planner.test.ts"],"benchmarkEvidence":[],"knownGap":"Scenario preservation is implemented; downstream domains must remain scenario-aware.","productReadiness":"ALREADY_USABLE","consumer":"reading composition","evidencePaths":["src/calculation/calculation-engine.ts","src/reading/scenario-aware-reading-composition.ts"],"nextAction":"Retain fail-closed scenario propagation.","frontierCapabilityKey":null},
  {"id":"month-season","layer":"structural","capability":"Month / Season Semantics","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["month branch","solar-term context"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/i18a-month-branch-strength-evidence.test.ts"],"benchmarkEvidence":[],"knownGap":"Season/month evidence exists but chart-level synthesis is not a single governed shared claim surface.","productReadiness":"NEEDS_INTEGRATION","consumer":"structural interpretation","evidencePaths":["src/research/i18a-month-branch-strength-evidence.ts"],"nextAction":"Integrate admitted month/season context before new domain-specific copies.","frontierCapabilityKey":null},
  {"id":"root-tonggen","layer":"structural","capability":"Root / Tonggen","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["hidden stems","branch positions","relations"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-root-strength-dependency-map.test.ts","test/general-natal-root-term-binding-authority.test.ts"],"benchmarkEvidence":[],"knownGap":"Large bounded research substrate exists, but no single governed executable root/Tonggen synthesis is proven.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/general-natal-root-strength-dependency-map.ts","src/research/general-natal-root-term-binding-authority.ts"],"nextAction":"Synthesize existing bounded root predicates before more source hunting.","frontierCapabilityKey":null},
  {"id":"strength","layer":"structural","capability":"旺衰 / 強弱","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["season","root","support/challenge","interactions"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/i23-strength-decision-readiness-v2.test.ts","test/general-natal-wang-shuai-qiang-ruo-semantic-axis-authority.test.ts"],"benchmarkEvidence":[],"knownGap":"Research primitives and readiness work exist, but a governed chart-level strength conclusion is not proven reachable.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/i23-strength-decision-readiness-v2.ts","src/research/general-natal-wang-shuai-qiang-ruo-semantic-axis-authority.ts"],"nextAction":"Compose existing primitives into a deterministic bounded synthesis.","frontierCapabilityKey":null},
  {"id":"dang-zhong","layer":"structural","capability":"黨眾 / 助寡","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["root","support constituents","month context"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-tonggen-dang-zhong-support-constituent-authority.test.ts"],"benchmarkEvidence":[],"knownGap":"Constituent authority evidence exists without a shared executable chart-level synthesis.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/general-natal-tonggen-dang-zhong-support-constituent-authority.ts"],"nextAction":"Integrate only after root/support primitives are stable.","frontierCapabilityKey":null},
  {"id":"gyeokguk","layer":"structural","capability":"格局","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["month context","ten-god relations","strength/root","interactions"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-pattern-candidate-establishment-formal-boundary-audit.test.ts","test/general-natal-special-pattern-exit-adversarial-corpus.test.ts"],"benchmarkEvidence":[],"knownGap":"Pattern conditions/counterexamples exist, but no governed shared Gyeokguk resolver is proven.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/general-natal-pattern-candidate-establishment-formal-boundary-audit.ts","src/research/general-natal-special-pattern-exit-adversarial-corpus.ts"],"nextAction":"Build bounded resolver from current condition corpus; do not open broad research by default.","frontierCapabilityKey":null},
  {"id":"johoo","layer":"structural","capability":"調候","methodology":{"id":"M-CLIMATE-TIAOHOU","status":"research"},"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["day stem","month/season context"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-tiaohou-priority-conditions.test.ts","test/general-natal-tiaohou-structure-conflict-preservation.test.ts"],"benchmarkEvidence":[],"knownGap":"Research methodology exists but is not a shared governed runtime claim.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/general-natal-tiaohou-priority-conditions.ts","src/research/general-natal-tiaohou-structure-conflict-preservation.ts"],"nextAction":"Synthesize bounded climate claim while preserving disagreement with strength methods.","frontierCapabilityKey":null},
  {"id":"xi-yong-ji","layer":"structural","capability":"喜神 / 用神 / 忌神","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["method-specific structural conclusions"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-xi-yong-ji-shen-scope-observation-authority.test.ts","test/general-natal-yongxi-multimethod-case-corpus.test.ts"],"benchmarkEvidence":[],"knownGap":"Method-specific evidence exists; no single global element preference may be inferred.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"none governed","evidencePaths":["src/research/general-natal-xi-yong-ji-shen-scope-observation-authority.ts","src/research/general-natal-yongxi-multimethod-case-corpus.ts"],"nextAction":"Preserve methodology-qualified outputs and explicit conflicts.","frontierCapabilityKey":null},
  {"id":"ten-god-context","layer":"structural","capability":"Ten-God Contextual Meaning","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["ten-god mapping","position","structure"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":false,"existingTests":["test/general-natal-bing-yi-zhengyin-exact-relation-authority.test.ts","test/general-natal-jia-yi-jiecai-exact-relation-authority.test.ts"],"benchmarkEvidence":[],"knownGap":"Exact relation authorities exist, but broad contextual meaning is not a shared executable synthesis.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"domain candidates","evidencePaths":["src/research/general-natal-bing-yi-zhengyin-exact-relation-authority.ts","src/research/general-natal-jia-yi-jiecai-exact-relation-authority.ts"],"nextAction":"Compose only explicit qualified relations into domain claims.","frontierCapabilityKey":null},
  {"id":"stem-branch-interactions","layer":"structural","capability":"Stem / Branch Interactions","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["pillars","relation facts","season/support context"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/structural-relations.test.ts","test/general-natal-minimal-interaction-predicate-set-executable-claims.test.ts"],"benchmarkEvidence":[],"knownGap":"Base relations are executable; qualification/precedence/effect synthesis remains fragmented.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"structural facts + research","evidencePaths":["src/calculation/structural-relations.ts","src/research/general-natal-minimal-interaction-predicate-set-executable-claims.ts"],"nextAction":"Promote a minimal qualified interaction layer from existing bounded predicates.","frontierCapabilityKey":null},
  {"id":"palace-position","layer":"structural","capability":"Palace / Position Semantics","methodology":null,"rule":null,"interpretationPack":null,"claim":{"type":"relationship.spouse.traditional_spouse_palace_position","state":"bounded_position_only"},"sourceEvidenceState":"repository_evidence_present","requiredInputs":["day branch"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/relationship-spouse-t8-day-branch-palace-project-governed-materiality-decision.test.ts"],"benchmarkEvidence":[],"knownGap":"Exact day-branch spouse-palace position_only semantic is bounded; wider palace meaning remains unauthorized.","productReadiness":"NEEDS_INTEGRATION","consumer":"relationship spouse staging","evidencePaths":["src/research/relationship-spouse-t8-day-branch-palace-project-governed-materiality-decision.ts"],"nextAction":"Materialize only the exact position_only claim into the next governed narrative gate.","frontierCapabilityKey":null},
  {"id":"general-natal","layer":"domain","capability":"General Natal","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["canonical snapshot","admitted claims"],"readingProfile":"myeonghwa-reading-profile-general-natal-v2","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/general-natal-product-vertical-slice.test.ts"],"benchmarkEvidence":[],"knownGap":"Bounded Preview path is usable; this does not establish Production interpretation authority.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview Official","evidencePaths":["src/research/general-natal-useful-reading-candidate.ts","src/interpretation/saju-engine-capability-frontier.ts"],"nextAction":"Use as reference vertical slice while shared structural gaps are synthesized.","frontierCapabilityKey":"general:natal"},
  {"id":"career-natal","layer":"domain","capability":"Career Natal","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["canonical snapshot","career candidate claims"],"readingProfile":"myeonghwa-reading-profile-career-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/career-natal-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Bounded Preview consumer route exists while producer semantics remain research-origin.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview Official","evidencePaths":["src/research/career-natal-reading-candidate.ts"],"nextAction":"Prefer shared structural synthesis over new career-local semantics.","frontierCapabilityKey":"career:natal"},
  {"id":"wealth-natal","layer":"domain","capability":"Wealth Natal","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["canonical snapshot","wealth candidate claims"],"readingProfile":"myeonghwa-reading-profile-wealth-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/wealth-natal-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Bounded Preview consumer route exists while producer semantics remain research-origin.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview Official","evidencePaths":["src/research/wealth-natal-reading-candidate.ts"],"nextAction":"Prefer shared structural synthesis over new wealth-local semantics.","frontierCapabilityKey":"wealth:natal"},
  {"id":"business-natal","layer":"domain","capability":"Business Natal","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["canonical snapshot","business candidate claims"],"readingProfile":"myeonghwa-reading-profile-business-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/business-natal-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Bounded Preview consumer route exists while producer semantics remain research-origin.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview Official","evidencePaths":["src/research/business-natal-reading-candidate.ts"],"nextAction":"Prefer shared structural synthesis over new business-local semantics.","frontierCapabilityKey":"business:natal"},
  {"id":"relationship-general-natal","layer":"domain","capability":"Relationship Natal General","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["canonical snapshot","relationship candidate claims"],"readingProfile":"myeonghwa-reading-profile-relationship-general-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/relationship-natal-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Current bounded Preview remains usable, but new Engine intake is terminally closed with no current semantic candidate.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview Official","evidencePaths":["src/research/relationship-natal-reading-candidate.ts","src/research/relationship-natal-general-terminal-bridge-closure.ts"],"nextAction":"Do not auto-reopen; require a genuinely new semantic candidate.","frontierCapabilityKey":"relationship:natal:general"},
  {"id":"family-natal","layer":"domain","capability":"Family Natal","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["family relation semantics","pillar/star reconciliation"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-family-domain-claim-corpus.test.ts"],"benchmarkEvidence":[],"knownGap":"Corpus exists but executable family classifier is explicitly unauthorized.","productReadiness":"NEEDS_BOUNDED_RESEARCH","consumer":"legacy only","evidencePaths":["src/research/general-natal-family-domain-claim-corpus.ts"],"nextAction":"Research only the first concrete execution blocker when a product slice requires it.","frontierCapabilityKey":null},
  {"id":"relationship-spouse","layer":"domain","capability":"Relationship Spouse","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["spouse T8 admitted inputs","day-branch position claim"],"readingProfile":"myeonghwa-reading-profile-relationship-spouse-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/relationship-spouse-t8-engine-hardening.test.ts","test/relationship-spouse-t8-day-branch-palace-project-governed-materiality-decision.test.ts"],"benchmarkEvidence":[],"knownGap":"Engine P0-P2 exists and project-governed position_only materiality is established, but narrative/delivery/Preview/Production are not thereby granted.","productReadiness":"NEEDS_INTEGRATION","consumer":"legacy / staging","evidencePaths":["src/interpretation/relationship-spouse-t8-engine-producer.ts","src/reading/relationship-spouse-t8-engine-hardening.ts","src/research/relationship-spouse-t8-day-branch-palace-project-governed-materiality-decision.ts"],"nextAction":"Run the next project-governed materialization/integration step without human-review gates.","frontierCapabilityKey":"relationship:natal:spouse"},
  {"id":"annual","layer":"extended","capability":"T9 Annual","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["natal claims","annual temporal facts"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/product-host-annual-temporal-facts.test.ts","test/general-annual-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Executable candidate paths exist but shared admitted temporal semantics/coherence are incomplete.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"legacy ProductHost paths","evidencePaths":["src/research/general-annual-reading-candidate.ts","src/reading/annual-interpretation-facts.ts"],"nextAction":"Prioritize temporal coherence and shared structural overlays before consumer widening.","frontierCapabilityKey":"general:annual"},
  {"id":"monthly","layer":"extended","capability":"T9 Monthly","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["natal claims","monthly temporal facts"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/product-host-monthly-reading-e2e.test.ts","test/general-monthly-reading-candidate.test.ts"],"benchmarkEvidence":[],"knownGap":"Executable candidate paths exist but monthly composition remains Research/legacy bounded.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"legacy ProductHost paths","evidencePaths":["src/research/general-monthly-reading-candidate.ts","src/reading/monthly-interpretation-facts.ts"],"nextAction":"Align monthly layer with admitted annual/natal structural semantics.","frontierCapabilityKey":"general:monthly"},
  {"id":"compatibility","layer":"extended","capability":"T10 Compatibility","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"profile_or_boundary_evidence_only","requiredInputs":["two canonical snapshots","compatibility methodology"],"readingProfile":"myeonghwa-reading-profile-compatibility-natal-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"MISSING","runtimeReachable":false,"existingTests":["test/relationship-spouse-t8-dyadic-compatibility-boundary-evidence.test.ts","test/saju-engine-capability-inventory.test.ts"],"benchmarkEvidence":[],"knownGap":"No dedicated governed T10 producer is proven; spouse research explicitly keeps pairwise compatibility separate.","productReadiness":"NEEDS_BOUNDED_RESEARCH","consumer":"profile only / legacy","evidencePaths":["src/research/relationship-spouse-t8-dyadic-compatibility-boundary-evidence.ts","src/reading/reading-intent-composition.ts"],"nextAction":"Open bounded research only when T10 becomes an active product requirement.","frontierCapabilityKey":"compatibility:natal"},
  {"id":"question-specific","layer":"extended","capability":"T11 Question-Specific","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"profile_or_boundary_evidence_only","requiredInputs":["reading question","admitted domain claims"],"readingProfile":"myeonghwa-reading-profile-question-specific-v1","profileAuthorizationState":"authorized_evidence_selection_only","runtimeState":"MISSING","runtimeReachable":false,"existingTests":["test/saju-engine-capability-inventory.test.ts"],"benchmarkEvidence":[],"knownGap":"Profile exists but no dedicated governed T11 producer is proven.","productReadiness":"NEEDS_BOUNDED_RESEARCH","consumer":"profile only / legacy","evidencePaths":["src/reading/reading-intent-composition.ts"],"nextAction":"Do not synthesize arbitrary Saju meaning from free-form questions.","frontierCapabilityKey":"question_specific:natal"},
  {"id":"daewoon","layer":"extended","capability":"Daewoon Interpretation","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"research_evidence_present","requiredInputs":["luck-cycle facts","natal structural claims","interaction rules"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"RESEARCH_ONLY","runtimeReachable":false,"existingTests":["test/general-natal-dayun-natal-interaction.test.ts","test/general-natal-dayun-temporal-overlay-replay-corpus.test.ts"],"benchmarkEvidence":[],"knownGap":"Substantial Dayun research/replay corpus exists without a governed end-to-end Daewoon reading producer.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"research only","evidencePaths":["src/research/general-natal-dayun-natal-interaction.ts","src/research/general-natal-dayun-temporal-overlay-replay-corpus.ts"],"nextAction":"Synthesize shared temporal overlay rules before a new consumer route.","frontierCapabilityKey":null},
  {"id":"reading-intent-profile","layer":"consumer","capability":"ReadingIntent / DomainReadingProfile","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["reading intent"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/reading-intent-composition.test.ts","test/saju-engine-capability-inventory.test.ts"],"benchmarkEvidence":[],"knownGap":"Profile existence is not semantic authority.","productReadiness":"ALREADY_USABLE","consumer":"all 21 known profile routes","evidencePaths":["src/reading/reading-intent-composition.ts"],"nextAction":"Keep profile selection separate from claim authority.","frontierCapabilityKey":null},
  {"id":"profile-authorization","layer":"consumer","capability":"Profile Authorization","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["content-addressed profile ref"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/reading-profile-authorization.test.ts"],"benchmarkEvidence":[],"knownGap":"Authorization deliberately cannot authorize interpretation rules, claim generation, or domain semantics.","productReadiness":"ALREADY_USABLE","consumer":"evidence selection only","evidencePaths":["src/reading/reading-profile-authorization.ts"],"nextAction":"Preserve narrow authorization constraints.","frontierCapabilityKey":null},
  {"id":"evidence-selector","layer":"consumer","capability":"Evidence Selector / NarrativeEvidenceBundle","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["authorized profile","interpretation claims"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/narrative-evidence-selector.test.ts","test/governed-reading-execution.test.ts"],"benchmarkEvidence":[],"knownGap":"Selection cannot promote unavailable semantic authority.","productReadiness":"ALREADY_USABLE","consumer":"governed reading","evidencePaths":["src/reading/governed-reading-evidence.ts","src/reading/governed-reading-execution.ts"],"nextAction":"Reuse for newly admitted claims only.","frontierCapabilityKey":null},
  {"id":"narrative","layer":"consumer","capability":"Narrative","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["NarrativeEvidenceBundle","claim narrative profiles"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/llm-narrative-orchestrator.test.ts","test/narrative-grounding-validator.test.ts"],"benchmarkEvidence":[],"knownGap":"Narrative runtime exists, but each new claim family still requires exact narrative materiality/profile authority.","productReadiness":"NEEDS_INTEGRATION","consumer":"bounded current routes","evidencePaths":["src/reading/product-reading-service.ts"],"nextAction":"Integrate claims after their bounded semantic/materiality gates.","frontierCapabilityKey":null},
  {"id":"artifact-product-host","layer":"consumer","capability":"ReadingArtifact / ProductHost","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["grounded narrative","reading artifact data"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/official-reading-artifact.test.ts","test/product-host-mvp.test.ts"],"benchmarkEvidence":[],"knownGap":"Host plumbing is not the first blocker for missing semantic families.","productReadiness":"ALREADY_USABLE","consumer":"bounded Preview/product host","evidencePaths":["src/reading/official-reading-artifact.ts","src/preview/preview-product-host.ts"],"nextAction":"Do not rebuild host plumbing for structural research gaps.","frontierCapabilityKey":null},
  {"id":"determinism","layer":"verification","capability":"Determinism","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["same snapshot","same registry","same options"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/interpretation-engine.test.ts"],"benchmarkEvidence":["test/interpretation-engine.test.ts"],"knownGap":"No R1 blocker found in deterministic hashing/execution foundation.","productReadiness":"ALREADY_USABLE","consumer":"engine verification","evidencePaths":["src/interpretation/interpretation-engine.ts","src/interpretation/rule-registry.ts"],"nextAction":"Require deterministic evidence for every new synthesis.","frontierCapabilityKey":null},
  {"id":"discrimination","layer":"verification","capability":"Discrimination","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["paired contrasting cases"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/discriminating-pair-audit.test.ts","test/benchmark-b-discriminating-corpus.test.ts"],"benchmarkEvidence":["test/discriminating-pair-audit.test.ts","test/benchmark-b-discriminating-corpus.test.ts"],"knownGap":"Existing verification substrate is reusable; new structural syntheses still need domain-specific pairs.","productReadiness":"ALREADY_USABLE","consumer":"verification","evidencePaths":["src/verification/discriminating-pair-audit.ts","src/verification/benchmark-b-discriminating-corpus.ts"],"nextAction":"Add bounded pairs with each new shared structural rule.","frontierCapabilityKey":null},
  {"id":"collision-clone","layer":"verification","capability":"Collision / Clone Resistance","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["multiple distinct snapshots","claim graphs"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/interpretation-engine.test.ts"],"benchmarkEvidence":["test/interpretation-engine.test.ts"],"knownGap":"Claim/run identity integrity exists, but no dedicated whole-reading clone/collision benchmark was found.","productReadiness":"NEEDS_INTEGRATION","consumer":"verification","evidencePaths":["src/interpretation/claim-graph.ts","src/interpretation/interpretation-engine.ts"],"nextAction":"Add a focused regression only when shared synthesis changes claim surfaces.","frontierCapabilityKey":null},
  {"id":"scenario-handling","layer":"verification","capability":"Scenario Handling","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["snapshot scenarios","scenario-sensitive rules"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/scenario-aware-reading-coverage.test.ts","test/scenario-evaluation-audit.test.ts"],"benchmarkEvidence":["test/scenario-aware-reading-coverage.test.ts","test/scenario-evaluation-audit.test.ts"],"knownGap":"No R1 blocker found in scenario-preserving infrastructure.","productReadiness":"ALREADY_USABLE","consumer":"reading composition","evidencePaths":["src/reading/scenario-aware-reading-composition.ts","src/interpretation/interpretation-engine.ts"],"nextAction":"Require new rules to declare ambiguity behavior.","frontierCapabilityKey":null},
  {"id":"conflict-preservation","layer":"verification","capability":"Conflict Preservation","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["multiple methodology outputs"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":false,"existingTests":["test/general-natal-tiaohou-structure-conflict-preservation.test.ts","test/general-natal-interaction-precedence-divergence-across-schools.test.ts"],"benchmarkEvidence":["test/general-natal-tiaohou-structure-conflict-preservation.test.ts","test/general-natal-interaction-precedence-divergence-across-schools.test.ts"],"knownGap":"Research proves disagreement must survive, but shared governed conflict representation is not yet a general runtime surface.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"research","evidencePaths":["src/research/general-natal-tiaohou-structure-conflict-preservation.ts","src/research/general-natal-interaction-precedence-divergence-across-schools.ts"],"nextAction":"Preserve method-qualified disagreement in structural synthesis.","frontierCapabilityKey":null},
  {"id":"cross-domain-coherence","layer":"verification","capability":"Cross-Domain Coherence","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["multiple domain readings from one snapshot"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/reading-intent-composition.test.ts","test/product-reading-integration.test.ts"],"benchmarkEvidence":["test/reading-intent-composition.test.ts","test/product-reading-integration.test.ts"],"knownGap":"Current domains route independently; no dedicated whole multi-reading coherence gate is proven.","productReadiness":"NEEDS_INTEGRATION","consumer":"multi-domain reading","evidencePaths":["src/reading/reading-intent-composition.ts","src/reading/product-reading-integration.ts"],"nextAction":"Add WS-H coherence E2E after shared structural synthesis is available.","frontierCapabilityKey":null},
  {"id":"temporal-coherence","layer":"verification","capability":"Temporal Coherence","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["natal context","annual/monthly/Daewoon layers"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"PARTIAL","runtimeReachable":true,"existingTests":["test/temporal-reading-context.test.ts","test/general-natal-nested-temporal-duration-expiry-boundary-corpus.test.ts"],"benchmarkEvidence":["test/temporal-reading-context.test.ts","test/general-natal-nested-temporal-duration-expiry-boundary-corpus.test.ts"],"knownGap":"Temporal context/runtime exists, but annual/monthly/Daewoon semantic layering is not fully governed.","productReadiness":"NEEDS_RULE_SYNTHESIS","consumer":"annual/monthly research routes","evidencePaths":["src/reading/temporal-reading-context.ts","src/research/general-natal-nested-temporal-duration-expiry-boundary-corpus.ts"],"nextAction":"Unify temporal precedence and duration/expiry before widening T9.","frontierCapabilityKey":null},
  {"id":"unknown-hour","layer":"verification","capability":"Unknown-Hour Behavior","methodology":null,"rule":null,"interpretationPack":null,"claim":null,"sourceEvidenceState":"repository_evidence_present","requiredInputs":["unknown birth time"],"readingProfile":null,"profileAuthorizationState":"not_applicable","runtimeState":"IMPLEMENTED","runtimeReachable":true,"existingTests":["test/unknown-time-limit.test.ts","test/unknown-time-planner.test.ts"],"benchmarkEvidence":["test/unknown-time-limit.test.ts","test/unknown-time-planner.test.ts"],"knownGap":"No R1 blocker found in preserving unknown-time uncertainty.","productReadiness":"ALREADY_USABLE","consumer":"calculation + reading","evidencePaths":["src/calculation/calculation-engine.ts"],"nextAction":"Keep downstream rules fail-closed when hour-dependent inputs are unavailable.","frontierCapabilityKey":null},
]);

export function buildSajuR1CanonicalCapabilityRuntimeAudit() {
  const frontier = buildCurrentSajuEngineCapabilityFrontier();
  const frontierKeys = new Set(frontier.entries.map((entry) => entry.capabilityKey));

  for (const entry of OBSERVATIONS) {
    if (
      entry.frontierCapabilityKey !== null &&
      !frontierKeys.has(entry.frontierCapabilityKey)
    ) {
      throw new Error(
        `R1 audit references missing Engine frontier capability: ${entry.frontierCapabilityKey}`,
      );
    }
  }

  const entries = Object.freeze(OBSERVATIONS.map((entry) => Object.freeze(entry)));
  const counts = Object.freeze(
    entries.reduce<Record<SajuR1RuntimeState, number>>(
      (acc, entry) => {
        acc[entry.runtimeState] += 1;
        return acc;
      },
      {
        IMPLEMENTED: 0,
        PARTIAL: 0,
        RESEARCH_ONLY: 0,
        RUNTIME_UNREACHABLE: 0,
        BLOCKED: 0,
        MISSING: 0,
        UNKNOWN: 0,
      },
    ),
  );

  const material = Object.freeze({
    version: SAJU_R1_CANONICAL_CAPABILITY_RUNTIME_AUDIT_VERSION,
    issue: '#1957' as const,
    track: 'saju' as const,
    baseFrontierHash: frontier.frontierHash,
    entries,
    counts,
    constraints: Object.freeze({
      auditIsSemanticAuthority: false as const,
      auditMayPromoteResearchAuthority: false as const,
      auditMayPromoteProductionAuthority: false as const,
      readingProfilePresenceIsSemanticAuthority: false as const,
      researchRuntimePresenceIsProductionAuthority: false as const,
      previewConsumerAuthorityIsProductionSemanticAuthority: false as const,
      externalHumanReviewRequired: false as const,
    }),
  });

  return Object.freeze({
    ...material,
    auditHash: deterministicContentHash(material),
  });
}
